(function(g){var window=this;'use strict';var AQ=function(J){J.publish("cardstatechange",J.g2()&&J.eI()?1:0)},m$=function(J,W){var H=g.Co(W),D=H?W:arguments;
for(H=H?0:1;H<D.length;H++){if(J==null)return;J=J[D[H]]}return J},f6H=function(J){var W=g.Be(J);
J=g.Hs(J);return new g.qf(W.x,W.y,J.width,J.height)},$AZ=function(J,W,H){var D;
return D=g.eQ(J,W,function(){g.Af(D);H.apply(J,arguments)},{})},Um=function(J){J=g.m2(J);
delete Om[J];g.yS(Om)&&jW&&jW.stop()},gZB=function(){jW||(jW=new g.SJ(function(){SQG()},20));
var J=jW;J.isActive()||J.start()},SQG=function(){var J=g.xe();
g.OF(Om,function(W){CCG(W,J)});
g.yS(Om)||gZB()},PC=function(J,W,H,D){g.z0.call(this);
if(!Array.isArray(J)||!Array.isArray(W))throw Error("Start and end parameters must be arrays");if(J.length!=W.length)throw Error("Start and end points must be the same length");this.A=J;this.B=W;this.duration=H;this.Z=D;this.coords=[];this.progress=this.L=0;this.V=null},CCG=function(J,W){W<J.startTime&&(J.endTime=W+J.endTime-J.startTime,J.startTime=W);
J.progress=(W-J.startTime)/(J.endTime-J.startTime);J.progress>1&&(J.progress=1);J.L=1E3/(W-J.V);J.V=W;eyS(J,J.progress);J.progress==1?(J.C=0,Um(J),J.onFinish(),J.Kp()):J.isPlaying()&&J.JI()},eyS=function(J,W){typeof J.Z==="function"&&(W=J.Z(W));
J.coords=Array(J.A.length);for(let H=0;H<J.A.length;H++)J.coords[H]=(J.B[H]-J.A[H])*W+J.A[H]},AJp=function(J,W){g.x1.call(this,J);
this.coords=W.coords;this.x=W.coords[0];this.y=W.coords[1];this.z=W.coords[2];this.duration=W.duration;this.progress=W.progress;this.fps=W.L;this.state=W.C},tQ=function(J,W,H,D,Y){PC.call(this,W,H,D,Y);
this.element=J},xH=function(J,W,H,D,Y){if(W.length!=2||H.length!=2)throw Error("Start and end points must be 2D");
tQ.call(this,J,W,H,D,Y)},mAY=function(J){return Math.pow(J,3)},OBG=function(J){return 3*J*J-2*J*J*J},zG=function(J){return J.baseUrl||null},VK=function(J,W){return g.IS(g.Xt(J,W),H=>!!H)},jHp=function(J,W,H){function D(Uw){var Lo=Uw.hovercardButton;
if(!Lo)return null;Lo=Lo.subscribeButtonRenderer;if(!Lo)return null;var Te=p(Lo.unsubscribedButtonText),Qk=p(Lo.subscribedButtonText);if(Lo.subscribed){var Vt=p(Lo.subscriberCountWithUnsubscribeText);var hp=p(Lo.subscriberCountText)}else Vt=p(Lo.subscriberCountText),hp=p(Lo.subscriberCountWithSubscribeText);var gA=null;return Uw.signinEndpoint&&((gA=m$(Uw,"signinEndpoint","webNavigationEndpointData","url"))||(gA=g.I(Lo.signInEndpoint?.commandMetadata,g.ey)?.url),!gA)?null:Te&&(Qk||gA)?{subscribed:Lo.subscribed,
subscribeText:Te,subscribeCount:Vt,unsubscribeText:Qk,unsubscribeCount:hp,enabled:Lo.enabled,signinUrl:gA,classic:Uw.useClassicSubscribeButton}:null}
function Y(Uw){if(Uw){var Lo=[],Te=Uw.videoId;Te&&Lo.push("v="+Te);(Te=Uw.playlistId)&&Lo.push("list="+Te);(Uw=Uw.startTimeSeconds)&&Lo.push("t="+Uw);return"/watch?"+Lo.join("&")}}
function p(Uw){if(!Uw)return null;var Lo=Uw.simpleText;return Lo?Lo:Uw.runs?g.Xt(Uw.runs,Te=>Te.text).join(""):null}
W=W.endscreenElementRenderer;if(!W)return null;var E=W.style,Q=W.endpoint||{},w=null,Z=null,b=!1,K=null,C=null,e=null,m=null,u=!1,n=null,l=null,h=null,X=null,v=null,HV=null;if(E==="VIDEO")g.I(Q,g.H0)?w=g.I(Q,g.H0).url:(HV=g.I(Q,g.i0),w=Y(HV)),Z=!1,K=J,W.thumbnailOverlays?(b=W.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,C=p(b.text),b=b.style==="LIVE"):C=p(W.videoDuration);else if(E==="PLAYLIST")g.I(Q,g.H0)?w=g.I(Q,g.H0).url:(HV=g.I(Q,g.i0),w=Y(HV)),Z=!1,K=J,e=p(W.playlistLength);else if(E===
"CHANNEL"){if(u=m$(Q,"browseEndpoint","browseId"))m=u,w=`/channel/${m}`;Z=!1;K="new";(u=!!W.isSubscribe)?n=D(W):l=p(W.subscribersText)}else E==="WEBSITE"?((h=m$(Q,"urlEndpoint","url"))&&(w=h),Z=!0,K="new",h=W.icon.thumbnails[0].url):E==="CREATOR_MERCHANDISE"&&(W.productPrice&&(X=p(W.productPrice)),W.additionalFeesText&&(v=p(W.additionalFeesText)),(Z=m$(Q,"urlEndpoint","url"))&&(w=Z),Z=!0,K="new");J=m$(W,"title","accessibility","accessibilityData","label");var SL=W.endpoint?W.endpoint.clickTrackingParams:
null,PV="";if(W.metadata){let Uw=p(W.metadata);Uw&&(PV=Uw)}return{id:`element-${H}`,type:E,title:p(W.title),metadata:PV,callToAction:p(W.callToAction),qI:W.image,iconUrl:h,left:Number(W.left),width:Number(W.width),top:Number(W.top),aspectRatio:Number(W.aspectRatio),startMs:Math.floor(Number(W.startMs)),endMs:Math.floor(Number(W.endMs)),videoDuration:C,cY:b,playlistLength:e,channelId:m,subscribeButton:n,subscribersText:l,isSubscribe:u,targetUrl:w||null,eO:Z,sessionData:SL?{itct:SL}:null,t4:K,mx:J?
J:null,isPlaceholder:W.isPlaceholder,impressionUrls:VK(W.impressionUrls||[],zG),Ik:VK(W.hovercardShowUrls||[],zG),clickUrls:VK(Q.loggingUrls||[],zG),visualElement:g.yJ(W.trackingParams),productPrice:X,additionalFeesText:v,watchEndpoint:HV||null}},NC=function(J,W){var H={startMs:Math.floor(Number(J.startMs)),
impressionUrls:VK(J.impressionUrls||[],zG),elements:VK(J.elements||[],(D,Y)=>jHp(W,D,Y))};
J.trackingParams&&(H.visualElement=g.yJ(J.trackingParams));return H},uI=function(J){return J.player.G().playerStyle==="creator-endscreen-editor"},UAH=function(J){return J.player.getVideoData().vZ?"current":J.J?"new":"current"},sm=function(J,W,H=!0){J.player.lx("creatorendscreen");
J.Y&&(J.Y.dispose(),J.Y=null,J.Z.dispose(),J.Z=null);for(var D of Object.values(J.A))D.dispose();J.A={};J.L={};J.S.length>0&&(J.S.forEach(Y=>{Y.dispose()}),J.S.length=0);
J.C&&(g.P7(J.C,"ytp-ce-element-show"),J.C.setAttribute("aria-hidden","true"));J.B=0;if((J.endscreen=W)&&W.elements){H&&PCT(J);H=[];D=new g.ha(W.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});H.push(D);J.player.G().Y||(J.Y=new g.c({D:"div",W:"ytp-ce-shadow"}),g.mL(J.player,J.Y.element,4),J.Z=new g.qY(J.Y,200));for(D=0;D<W.elements.length;++D){let Y=W.elements[D],p=tBB(J,Y);if(!p){g.Jx(new g.IV("buildEndscreenElement null",Y));continue}J.A[Y.id]=p;J.L[Y.id]=Y;g.mL(J.player,
p.element,4);let E=new g.ha(Y.startMs,Y.endMs,{id:"ytp-ce-element-"+Y.id,namespace:"creatorendscreen"});H.push(E);xAp(J,p,Y)}J.player.yR(H);J.dh()}},zyP=function(J){var W=J.player.getVideoData(),H=W.videoId;
J.V&&J.V.abort();H={method:"POST",onFinish:Y=>{var p=J.V=null;Y.status===200&&(Y=Y.responseText,Y.substring(0,3)===")]}"&&(Y=Y.substring(3),p=JSON.parse(Y),p=NC(p,UAH(J))));sm(J,p)},
urlParams:{v:H},withCredentials:!0};J.J&&(H.urlParams.ptype="embedded");var D=W.Pd;D&&(H.postParams={ad_tracking:D});if(W=g.Znp(W))if(W=g.lu(W),W=g.sz(W))J.V=g.AZ(W,H)},PCT=function(J){var W=g.IP(),H=g.XG();
H&&W&&J.endscreen.visualElement&&g.BH(g.KY)(void 0,H,W,J.endscreen.visualElement)},tBB=function(J,W){var H=null;
switch(W.type){case "VIDEO":J={D:"div",Tl:["ytp-ce-element","ytp-ce-video"],N:{tabindex:"0","aria-label":W.mx||"","aria-hidden":"true"},K:[{D:"div",W:"ytp-ce-element-shadow"},{D:"div",W:"ytp-ce-covering-image",N:GG(W)},{D:"div",W:"ytp-ce-covering-shadow-top"},{D:"a",W:"ytp-ce-covering-overlay",N:{href:qC(J,W.targetUrl),tabindex:"-1"},K:[{D:"div",Tl:["ytp-ce-video-title","ytp-webkit-ellipsis"],N:{dir:g.G0(W.title||"")},tR:W.title},{D:"div",W:W.cY?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
tR:W.videoDuration||void 0}]}]};H=new g.c(J);break;case "PLAYLIST":J={D:"div",Tl:["ytp-ce-element","ytp-ce-playlist"],N:{tabindex:"0","aria-label":W.mx||"","aria-hidden":"true"},K:[{D:"div",W:"ytp-ce-element-shadow"},{D:"div",W:"ytp-ce-covering-image",N:GG(W)},{D:"div",W:"ytp-ce-covering-shadow-top"},{D:"a",W:"ytp-ce-covering-overlay",N:{href:qC(J,W.targetUrl),tabindex:"-1"},K:[{D:"div",Tl:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],N:{dir:g.G0(W.title||"")},tR:W.title},{D:"div",W:"ytp-ce-playlist-count",
K:[{D:"div",W:"ytp-ce-playlist-icon"},{D:"div",W:"ytp-ce-playlist-count-text",tR:W.playlistLength||void 0}]}]}]};H=new g.c(J);break;case "CHANNEL":H={D:"div",Tl:["ytp-ce-element","ytp-ce-channel",W.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],N:{tabindex:"0","aria-label":W.mx||"","aria-hidden":"true"},K:[{D:"div",W:"ytp-ce-element-shadow"},{D:"div",W:"ytp-ce-expanding-overlay",K:[{D:"div",W:"ytp-ce-expanding-overlay-hider"},{D:"div",W:"ytp-ce-expanding-overlay-background"},{D:"div",W:"ytp-ce-expanding-overlay-content",
K:[{D:"div",W:"ytp-ce-expanding-overlay-body",K:[{D:"div",W:"ytp-ce-expanding-overlay-body-padding",K:[{D:"a",Tl:["ytp-ce-channel-title","ytp-ce-link"],N:{href:qC(J,W.targetUrl),target:"_blank",tabindex:"-1",dir:g.G0(W.title||"")},tR:W.title},W.subscribeButton?{D:"div",W:"ytp-ce-subscribe-container",K:[{D:"div",W:"ytp-ce-channel-subscribe"}]}:"",W.subscribersText?{D:"div",W:"ytp-ce-channel-subscribers-text",N:W.mx?{"aria-hidden":"true"}:{},tR:W.subscribersText}:"",W.metadata?{D:"div",Tl:["ytp-ce-channel-metadata",
"yt-ui-ellipsis","yt-ui-ellipsis-3"],tR:W.metadata}:""]}]}]}]},{D:"div",W:"ytp-ce-expanding-image",N:GG(W)}]};H=new g.c(H);let Y=g.on(document,"div","ytp-ce-channel-subscribe",H.element)[0];if(W.subscribeButton&&W.channelId){g.jJ(Y,"ytp-ce-subscribe-button");let p;if(J.player.G().Y){var D=null;p=W.sessionData.itct}else D="endscreen",p=null;D=new VBS(W.subscribeButton.subscribeText,W.subscribeButton.subscribeCount,W.subscribeButton.unsubscribeText,W.subscribeButton.unsubscribeCount,!!W.subscribeButton.enabled,
!!W.subscribeButton.classic,W.channelId,!!W.subscribeButton.subscribed,D,p,J.player);Y.appendChild(D.element);J.S.push(D)}break;case "WEBSITE":J={D:"div",Tl:["ytp-ce-element","ytp-ce-website"],N:{tabindex:"0","aria-label":W.mx||"","aria-hidden":"true"},K:[{D:"div",W:"ytp-ce-element-shadow"},{D:"div",W:"ytp-ce-expanding-overlay",K:[{D:"div",W:"ytp-ce-expanding-overlay-hider"},{D:"div",W:"ytp-ce-expanding-overlay-background"},{D:"div",W:"ytp-ce-expanding-overlay-content",K:[{D:"div",W:"ytp-ce-expanding-overlay-body",
K:[{D:"div",W:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",W:"ytp-ce-website-title",N:{dir:g.G0(W.title||"")},tR:W.title},{D:"div",W:"ytp-ce-website-metadata",tR:W.metadata},{D:"a",Tl:["ytp-ce-website-goto","ytp-ce-link"],N:{href:qC(J,W.targetUrl),target:"_blank",tabindex:"-1"},tR:W.callToAction}]}]}]}]},{D:"div",W:"ytp-ce-expanding-image",N:GG(W)},{D:"div",W:"ytp-ce-expanding-icon",N:N0Y(W.iconUrl)}]};H=new g.c(J);break;case "CREATOR_MERCHANDISE":H="",W.productPrice&&(H={D:"div",W:"ytp-ce-merchandise-price-container",
K:[{D:"div",W:"ytp-ce-merchandise-price",tR:W.productPrice}]},W.additionalFeesText&&H.K.push({D:"div",W:"ytp-ce-merchandise-additional-fees",tR:W.additionalFeesText})),J={D:"div",Tl:["ytp-ce-element","ytp-ce-merchandise"],N:{tabindex:"0","aria-label":W.mx||"","aria-hidden":"true"},K:[{D:"div",W:"ytp-ce-element-shadow"},{D:"div",W:"ytp-ce-expanding-overlay",K:[{D:"div",W:"ytp-ce-expanding-overlay-hider"},{D:"div",W:"ytp-ce-expanding-overlay-background"},{D:"div",W:"ytp-ce-expanding-overlay-content",
K:[{D:"div",W:"ytp-ce-expanding-overlay-body",K:[{D:"div",W:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",W:"ytp-ce-merchandise-title",N:{dir:g.G0(W.title||"")},tR:W.title},H,{D:"div",W:"ytp-ce-merchandise-metadata",tR:W.metadata},{D:"a",Tl:["ytp-ce-merchandise-goto","ytp-ce-link"],N:{href:qC(J,W.targetUrl),target:"_blank",tabindex:"-1"},tR:W.callToAction}]}]}]}]},{D:"div",W:"ytp-ce-expanding-image",N:GG(W)},{D:"div",W:"ytp-ce-merchandise-invideo-cta-container",K:[{D:"div",W:"ytp-ce-merchandise-invideo-cta",
tR:W.callToAction||void 0}]}]},H=new g.c(J)}W.isPlaceholder&&g.jJ(H.element,"ytp-ce-placeholder");return H},xAp=function(J,W,H){function D(){E(1)}
function Y(){E(-1)}
W.listen("mouseenter",()=>{n0(J,W,H)});
W.listen("mouseleave",()=>{lI(J,W,H)});
J.player.G().Y||W.listen("click",()=>{g.jJ(W.element,"ytp-ce-element-hover")});
W.listen("click",Q=>{uuT(J,H,Q)});
W.listen("keypress",Q=>{uuT(J,H,Q)});
W.listen("focus",()=>{n0(J,W,H)});
W.listen("blur",()=>{lI(J,W,H)});
W.listen("touchstart",()=>{n0(J,W,H)});
var p=g.Jd("ytp-ce-expanding-overlay-hider",W.element);p&&W.j(p,"touchstart",Q=>{Q.stopPropagation();g.P7(W.element,"ytp-ce-element-hover");g.P7(W.element,"ytp-ce-force-expand")});
W.listen("keydown",Q=>{J.AR=Q.keyCode===9&&!Q.shiftKey});
var E=Q=>{J.B+=Q;J.B>0?(g.jJ(W.element,"ytp-ce-force-expand"),yK(J,H.id,!0)):(g.P7(W.element,"ytp-ce-force-expand"),g.P7(W.element,"ytp-ce-element-hover"),yK(J,H.id,!1))};
p=Q=>{Q&&(W.listen("blur",()=>{Q.style.display!="none"&&J.AR&&Q.focus()}),W.j(Q,"focus",D),W.j(Q,"blur",Y))};
p(g.Jd("ytp-sb-subscribe",W.element));p(g.Jd("ytp-sb-unsubscribe",W.element));W.listen("focus",D);W.listen("blur",Y)},hQ=function(J,W,H){function D(){p||(Y++,Y===W.length&&(E.stop(),H&&H()))}
if(!W||W.length===0||uI(J))H&&H();else{W=sHH(J,W);var Y=0,p=!1,E=new g.SJ(()=>{p=!0;H&&H()},1E3,J);
E.start();for(J=0;J<W.length;J++)g.ws(W[J],D)}},GG=function(J){if(J.qI)var W=J.qI.thumbnails;
return N0Y(W?W[W.length-1].url:null)},qC=function(J,W){J=J.player.G();
if(W){if(W.startsWith("//"))return J.protocol+":"+W;if(W.startsWith("/"))return g.wm(J)+W}else return"";return W},N0Y=function(J){return J?{style:"background-image: url("+J+")"}:{}},n0=function(J,W,H){g.OK(W.element,"ytp-ce-element-hover")||(H.type==="VIDEO"||H.type==="PLAYLIST"?g.jJ(W.element,"ytp-ce-element-hover"):J.player.G().Y?(new g.SJ(()=>{g.jJ(W.element,"ytp-ce-element-hover")},200)).start():g.jJ(W.element,"ytp-ce-element-hover"),hQ(J,H.Ik),yK(J,H.id,!0))},lI=function(J,W,H){g.P7(W.element,
"ytp-ce-element-hover");
g.P7(W.element,"ytp-ce-force-expand");yK(J,H.id,!1)},uuT=function(J,W,H){if(W.targetUrl&&(!H||H.type!=="keypress"||H.keyCode===13)){for(var D=H.target;D&&!g.OK(D,"ytp-ce-element");){g.OK(D,"subscribe-label")&&iI(J,W);
if(g.OK(D,"ytp-ce-channel-subscribe"))return;D=D.parentElement||null}if(!D||g.OK(D,"ytp-ce-element-hover")){H.preventDefault();H.stopPropagation();if(D=J.A[W.id])lI(J,D,W),D.element.blur();if(H.ctrlKey||H.metaKey||W.t4==="new")iI(J,W),J.player.sendVideoStatsEngageEvent(17,void 0),J.player.pauseVideo(),H=g.lu(qC(J,W.targetUrl)),H=g.sz(H),g.Oy(H,void 0,W.sessionData);else{let Y=g.o_(J.player.G())||J.player.getVideoData().vZ,p=()=>{var E=qC(J,W.targetUrl),Q=W.sessionData,w=W.watchEndpoint,Z=g.W$(E);
Y&&Z&&(Z.v||Z.list)?J.player.g_(Z.v,Q,Z.list,!1,void 0,w||void 0):g.A5(E,Q)};
iI(J,W,()=>{J.player.sendVideoStatsEngageEvent(17,p)})}}}},yK=function(J,W,H){J.Y&&(H?J.Z.show():J.Z.hide());
for(let D of Object.keys(J.A))D!==W&&g.xb(J.A[D].element,"ytp-ce-element-shadow-show",H)},iI=function(J,W,H){hQ(J,W.clickUrls,H);
(J=g.XG())&&W.eO&&g.jK(J,W.visualElement)},sHH=function(J,W){var H=J.player.getVideoData().clientPlaybackNonce;
J=J.player.getCurrentTime().toFixed(2);H={CPN:H,AD_CPN:H,MT:J};J=[];for(let D=0;D<W.length;D++)J.push(GIf(W[D],H));return J},GIf=function(J,W){return J.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,H=>{var D=unescape(H);
D=D.substring(1,D.length-1);return W[D]?escape(W[D]):H})},qQS=function(J){return typeof J==="string"?J:""},I0=function(J,W,H){for(let D in W)if(W[D]===J)return J;
return H},XF=function(J){if(!J)return null;
var W=g.lu(qQS(J.value));W=g.sz(W);if(!W)return null;var H=I0(J.target,nZH,"current");if(H==null)J=null;else{var D=J.show_link_icon;J=new l6f(W,H,D==="true"||D==="false"?D==="true":!0,J.pause_on_navigation!=null?J.pause_on_navigation:!0)}return J},I69=function(J){if(!J)return null;
var W=I0(J.type,yJY),H=I0(J.trigger,hyp);J=J.url;J=Array.isArray(J)&&J.length?J[0]:J;J=XF(J?J:null);return W?new iBY(W,H,J):null},XoT=function(J,W){return g.BV(J.action,W)},L0=function(J,W){J="background-image: url("+J+");";
var H=[];W&&H.push(W);return{D:"div",W:"iv-card-image",N:{style:J},K:H}},dg=function(J){return J.customMessage?R0("div","iv-card-message",J.customMessage):""},vC=function(J){if(!J.metaInfo||J.metaInfo.length===0)return"";
var W=[];for(let H of J.metaInfo)W.push(R0("li","",H));return{D:"ul",W:"iv-card-meta-info",K:W}},FF=function(J,W,H,D){if(D)for(let Y of W)J.C(Y,D,H.id,H.sessionData,H.mS.click,5)},R0=function(J,W,H){W?typeof W==="string"?W={"class":W}:Array.isArray(W)&&(W={"class":W.join(" ")}):W={};
W.dir=g.G0(H);return{D:J,N:W,tR:H}},LMF=function(J){if(!J.customMessage)return"";
var W=["iv-card-action","iv-card-primary-link"],H={};J.qR&&(W.push("iv-card-action-icon"),H.style="background-image: url("+J.qR+");");H.dir=g.G0(J.customMessage);var D=[{D:"span",tR:J.customMessage}];J.showLinkIcon&&(D.push("\u00a0"),D.push({D:"span",W:"iv-card-link-icon"}));return{D:"div",Tl:W,N:H,K:D}},Ryp=function(J){var W;
(W=J)&&!(W=J.length>1?J.charAt(0)==="/"&&J.charAt(1)!=="/":J==="/")&&(W=J.replace(/^(https?:)?\/\//,"").split("/",1),W=!W||W.length<1||!W[0]?[]:W[0].toLowerCase().split(".").reverse(),W=W[0]==="com"&&W[1]==="youtube"||W[0]==="be"&&W[1]==="youtu");return W?J.indexOf("/redirect?")===-1:!1},dAH=function(J,W){return W?W:Ryp(J)?"current":"new"},BC=function(J,W,H,D,Y,p,E){J.context.C.listen(W,"click",Q=>{J.Mm(H,D,Y,p||[],E||0,Q)});
J.context.C.listen(W,"touchstart",()=>{J.JR=!1});
J.context.C.listen(W,"touchmove",()=>{J.JR=!0})},vZG=function(J){if(g.I(J,g.H0)?.url)return g.I(J,g.H0).url;
if((J=g.I(J,g.i0))&&J.videoId){let W="/watch?v="+J.videoId;J.playlistId&&(W+="&list="+J.playlistId);J.index&&(W+="&index="+J.index);J.startTimeSeconds&&(W+="&t="+J.startTimeSeconds);return W}return null},TG=function(J,W,H){return{e6:(J.impressionLoggingUrlsV2s||[]).map(D=>D.baseUrl||""),
click:(H.loggingUrls||[]).map(D=>D.baseUrl||""),
close:(W.dismissLoggingUrlsV2s||[]).map(D=>D.baseUrl||""),
yk:(W.impressionLoggingUrlsV2s||[]).map(D=>D.baseUrl||""),
y3:(W.clickLoggingUrlsV2s||[]).map(D=>D.baseUrl||"")}},WM=function(J,W){if(W.onClickCommand&&g.I(W.onClickCommand,g.oue)?.targetId==="engagement-panel-error-corrections"){J.qm=W;
var H=!0}else H=!1;if(!H||FMF(J,W))if(H=B0S(J,W)){var D={Oh:W,Oi:H.element,zE:!1};if(W.onClickCommand)J.YQ||T0F(J),cC(J,W.id),H=J.findLastIndex(D),g.KZ(J.cards,H,0,D);else{J.isInitialized||cJ9(J);cC(J,W.id);let Y=J.findLastIndex(D);g.KZ(J.cards,Y,0,D);H.pa(J.A,Y);J.DU()}W.autoOpen?J.addCueRange(W.startMs,0x8000000000000,W.id,()=>{J.Y||(J.C=D,o0(J),oZH(J,D),Jn(J,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(H=J.context.X.getCurrentTime()*1E3,H<5E3&&H>W.startMs&&JET(J,D),J.addCueRange(W.startMs,W.startMs+1,W.id,
()=>{JET(J,D)}),o0(J))}},HM=function(J){J.Y&&(J.fa.hide(),J.B4.A(),g.P7(J.context.X.getRootNode(),g.mK.IV_DRAWER_OPEN),J.Y=!1,AQ(J.X),J.Z&&J.Z.stop(),J.Z=new g.SJ(()=>{J.b9&&(J.b9.focus(),J.b9=null)},330),J.Z.start())},WSf=function(J,W){W=W.data;
W.autoOpenMs&&J.addCueRange(W.autoOpenMs,0x8000000000000,"",()=>{Jn(J,"YOUTUBE_DRAWER_AUTO_OPEN")});
W.autoCloseMs&&J.addCueRange(W.autoCloseMs,0x8000000000000,"",()=>{HM(J)});
var H=W.headerText;g.Sj(J.Ag,H);J.S&&J.S.setAttribute("data-tooltip-title",H);W.eventId&&(J.eventId=W.eventId);J.yY=g.yJ(W.trackingParams);J.B=g.yJ(W.closeTrackingParams);J.R9=g.yJ(W.iconTrackingParams)},DR=function(J,W,H){var D=-1,Y=-1;
for(let p=0;p<J.length;p++){if(J[p].height===W||J[p].width===H)return J[p];((J[p].height||0)<W||(J[p].width||0)<H)&&(D<0||(J[D].height||0)<(J[p].height||0)||(J[D].width||0)<(J[p].width||0))?D=p:((J[p].height||0)>=W||(J[p].width||0)>=H)&&(Y<0||(J[Y].height||0)>(J[p].height||0)||(J[Y].width||0)>(J[p].width||0))&&(Y=p)}return J[Y>=0?Y:D]},Y3=function(J,W,H,D){return{feature:H.feature?H.feature:"cards",
src_vid:J.context.videoData.videoId,annotation_id:W,ei:J.context.videoData.eventId||"",itct:D.trackingParams||""}},HUp=function(J,W){var H=W.cardId?W.cardId:`cr:${J.L}`,D=J.X.G().experiments.Er("enable_error_corrections_infocard_web_client");
if(!W.content&&W.teaser.simpleCardTeaserRenderer&&D){D=W.teaser.simpleCardTeaserRenderer;var Y=W.icon?W.icon.infoCardIconRenderer:null;if(D.channelAvatar&&D.channelAvatar.thumbnails&&D.channelAvatar.thumbnails.length>0)var p=DR(D.channelAvatar.thumbnails,22,22).url;W={id:H,timestamp:J.L,type:"simple",teaserText:g.uT(D.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:{},sponsored:!1,mS:{},b1:null,G_:D.trackingParams?
g.yJ(D.trackingParams):null,R9:Y&&Y.trackingParams?g.yJ(Y.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,qR:null,title:"",customMessage:"",url:null,onClickCommand:D.onTapCommand||null,vx:p};WM(J,W)}else if(W.content?.simpleCardContentRenderer){if(!W.cueRanges.length)return;p=W.content?.simpleCardContentRenderer;D=W.teaser.simpleCardTeaserRenderer;Y=W.icon?W.icon.infoCardIconRenderer:null;W={id:H,timestamp:J.L,type:"simple",teaserText:g.uT(D.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),
startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:Y3(J,H,W,p),sponsored:!1,mS:TG(p,D,p.command),b1:p.trackingParams?g.yJ(p.trackingParams):null,G_:D.trackingParams?g.yJ(D.trackingParams):null,R9:Y&&Y.trackingParams?g.yJ(Y.trackingParams):null,imageUrl:DR(p.image.thumbnails,290,290).url,displayDomain:p.displayDomain?g.uT(p.displayDomain):null,showLinkIcon:!!p.showLinkIcon,qR:null,title:p.title?g.uT(p.title):"",customMessage:p.callToAction?g.uT(p.callToAction):"",url:g.I(p.command,
g.H0).url?XF({pause_on_navigation:!J.context.videoData.isLivePlayback,target:"new",value:g.I(p.command,g.H0).url}):null,onClickCommand:null};WM(J,W)}else if(W.content?.collaboratorInfoCardContentRenderer){if(!W.cueRanges.length)return;p=W.content?.collaboratorInfoCardContentRenderer;D=W.teaser.simpleCardTeaserRenderer;Y=W.icon?W.icon.infoCardIconRenderer:null;W={id:H,timestamp:J.L,type:"collaborator",teaserText:g.uT(D.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),
autoOpen:!!W.autoOpen,sessionData:Y3(J,H,W,p),sponsored:!1,mS:TG(p,D,p.endpoint),b1:p.trackingParams?g.yJ(p.trackingParams):null,G_:D.trackingParams?g.yJ(D.trackingParams):null,R9:Y&&Y.trackingParams?g.yJ(Y.trackingParams):null,channelId:g.I(p.endpoint,g.b8).browseId,customMessage:p.customText?g.uT(p.customText):null,profileImageUrl:DR(p.channelAvatar.thumbnails,290,290).url,title:p.channelName?g.uT(p.channelName):"",metaInfo:[p.subscriberCountText?g.uT(p.subscriberCountText):""],url:XF({pause_on_navigation:!J.context.videoData.isLivePlayback,
target:"new",value:g.I(p.endpoint,g.b8).canonicalBaseUrl?g.I(p.endpoint,g.b8).canonicalBaseUrl:`/channel/${g.I(p.endpoint,g.b8).browseId}`}),onClickCommand:null};WM(J,W)}else if(W.content?.playlistInfoCardContentRenderer){if(!W.cueRanges.length)return;p=W.content?.playlistInfoCardContentRenderer;D=W.teaser.simpleCardTeaserRenderer;Y=W.icon?W.icon.infoCardIconRenderer:null;W={id:H,timestamp:J.L,type:"playlist",teaserText:g.uT(D.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),
autoOpen:!!W.autoOpen,sessionData:Y3(J,H,W,p),sponsored:!1,mS:TG(p,D,p.action),b1:p.trackingParams?g.yJ(p.trackingParams):null,G_:D.trackingParams?g.yJ(D.trackingParams):null,R9:Y&&Y.trackingParams?g.yJ(Y.trackingParams):null,Hx:DR(p.playlistThumbnail.thumbnails,258,290).url,customMessage:p.customMessage?g.uT(p.customMessage):null,playlistVideoCount:g.uT(p.playlistVideoCount),title:p.playlistTitle?g.uT(p.playlistTitle):"",metaInfo:[p.channelName?g.uT(p.channelName):"",p.videoCountText?g.uT(p.videoCountText):
""],url:XF({pause_on_navigation:!J.context.videoData.isLivePlayback,target:"new",value:vZG(p.action)}),onClickCommand:null};WM(J,W)}else if(W.content?.videoInfoCardContentRenderer){if(!W.cueRanges.length)return;p=W.content?.videoInfoCardContentRenderer;D=W.teaser.simpleCardTeaserRenderer;Y=W.icon?W.icon.infoCardIconRenderer:null;W={id:H,timestamp:J.L,type:"video",teaserText:g.uT(D.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,
sessionData:Y3(J,H,W,p),sponsored:!1,mS:TG(p,D,p.action),b1:p.trackingParams?g.yJ(p.trackingParams):null,G_:D.trackingParams?g.yJ(D.trackingParams):null,R9:Y&&Y.trackingParams?g.yJ(Y.trackingParams):null,Hx:DR(p.videoThumbnail.thumbnails,258,290).url,videoDuration:p.lengthString?g.uT(p.lengthString):null,customMessage:p.customMessage?g.uT(p.customMessage):null,title:p.videoTitle?g.uT(p.videoTitle):"",metaInfo:[p.channelName?g.uT(p.channelName):"",p.viewCountText?g.uT(p.viewCountText):""],isLiveNow:!!p.badge,
url:XF({pause_on_navigation:!J.context.videoData.isLivePlayback,target:"new",value:vZG(p.action)}),onClickCommand:null};WM(J,W)}J.L++},DbS=function(J,W){return g.BV(J.cards,H=>H.Oh.id===W)},o0=function(J){g.xb(J.X.getRootNode(),"ytp-cards-shopping-active",YB9(J))},cC=function(J,W){if(W=DbS(J,W))W===J.C&&(J.C=null),J.X.removeCueRange(W.Oh.id),g.fR(W.Oi),g.pZ(J.cards,W),J.DU(),o0(J)},Jn=function(J,W,H){if(!J.Y){J.fa.show();
J.aB=new g.SJ(()=>{g.jJ(J.context.X.getRootNode(),g.mK.IV_DRAWER_OPEN)},0);
J.aB.start();J.B4.j(J.A,"mousewheel",Y=>{J.VY.start();Y.preventDefault();Y=Y||window.event;var p=0;Y.type=="MozMousePixelScroll"?p=0==(Y.axis==Y.HORIZONTAL_AXIS)?Y.detail:0:window.opera?p=Y.detail:p=Y.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?Y.wheelDeltaY/-30:Y.wheelDeltaY/-1.2:Y.wheelDelta/-1.6:Y.wheelDeltaY/-3;if(Y=p)J.A.scrollTop+=Y});
J.Y=!0;var D=g.XG();D&&J.yY&&J.B&&g.mo(D,[J.yY,J.B]);W={TRIGGER_TYPE:W};for(let Y of J.cards)Y.zE||(Y.zE=!0,pRZ(J.context.logger,Y.Oh.mS.e6,W)),D&&g.mo(D,[Y.Oh.b1]);AQ(J.X);H&&(J.Z=new g.SJ(()=>{J.b9=J.S;J.Ig.focus()},330),J.Z.start())}},cJ9=function(J){g.UK(J.Ff(),[g.mK.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.mL(J.X,J.V,5);J.Lb();J.S=g.Jd("ytp-cards-button",J.X.getRootNode());J.Ig=g.Jd("iv-drawer-close-button",J.V);J.isInitialized=!0},T0F=function(J){J.AR.push(g.AM("iv-teaser-shown",J.E_,J));
J.AR.push(g.AM("iv-teaser-hidden",J.Ce,J));J.AR.push(g.AM("iv-teaser-clicked",J.kQ,J));J.YQ=!0},FMF=function(J,W){J.qm=W;
var H=J.X.getVideoData();if(!H)return!1;H=g.j3(H.getWatchNextResponse());if(H?.markersMap)for(let Y=0;H?.markersMap.length>Y;Y++){var D=H?.markersMap[Y];if(D.key==="ERROR_CORRECTION_MARKERS"&&(D=D.value?.markers)&&D.length>0)return W.startMs=g.I(D[0],g.GaL)?.timeRangeStartMillis||0,J.qm=null,!0}return!1},B0S=function(J,W){switch(W.type){case "simple":J=J.zl;
var H=W.displayDomain?{D:"div",W:"iv-card-image-text",tR:W.displayDomain}:void 0;var D=LMF(W);H={D:"div",Tl:["iv-card"],K:[{D:"a",W:"iv-click-target",N:{href:W.url?W.url.C()||"":""},K:[L0(W.imageUrl,H),{D:"div",W:"iv-card-content",K:[R0("h2",void 0,W.title),D]}]}]};H=new g.c(H);FF(J,g.cK("iv-click-target",H.element),W,W.url);W=H;break;case "collaborator":J=J.zl;H={D:"div",Tl:["iv-card","iv-card-channel"],K:[{D:"a",Tl:["iv-click-target"],N:{href:W.url.C()||"","data-ytid":W.channelId},K:[L0(W.profileImageUrl),
{D:"div",W:"iv-card-content",K:[dg(W),{D:"h2",W:"iv-card-primary-link",tR:W.title},vC(W)]}]}]};H=new g.c(H);FF(J,g.cK("iv-click-target",H.element),W,W.url);W=H;break;case "playlist":J=J.zl;H={D:"div",Tl:["iv-card","iv-card-playlist"],K:[{D:"a",W:"iv-click-target",N:{href:W.url.C()||""},K:[L0(W.Hx,{D:"div",W:"iv-card-image-overlay",K:[{D:"span",W:"iv-card-playlist-video-count",tR:W.playlistVideoCount}]}),{D:"div",W:"iv-card-content",K:[dg(W),R0("h2","iv-card-primary-link",W.title),vC(W)]}]}]};H=new g.c(H);
FF(J,g.cK("iv-click-target",H.element),W,W.url);W=H;break;case "productListing":J=J.zl;var Y=W.offers.length!=0;H=["iv-card"];D="";var p=LMF(W);Y&&(H.push("iv-card-product-listing"),D="iv-card-primary-link",p=W.offers[0],Y=[],p.price&&Y.push({D:"div",W:"iv-card-offer-price",tR:p.price}),p.merchant&&Y.push({D:"div",W:"iv-card-offer-merchant",tR:p.merchant}),p={D:"div",K:Y});Y=W.url?W.url.C()||"":"";H={D:"div",Tl:H,N:{tabindex:"0"},K:[{D:"a",Tl:["iv-card-image","iv-click-target"],N:{style:"background-image: url("+
W.imageUrl+");",href:Y,"aria-hidden":"true",tabindex:"-1"}},{D:"div",W:"iv-card-content",K:[W.sponsored?{D:"div",W:"iv-card-sponsored",K:["\u0420\u0435\u043a\u043b\u0430\u043c\u0430",{D:"div",W:"iv-ad-info-container",K:[{D:"div",W:"iv-ad-info",tR:"{{adInfo}}"},{D:"div",W:"iv-ad-info-icon-container",K:[{D:"div",W:"iv-ad-info-icon"},{D:"div",W:"iv-ad-info-callout"}]}]}]}:"",{D:"a",W:"iv-click-target",N:{href:Y},K:[R0("h2",D,W.title),p]}]}]};H=new g.c(H);D=g.ab("span");g.Sj(D,"\u042d\u0442\u043e \u043a\u043e\u043d\u0442\u0435\u043a\u0441\u0442\u043d\u0430\u044f \u0440\u0435\u043a\u043b\u0430\u043c\u0430. \u0415\u0435 \u043f\u043e\u043a\u0430\u0437 \u043c\u043e\u0436\u0435\u0442 \u043e\u043f\u043b\u0430\u0447\u0438\u0432\u0430\u0442\u044c\u0441\u044f \u043f\u0440\u043e\u0434\u0430\u0432\u0446\u043e\u043c.");
H.setContent(D,"adInfo");FF(J,g.cK("iv-click-target",H.element),W,W.url);W=H;break;case "video":J=J.zl;H=W.isLiveNow?{D:"span",Tl:["yt-badge","yt-badge-live"],tR:"\u0421\u0415\u0419\u0427\u0410\u0421 \u0412 \u041f\u0420\u042f\u041c\u041e\u041c \u042d\u0424\u0418\u0420\u0415"}:null;H={D:"div",Tl:["iv-card","iv-card-video"],K:[{D:"a",W:"iv-click-target",N:{href:W.url?.C()||""},K:[L0(W.Hx,W.videoDuration?{D:"span",W:"iv-card-video-duration",tR:W.videoDuration}:void 0),{D:"div",W:"iv-card-content",K:[dg(W),
R0("h2","iv-card-primary-link",W.title),vC(W),H]}]}]};H=new g.c(H);FF(J,g.cK("iv-click-target",H.element),W,W.url);W=H;break;default:return null}return W},JET=function(J,W){if(!g.OK(J.X.getRootNode(),"ytp-cards-teaser-shown")){if(J.C!==W){var H=g.XG(),D=J.C?J.C.Oh.R9:J.R9;
H&&D&&g.O$(H,[D]);J.C=W;o0(J)}(H=J.isInitialized&&J.Ff().style.display=="none")||(H=J.context.X.getPlayerState(),D=H===0&&J.context.X.getCurrentTime()===0,H=!(H===1||H===3||D));H||W.Oh.teaserDurationMs&&J.X.cf(!0,{teaserText:W.Oh.teaserText,durationMs:W.Oh.teaserDurationMs,onClickCommand:W.Oh.onClickCommand,vx:W.Oh.vx??null});J.Ka.isActive()||((!J.Y||!J.VY.isActive()&&J.RB)&&oZH(J,W),J.Ka.start(910+W.Oh.teaserDurationMs))}},YB9=function(J){return J.C?J.C.Oh.type==="productListing":J.X.U("enable_wn_infocards")?
!!J.cards?.length&&g.vV(J.cards,W=>W.Oh.type==="productListing"):g.vV(J.cards,W=>W.Oh.type==="productListing")},oZH=function(J,W){J.J.eo?(W=new PC([0,
J.A.scrollTop],[0,W.Oi.offsetTop],600,OBG),J.context.Y.listen(W,"animate",H=>{J.A.scrollTop=H.y}),J.context.Y.listen(W,"finish",H=>{J.A.scrollTop=H.y}),W.play()):(J.J.n9(!0),J.A.scrollTop=W.Oi.offsetTop,J.J.n9(!1))},p1=function(J){return J.C&&J.C.Oh?J.C.Oh:J.cards[0]&&J.cards[0].Oh?J.cards[0].Oh:null},ELH=function(J){var W=J.annotation.data;
"start_ms"in W&&"end_ms"in W&&J.addCueRange(Number(W.start_ms),Number(W.end_ms),J.annotation.id,()=>{J.show()},()=>{J.hide()})},QzP=function(J,W){var H=f6H(W).width;
g.ve(W,H);H=new xH(W,[H,W.offsetTop],[H-H,W.offsetTop],200,mAY);g.q(J,H);J.context.Y.listen(H,"begin",()=>{g.D8(W,!0)});
H.play()},Ek=function(J,W,H){H.stopPropagation();
wRG(J);ZUB(J,W);J.C.focus()},M6F=function(J){var W=J.annotation.data;
if(J.annotation.style==="cta")var H=6;else if(J.annotation.style==="video"||J.annotation.style==="playlist")H=7;J.L=W.collapsedelay_ms||J.L;var D=["iv-promo","iv-promo-inactive"];J.Ff().setAttribute("aria-hidden","true");J.Ff().setAttribute("aria-label","\u041f\u0440\u043e\u0434\u0432\u0438\u0436\u0435\u043d\u0438\u0435");J.Ff().tabIndex=0;var Y=J.annotation.YM(),p=W.image_url;if(p){var E=J.createElement({D:"div",Tl:["iv-promo-img","iv-click-target"]});p=J.createElement({D:"img",N:{src:p,"aria-hidden":"true"}});
E.appendChild(p);W.video_duration&&!W.is_live?(p=J.createElement({D:"span",W:"iv-promo-video-duration",tR:W.video_duration}),E.appendChild(p)):W.playlist_length&&(p=J.createElement({D:"span",W:"iv-promo-playlist-length",tR:W.playlist_length.toString()}),E.appendChild(p));Y&&BC(J,E,Y,J.annotation.id,W.session_data,void 0,H)}Y?(p=J.createElement({D:"a",W:"iv-promo-txt"}),g.iu(p,Y.C()),J.C=p):J.C=J.createElement({D:"div",W:"iv-promo-txt"});switch(J.annotation.style){case "cta":case "website":var Q=J.createElement({D:"p",
K:[{D:"strong",tR:W.text_line_1}]});var w=J.createElement({D:"p",K:[{D:"span",W:"iv-promo-link",tR:W.text_line_2}]});if(p=W.text_line_3){D.push("iv-promo-website-card-cta-redesign");var Z=J.createElement({D:"button",Tl:["iv-promo-round-expand-icon","ytp-button"]});p=J.createElement({D:"button",Tl:["iv-button","iv-promo-button"],K:[{D:"span",W:"iv-button-content",tR:p}]});var b=J.createElement({D:"div",W:"iv-promo-button-container"});b.appendChild(p);Y&&BC(J,J.Ff(),Y,J.annotation.id,W.session_data,
void 0,H)}g.jJ(J.C,"iv-click-target");Y&&BC(J,J.C,Y,J.annotation.id,W.session_data,void 0,H);break;case "playlist":case "video":Q=J.createElement({D:"p",K:[{D:"span",tR:W.text_line_1}]}),w=J.createElement({D:"p",K:[{D:"strong",tR:W.text_line_2}]}),W.is_live&&(Q=w,w=J.createElement({D:"span",Tl:["yt-badge","iv-promo-badge-live"],tR:"\u0421\u0415\u0419\u0427\u0410\u0421 \u0412 \u041f\u0420\u042f\u041c\u041e\u041c \u042d\u0424\u0418\u0420\u0415"})),g.jJ(J.C,"iv-click-target"),Y&&BC(J,J.C,Y,J.annotation.id,
W.session_data,void 0,H),D.push("iv-promo-video")}Q&&J.C.appendChild(Q);w&&J.C.appendChild(w);J.B.appendChild(J.C);b&&J.B.appendChild(b);H=J.createElement({D:"div",W:"iv-promo-actions"});J.A=J.createElement({D:"button",Tl:["iv-promo-expand","ytp-button"]});J.A.title="\u0420\u0430\u0437\u0432\u0435\u0440\u043d\u0443\u0442\u044c";J.context.C.listen(J.A,"click",K=>{Ek(J,5E3,K)});
H.appendChild(J.A);g.D8(J.A,!1);J.context.C.listen(J.Ff(),"mouseover",J.VY,J);J.context.C.listen(J.Ff(),"mouseout",J.zl,J);J.context.C.listen(J.Ff(),"touchend",K=>{Ek(J,5E3,K)});
J.Y=J.createElement({D:"button",Tl:["iv-promo-close","ytp-button"]});J.Y.title="\u0417\u0430\u043a\u0440\u044b\u0442\u044c";J.context.C.listen(J.Y,"click",J.annotation.style==="cta"&&W.text_line_3?J.qm:J.AR,J);H.appendChild(J.Y);g.UK(J.Ff(),D);E&&(g.bp(J.Ff(),E),Z&&E.appendChild(Z));g.bp(J.Ff(),J.B);g.bp(J.Ff(),H)},Qh=function(J){J.V&&(g.ke.clearTimeout(J.V),J.V=null)},wRG=function(J){J.Z.stop();
J.isCollapsed&&(g.tG(J.Ff(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),J.isCollapsed=!1,J.C&&J.C.removeAttribute("aria-hidden"),g.D8(J.A,!1),g.D8(J.Y,!0))},ZUB=function(J,W){J.V||(J.V=g.mU(function(){Qh(this);
an9(this)},W,J))},an9=function(J){J.isCollapsed||J.S||J.V||(g.jJ(J.Ff(),"iv-promo-collapsed"),J.isCollapsed=!0,J.Z.start())},pRZ=function(J,W,H){W&&(H?wb(J,W.map(D=>g.DB(D,H))):wb(J,W))},wb=function(J,W,H,D){var Y=1,p=void 0,E=-1;
if(H){let Q=!1;p=()=>{Y--;Y||Q||(clearTimeout(E),Q=!0,H())};
E=setTimeout(()=>{Q=!0;H()},1E3)}for(let Q of W||[])Y++,g.ws(Q,p);
D&&(Y++,D!==0&&J.X.sendVideoStatsEngageEvent(D,p))},ktF=function(J){return J==="annotation-editor"||J==="live-dashboard"},bUF=function(J){J.V&&(J.player.removeEventListener("videodatachange",J.V),J.V=null)},KSP=function(J){J=J.createElement({D:"div",
Tl:["annotation","annotation-type-custom"]});g.D8(J,!1);return J},MD=function(J,W){var H=!1,D=W.getElementsByTagName("annotations");
if(D&&!(D.length<1)&&(D=D[0].getAttribute("itct"))){var Y=g.XG();if(Y){var p=g.IP();p&&g.BH(g.bT)(void 0,Y,p,[g.yJ(D)])}}W=W.getElementsByTagName("annotation");for(D=0;D<W.length;D++){var E=rEY(J,W[D]);Y=null;try{a:{if(!E){Y=null;break a}var Q=E.id;p=/.+/;let e=typeof Q==="string"&&p!=null&&Q!=null&&Q.match(p)?Q:"",m=I0(E.type,fnS),u=I0(E.style,$b9),n=qQS(E.data),l=n.length!==0?JSON.parse(n):{};b:{var w=E.action;p=I69;if(w==null){var Z=null;break b}if(g.Co(w)){E=[];for(let X of w){let v=p(X);v&&E.push(v)}Z=
E;break b}let h=p(w);Z=h?[h]:[]}p=Z;Y=e&&m?new SBT(e,m,u,p,l):null}}catch(e){}if(Y)if(Y.type==="branding"||Y.type==="promotion"){p=J;E=Y;var b=KSP(p),K=null;switch(E.type){case "branding":if(p.player.G().m8)break;p.player.U("web_player_overlay_positioned_layout")?(b.setAttribute("data-overlay-order","11"),p.player.v_(b,4,!0)):p.A.element.appendChild(b);K=new gL9(b,ZR(p),E);break;case "promotion":g.mL(p.player,b,4),K=new CaF(b,ZR(p),E)}K&&K.Ca();K&&(g.q(J,K),J.L[Y.id]=K)}else if(Y.type==="card"||Y.type===
"drawer"){J.C||(J.C=eJH(J),g.q(J,J.C));if(Y.type==="card"){b=J.C;var C=(H=Y)&&H.data&&H.data.card_type;Y=H.data;if(C)switch(p=Y.tracking||{},p={e6:p.impression,click:p.click,close:p.close,yk:p.teaser_impression,y3:p.teaser_click},E=Y.tracking_params||{},K=null,C){case "collaborator":H={id:H.id,timestamp:Y.timestamp||0,type:Y.card_type,teaserText:Y.teaser_text,teaserDurationMs:Y.teaser_duration_ms,startMs:Y.start_ms,autoOpen:Y.auto_open||!1,sessionData:Y.session_data||{},sponsored:Y.sponsored||!1,
mS:p,b1:E.card?g.yJ(E.card):null,G_:E.teaser?g.yJ(E.teaser):null,R9:E.icon?g.yJ(E.icon):null,channelId:Y.channel_id,customMessage:Y.custom_message?Y.custom_message:null,profileImageUrl:Y.image_url,title:Y.title,metaInfo:Y.meta_info,url:XF({pause_on_navigation:Y.pause_on_navigation,target:Y.target||"new",value:Y.url}),onClickCommand:null};WM(b,H);break;case "playlist":H={id:H.id,timestamp:Y.timestamp||0,type:Y.card_type,teaserText:Y.teaser_text,teaserDurationMs:Y.teaser_duration_ms,startMs:Y.start_ms,
autoOpen:Y.auto_open||!1,sessionData:Y.session_data||{},sponsored:Y.sponsored||!1,mS:p,b1:E.card?g.yJ(E.card):null,G_:E.teaser?g.yJ(E.teaser):null,R9:E.icon?g.yJ(E.icon):null,Hx:Y.image_url,playlistVideoCount:Y.playlist_video_count,customMessage:Y.custom_message?Y.custom_message:null,title:Y.title,metaInfo:Y.meta_info,url:XF({pause_on_navigation:Y.pause_on_navigation,target:Y.target||"new",value:Y.url}),onClickCommand:null};WM(b,H);break;case "productListing":Y.signin_url&&(K=XF({target:"current",
value:Y.signin_url}));C=[];let e=Y.offers||[];for(let m=0;m<e.length;m++)C.push(new AE9(g.M_(e[m].merchant),g.M_(e[m].price)));H={id:H.id,timestamp:Y.timestamp||0,type:Y.card_type,teaserText:Y.teaser_text,teaserDurationMs:Y.teaser_duration_ms,startMs:Y.start_ms,autoOpen:Y.auto_open||!1,sessionData:Y.session_data||{},sponsored:Y.sponsored||!1,mS:p,b1:E.card?g.yJ(E.card):null,G_:E.teaser?g.yJ(E.teaser):null,R9:E.icon?g.yJ(E.icon):null,imageUrl:Y.image_url,displayDomain:Y.display_domain?Y.display_domain:
null,showLinkIcon:!!Y.show_link_icon,qR:Y.button_icon_url?Y.button_icon_url:null,title:Y.title,customMessage:Y.custom_message?Y.custom_message:null,url:XF({pause_on_navigation:Y.pause_on_navigation,target:Y.target||"new",value:Y.url}),EDY:K,jWv:Y.signin_title?Y.signin_title:void 0,Sca:Y.signin_message?Y.signin_message:void 0,offers:C,onClickCommand:null};WM(b,H);break;case "simple":H={id:H.id,timestamp:Y.timestamp||0,type:Y.card_type,teaserText:Y.teaser_text,teaserDurationMs:Y.teaser_duration_ms,
startMs:Y.start_ms,autoOpen:Y.auto_open||!1,sessionData:Y.session_data||{},sponsored:Y.sponsored||!1,mS:p,b1:E.card?g.yJ(E.card):null,G_:E.teaser?g.yJ(E.teaser):null,R9:E.icon?g.yJ(E.icon):null,imageUrl:Y.image_url,displayDomain:Y.display_domain?Y.display_domain:null,showLinkIcon:!!Y.show_link_icon,qR:Y.button_icon_url?Y.button_icon_url:null,title:Y.title,customMessage:Y.custom_message?Y.custom_message:null,url:XF({pause_on_navigation:Y.pause_on_navigation,target:Y.target||"new",value:Y.url}),onClickCommand:null};
WM(b,H);break;case "video":H={id:H.id,timestamp:Y.timestamp||0,type:Y.card_type,teaserText:Y.teaser_text,teaserDurationMs:Y.teaser_duration_ms,startMs:Y.start_ms,autoOpen:Y.auto_open||!1,sessionData:Y.session_data||{},sponsored:Y.sponsored||!1,mS:p,b1:E.card?g.yJ(E.card):null,G_:E.teaser?g.yJ(E.teaser):null,R9:E.icon?g.yJ(E.icon):null,Hx:Y.image_url,videoDuration:Y.video_duration||null,customMessage:Y.custom_message?Y.custom_message:null,title:Y.title,metaInfo:Y.meta_info,isLiveNow:!!Y.is_live_now,
url:XF({pause_on_navigation:Y.pause_on_navigation,target:Y.target||"new",value:Y.url}),onClickCommand:null},WM(b,H)}}else WSf(J.C,Y);H=!0}}H&&(AQ(J.player),J.J())},mbG=function(J){var W=J.player.G();
J=J.player.getVideoData();return(W.annotationsLoadPolicy||J.annotationsLoadPolicy)===1&&!J.RD||W.RB.get(J.videoId)||J.GC()||g.UY(J)?!0:!1},OUH=function(J,W){W=!W.isCued()&&!W.C(1024);
J.A.n9(W);J.Y.n9(W)},t6f=function(J,W){var H=W.videoId,D=p=>{var E=J.loadNumber;
J.B=null;J.loaded&&J.loadNumber===E&&J.player.getVideoData().videoId===H&&(p=g.Qd(p)&&p.responseXML?p.responseXML:null)&&(MD(J,p),g.jJ(J.player.getRootNode(),"iv-module-loaded"))};
g.vN()&&(D=jz9(J,D));var Y={format:"XML",onFinish:D,onError:()=>{J.B=null},
urlParams:{}};W.isPharma&&(Y.urlParams.pharma="1");Y.method="POST";Y.withCredentials=!0;(D=J.player.G().RB.get(H))&&UbY(Y,D);D=D&&D.gV;if(!W.sC||D)J.V=()=>{if(!J.qm)J.onVideoDataChange(Y);var p=J.player.getVideoData();p?.ym()&&!J.AR&&Pax(J,p)},J.player.addEventListener("videodatachange",J.V)},aU=function(J,W){var H=!1;
J.C||(J.C=eJH(J),g.q(J,J.C));for(var D of W.cards||[])D.cardRenderer&&(HUp(J.C,D.cardRenderer),H=!0);H&&(J.player.getVideoData()?.ym()||(H=J.C,D=W.headerText?g.uT(W.headerText):"",g.Sj(H.Ag,D),H.S&&H.S.setAttribute("data-tooltip-title",D),H.context.videoData.eventId&&(H.eventId=H.context.videoData.eventId),H.yY=W.trackingParams?g.yJ(W.trackingParams):null,H.B=W.closeButton.infoCardIconRenderer.trackingParams?g.yJ(W.closeButton.infoCardIconRenderer.trackingParams):null,H.R9=W.icon.infoCardIconRenderer.trackingParams?
g.yJ(W.icon.infoCardIconRenderer.trackingParams):null,J.J()),AQ(J.player))},Pax=function(J,W){if(W=W.getWatchNextResponse()?.cards?.cardCollectionRenderer)J.AR=!0,aU(J,W),W.headerText&&J.Ed&&(W=g.uT(W.headerText),J.Ed.setAttribute("data-tooltip-title",W))},jz9=function(J,W){return(...H)=>{J.e$()||J.Ca.push(g.pD.so(()=>{W(...H)}))}},UbY=function(J,W){J.method="POST";
J.postParams=J.postParams||{};W.gV&&(J.postParams.ic_coll=W.gV);W.lj&&(J.postParams.ic_track=W.lj)},rEY=function(J,W){var H={};
for(var D of W.attributes)H[D.name]=D.nodeValue;for(D=0;D<W.childNodes.length;D++){let p=W.childNodes[D];if(!g.eL(p)||p.nodeType!=1)continue;var Y=void 0;if(H[p.tagName])Y=H[p.tagName];else if(p.tagName==="data"){p.childNodes.length>0&&(Y=p.childNodes[0].nodeValue,H[p.tagName]=typeof Y==="string"?Y.trim():Y);continue}else Y=[],H[p.tagName]=Y;p&&p.tagName==="TEXT"?p.childNodes.length===1&&p.childNodes[0].nodeType===3?Y.push(p.childNodes[0].nodeValue):Y.push(""):p&&Y.push(rEY(J,p))}return H},ZR=function(J){if(!J.S){let W=
new xbS(J);
g.q(J,W);let H=new g.Lz(J);g.q(J,H);J.S=new zJT(W,H,J.player.G(),J.player.getVideoData(),J.logger,J.player,J.ue)}return J.S},V6B=function(J){var W=J.player.getVideoData();
if(W.xI){var H=J.player.G().RB.get(W.videoId);if(H){var D={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:(Y,p,E)=>{Y=J.loadNumber;p=W.videoId;J.loaded&&J.loadNumber===Y&&J.player.getVideoData().videoId===p&&(E=g.Qd(E)&&E.responseXML?E.responseXML:null)&&MD(J,E)}};
g.vN()&&(D.onFinish=jz9(J,D.onFinish));D.postParams={ic_only:"1"};UbY(D,H);J.qm=!0;g.AZ(W.xI,D)}}},eJH=function(J){var W=new g.c({D:"div"});
g.D8(W.element,!1);var H=new NIS(J.player,W.element,ZR(J));g.q(H,W);W.pa(J.A.element);H.Ca();return H},usY=function(J,W,H,D,Y){if(!J.player.G().m8){var p=[];
W.navigationEndpoint&&g.I(W.navigationEndpoint,g.b8)&&g.I(W.navigationEndpoint,g.b8).browseId&&p.push(new iBY("openUrl","click",new l6f(`/channel/${g.I(W.navigationEndpoint,g.b8).browseId}`,"new",!0,!0)));var E=W.watermark.thumbnails[0];D={channel_name:W.channelName,end_ms:W.endTimeMs,image_height:E.height,image_type:1,image_url:E.url,image_width:E.width,is_mobile:!1,session_data:{annotation_id:H,ei:Y,feature:"iv",itct:W.trackingParams,src_vid:D},start_ms:W.startTimeMs};if(W.subscribeButton&&g.I(W.subscribeButton,
g.ox)){D.channel_id=g.I(W.subscribeButton,g.ox).channelId;W=g.I(W.subscribeButton,g.ox);E=Y=null;W.subscribed?(W.subscriberCountWithUnsubscribeText&&(Y=g.uT(W.subscriberCountWithUnsubscribeText)),W.subscriberCountText&&(E=g.uT(W.subscriberCountText))):(W.subscriberCountText&&(Y=g.uT(W.subscriberCountText)),W.subscriberCountWithSubscribeText&&(E=g.uT(W.subscriberCountWithSubscribeText)));let Q=g.I(W.signInEndpoint?.commandMetadata,g.ey)?.url||"";W={subscribeText:g.uT(W.unsubscribedButtonText),subscribeCount:Y||
"",unsubscribeText:g.uT(W.subscribedButtonText),unsubscribeCount:E||"",enabled:W.enabled||!1,classic:!1,subscribed:W.subscribed||!1,feature:"iv",signInUrl:Q};D.standalone_subscribe_button_data=W}p=new SBT(H,"branding","branding",p,D);D=KSP(J);J.player.U("web_player_overlay_positioned_layout")?(D.setAttribute("data-overlay-order","11"),J.player.v_(D,4,!0)):J.A.element.appendChild(D);p=new gL9(D,ZR(J),p);p.Ca();g.q(p,p);J.L[H]=p}};
g.Kr.prototype.cf=g.De(41,function(J,W){var H=g.Ys(this.p9());H&&H.cf(J,W)});var Om={},jW=null;g.uM(PC,g.z0);g.N=PC.prototype;g.N.getDuration=function(){return this.duration};
g.N.play=function(J){if(J||this.C==0)this.progress=0,this.coords=this.A;else if(this.isPlaying())return!1;Um(this);this.startTime=J=g.xe();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.V=this.startTime;this.progress||this.U4();this.KP("play");this.isPaused()&&this.KP("resume");this.C=1;var W=g.m2(this);W in Om||(Om[W]=this);gZB();CCG(this,J);return!0};
g.N.stop=function(J){Um(this);this.C=0;J&&(this.progress=1);eyS(this,this.progress);this.onStop();this.Kp()};
g.N.pause=function(){this.isPlaying()&&(Um(this),this.C=-1,this.KP("pause"))};
g.N.Yk=function(){this.C==0||this.stop(!1);this.KP("destroy");PC.ZB.Yk.call(this)};
g.N.destroy=function(){this.dispose()};
g.N.JI=function(){this.KP("animate")};
g.N.KP=function(J){this.dispatchEvent(new AJp(J,this))};
g.uM(AJp,g.x1);g.uM(tQ,PC);tQ.prototype.Y=function(){};
tQ.prototype.JI=function(){this.Y();tQ.ZB.JI.call(this)};
tQ.prototype.Kp=function(){this.Y();tQ.ZB.Kp.call(this)};
tQ.prototype.U4=function(){this.Y();tQ.ZB.U4.call(this)};
g.uM(xH,tQ);xH.prototype.Y=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var xbS=class extends g.UQ{constructor(J){super();this.A=J||window;this.C=[]}listen(J,W,H,D){H=(0,g.Ow)(H,D||this.A);J=g.eQ(J,W,H);this.C.push(J);return J}On(J,W,H,D){H=(0,g.Ow)(H,D||this.A);J=$AZ(J,W,H);this.C.push(J);return J}Mn(J){g.Af(J);g.pZ(this.C,J)}removeAll(){g.Af(this.C);this.C.length=0}Yk(){this.removeAll();super.Yk()}};var VBS=class extends g.c{constructor(J,W,H,D,Y,p,E,Q,w,Z,b){J=J.charAt(0)+J.substring(1).toLowerCase();H=H.charAt(0)+H.substring(1).toLowerCase();if(W==="0"||W==="-1")W=null;if(D==="0"||D==="-1")D=null;var K=b.G(),C=K.userDisplayName&&g.yM(K);super({D:"div",Tl:["ytp-button","ytp-sb"],K:[{D:"div",W:"ytp-sb-subscribe",N:C?{"data-tooltip-title":g.ns("\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u0442\u044c\u0441\u044f \u043a\u0430\u043a $USER_NAME",{USER_NAME:K.userDisplayName}),"aria-label":"\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u0442\u044c\u0441\u044f \u043d\u0430 \u043a\u0430\u043d\u0430\u043b",
"data-tooltip-image":g.Qq(K),"data-tooltip-opaque":String(g.I_(K)),tabindex:"0",role:"button"}:{"aria-label":"\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u0442\u044c\u0441\u044f \u043d\u0430 \u043a\u0430\u043d\u0430\u043b"},K:[{D:"div",W:"ytp-sb-text",K:[{D:"div",W:"ytp-sb-icon"},J]},W?{D:"div",W:"ytp-sb-count",tR:W}:""]},{D:"div",W:"ytp-sb-unsubscribe",N:C?{"data-tooltip-title":g.ns("\u041f\u043e\u0434\u043f\u0438\u0441\u043a\u0430 \u043e\u0444\u043e\u0440\u043c\u043b\u0435\u043d\u0430 \u0432 \u0430\u043a\u043a\u0430\u0443\u043d\u0442\u0435 $USER_NAME",
{USER_NAME:K.userDisplayName}),"aria-label":"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0443 \u043d\u0430 \u043a\u0430\u043d\u0430\u043b","data-tooltip-image":g.Qq(K),"data-tooltip-opaque":String(g.I_(K)),tabindex:"0",role:"button"}:{"aria-label":"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0443 \u043d\u0430 \u043a\u0430\u043d\u0430\u043b"},K:[{D:"div",W:"ytp-sb-text",K:[{D:"div",W:"ytp-sb-icon"},H]},
D?{D:"div",W:"ytp-sb-count",tR:D}:""]}],N:{"aria-live":"polite"}});this.channelId=E;this.X=b;var e=this.ZU("ytp-sb-subscribe"),m=this.ZU("ytp-sb-unsubscribe");p&&g.jJ(this.element,"ytp-sb-classic");if(Y){Q?this.C():this.A();var u=()=>{if(K.yY){var l=this.channelId;if(w||Z){var h={c:l};var X;g.kg.isInitialized()&&(X=g.qh2(h));h=X||"";if(X=b.getVideoData())if(X=X.subscribeCommand){var v=b.RW();v?(g.Km(v,X,{botguardResponse:h,feature:w}),g.LQ(b,"SUBSCRIBE",l)):g.cb(Error("No innertube service available when updating subscriptions."))}else g.cb(Error("No subscribe command in videoData."));
else g.cb(Error("No video data available when updating subscription."))}m.focus();m.removeAttribute("aria-hidden");e.setAttribute("aria-hidden","true")}else g.N5(g.dx(this.X.G()),"sb_button",this.Y)},n=()=>{var l=this.channelId;
if(w||Z){var h=b.getVideoData();g.Km(b.RW(),h.unsubscribeCommand,{feature:w});g.LQ(b,"UNSUBSCRIBE",l)}e.focus();e.removeAttribute("aria-hidden");m.setAttribute("aria-hidden","true")};
this.j(e,"click",u);this.j(m,"click",n);this.j(e,"keypress",l=>{l.keyCode===13&&u(l)});
this.j(m,"keypress",l=>{l.keyCode===13&&n(l)});
this.j(b,"SUBSCRIBE",this.C);this.j(b,"UNSUBSCRIBE",this.A)}else g.jJ(e,"ytp-sb-disabled"),g.jJ(m,"ytp-sb-disabled")}Y(){window.location.reload()}C(){g.jJ(this.element,"ytp-sb-subscribed")}A(){g.P7(this.element,"ytp-sb-subscribed")}};var lnZ=class extends g.nr{constructor(J){super(J);this.V=this.endscreen=null;this.A={};this.L={};this.Z=this.Y=null;this.S=[];this.C=null;this.AR=!0;this.B=0;J=J.G();this.J=g.yM(J)||J.VY==="profilepage";this.events=new g.rC(this);g.q(this,this.events);this.events.j(this.player,g.VI("creatorendscreen"),this.onCueRangeEnter);this.events.j(this.player,g.N0("creatorendscreen"),this.onCueRangeExit);this.events.j(this.player,"resize",this.dh);this.events.j(window,"focus",this.qm);this.load();var W=g.ab("STYLE");
(g.Tn("HEAD")[0]||document.body).appendChild(W);this.addOnDisposeCallback(()=>{g.fR(W)});
W.sheet&&(W.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),W.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))}load(){super.load();if(!uI(this)){var J=g.Mz2(this.player.getVideoData());J?(J=NC(J,UAH(this)),sm(this,J,!1)):zyP(this)}}unload(){sm(this,null);this.V&&(this.V.abort(),this.V=null);super.unload()}ED(J,W){return uI(this)?J==="loadCustomEndscreenRenderer"?(J=NC(W,"new"),sm(this,J),!0):null:null}getOptions(){return uI(this)?["loadCustomEndscreenRenderer"]:[]}dh(){if(this.endscreen&&this.endscreen.elements){var J=this.player.getVideoContentRect();if(J&&J.width!==0&&J.height!==0){var W=this.player.getPlayerSize();
if(W&&W.width!==0&&W.height!==0){var H=J.width/J.height;var D=0;var Y=-1;for(var p=0;p<szY.length;p++){var E=Math.abs(W.width-szY[p]);if(Y===-1||D>=E)Y=p,D=E}D=Gt9[Y];this.Y&&g.yC(this.Y.element,"outline-width",Math.max(W.width,W.height)+"px");for(W=0;W<this.endscreen.elements.length;++W){p=this.endscreen.elements[W].id;Y=this.A[p];E=this.L[p];if(!Y||!E)continue;let w=E.width*H/E.aspectRatio;var Q=Math.round(E.width*J.width);p=Math.round(w*J.height);let Z=J.left+Math.round(E.left*J.width),b=J.top+
Math.round(E.top*J.height);g.Ws(Y.element,Q,p);g.ve(Y.element,Z,b);g.tG(Y.element,qBp);Q>256||p>256?g.jJ(Y.element,"ytp-ce-large-round"):Q>96||p>96?g.jJ(Y.element,"ytp-ce-medium-round"):g.jJ(Y.element,"ytp-ce-small-round");g.tG(Y.element,nLp);Q=E.left+E.width/2;E=E.top+w/2;g.jJ(Y.element,Q<=.5&&E<=.5?"ytp-ce-top-left-quad":Q>.5&&E<=.5?"ytp-ce-top-right-quad":Q<=.5&&E>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.tG(Y.element,Gt9);g.jJ(Y.element,D);(Y=g.on(document,"div","ytp-ce-expanding-overlay-body",
Y.element)[0])&&g.yC(Y,"height",`${p}px`)}}}}}onCueRangeEnter(J){if(this.endscreen)if(J.getId()==="ytp-ce-in-endscreen")hQ(this,this.endscreen.impressionUrls),(J=g.XG())&&this.endscreen.visualElement&&g.Ax(J,this.endscreen.visualElement),this.C&&(g.jJ(this.C,"ytp-ce-element-show"),this.C.removeAttribute("aria-hidden"),this.player.g2()?g.jJ(this.C,"ytp-ce-hide-button-lower"):g.P7(this.C,"ytp-ce-hide-button-lower"));else{J=J.getId().substring(15);var W=this.A[J],H=this.L[J];g.jJ(W.element,"ytp-ce-element-show");
W.element.removeAttribute("aria-hidden");W=this.player.getRootNode();g.jJ(W,"ytp-ce-shown");hQ(this,H.impressionUrls);(W=g.XG())&&g.Ax(W,H.visualElement);this.player.G().AR&&g.LQ(this.player,"endscreenelementshown",J)}}onCueRangeExit(J){if(J.getId()==="ytp-ce-in-endscreen")this.C&&(g.P7(this.C,"ytp-ce-element-show"),this.C.setAttribute("aria-hidden","true"));else{J=J.getId().substring(15);var W=this.A[J];g.P7(W.element,"ytp-ce-element-show");W.element.setAttribute("aria-hidden","true");W=this.player.getRootNode();
g.P7(W,"ytp-ce-shown");this.player.G().AR&&g.LQ(this.player,"endscreenelementhidden",J)}}qm(J){J.target===window&&(new g.SJ(()=>{for(let W of Object.values(this.A))g.tG(W.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()}n9(J){for(let W of Object.values(this.A))J?W.element.setAttribute("hidden",""):W.element.removeAttribute("hidden")}EQ(J){this.C&&this.player.getRootNode().removeChild(this.C);
J&&(g.jJ(J,"ytp-ce-hide-button-container"),this.C=J,g.mL(this.player,this.C,4))}},szY=[346,426,470,506,570,640,853,1280,1920],Gt9="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),nLp=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],qBp=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var l6f=class{constructor(J,W,H,D){this.value=J;this.target=W;this.showLinkIcon=H;this.A=D}C(){return this.value?this.value:null}},nZH={F5:"current",tRl:"new"};var iBY=class{constructor(J,W,H){this.type=J;this.trigger=W;this.url=H}},yJY={CLOSE:"close",RrR:"openUrl",SUBSCRIBE:"subscribe"},hyp={S_:"click",CLOSE:"close",Lv4:"hidden",uym:"rollOut",Bev:"rollOver",SJ4:"shown"};var SBT=class{constructor(J,W,H,D,Y){this.id=J;this.type=W;this.style=H;this.data=Y;this.action=D||[]}YM(){var J=XoT(this,W=>W.type==="openUrl"&&W.url!=null);
return J?J.url:null}},$b9={Pr:"anchored",eK:"branding",CHANNEL:"channel",vI:"cta",BlU:"highlightText",b9k:"label",PLAYLIST:"playlist",POPUP:"popup",Jb9:"speech",SUBSCRIBE:"subscribe",tX$:"title",VIDEO:"video",nMr:"website"},fnS={eK:"branding",lr:"card",Lf:"drawer",u4l:"highlight",S_4:"marker",Egl:"promotion",TEXT:"text",pHl:"widget"};var yET=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
hJZ=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];var iUZ=class{constructor(J,W){this.context=J;this.C=W}};var AE9=class{constructor(J,W){this.merchant=J;this.price=W}};var Inf=class extends g.UQ{constructor(J,W){super();this.element=J;this.context=W;this.JR=!1;this.W4=new Map;this.S$=new Map;this.context.X.addEventListener(g.VI("annotations_module"),H=>{(H=this.W4.get(H))&&H.apply(this)});
this.context.X.addEventListener(g.N0("annotations_module"),H=>{(H=this.S$.get(H))&&H.apply(this)})}addCueRange(J,W,H,D,Y){J=new g.ha(J,W,{id:H,
namespace:"annotations_module"});D&&this.W4.set(J,D);Y&&this.S$.set(J,Y);this.context.X.yR([J],1)}Ca(){this.context.A.subscribe("resize",this.DU,this)}Ff(){return this.element}Mm(J,W,H,D,Y,p){if(this.JR)return!1;p&&(p.stopPropagation(),p.preventDefault());this.navigate(J,H,D,Y);return!1}show(){}hide(){}destroy(){g.fR(this.Ff())}DU(){}navigate(J,W,H,D){var Y=J.C();if(Y){var p=dAH(Y,J.target),E=()=>{J.A&&this.context.X.pauseVideo();var Q=this.context.videoData.vZ||!1,w=g.W$(Y||"");Q&&w&&(w.v||w.list)?
this.context.X.g_(w.v,W,w.list,!1):g.Oy(Y||"",p==="current"?"_top":void 0,W)};
p==="new"&&(E(),E=null);wb(this.context.logger,H,E,D);Ryp(Y)||(H=g.XG(),D=W.itct,H&&D&&g.jK(H,g.yJ(D)))}}Yk(){this.W4.clear();this.S$.clear();super.Yk()}createElement(J){J=new g.c(J);g.q(this,J);return J.element}};var NIS=class extends Inf{constructor(J,W,H){super(W,H);this.X=J;this.eventId=null;this.YQ=this.RB=this.yq=this.Y=this.isInitialized=!1;this.cards=[];this.Ig=this.S=this.b9=this.Z=this.aB=this.C=null;this.AR=[];this.qm=this.B=this.R9=this.yY=null;this.L=0;this.VY=new g.SJ(()=>{},H.O.G9?4E3:3E3);
g.q(this,this.VY);this.Ka=new g.SJ(()=>{});
g.q(this,this.Ka);this.zl=new iUZ(H,(D,Y,p,E,Q,w)=>{BC(this,D,Y,p,E,Q,w)});
this.J=new g.c({D:"div",W:"iv-drawer",N:{id:"iv-drawer"},K:[{D:"div",W:"iv-drawer-header",N:{"aria-role":"heading"},K:[{D:"span",W:"iv-drawer-header-text"},{D:"button",Tl:["iv-drawer-close-button","ytp-button"],N:{"aria-label":"\u0421\u043a\u0440\u044b\u0442\u044c \u043f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0438",tabindex:"0"}}]},{D:"div",W:"iv-drawer-content"}]});g.q(this,this.J);this.V=this.J.element;this.fa=new g.qY(this.J,330);g.q(this,this.fa);this.Ag=g.Jd("iv-drawer-header-text",this.V);
this.A=g.Jd("iv-drawer-content",this.V);this.addCueRange(0,H.videoData.lengthSeconds*1E3,"",()=>{this.yq&&Jn(this,"YOUTUBE_DRAWER_AUTO_OPEN")},()=>{(this.yq=this.Y)&&HM(this)});
this.B4=new g.rC(this);g.q(this,this.B4);this.X.addEventListener("videodatachange",this.z0.bind(this))}z0(){this.qm&&WM(this,this.qm)}isAvailable(){var J;if(J=!!this.cards.length)(J=this.X.getRootNode())?(J=g.Hs(J),J=173<J.width&&173<J.height):J=!1;return J}DU(){var J=this.isAvailable();g.D8(this.Ff(),J);g.xb(this.context.X.getRootNode(),g.mK.IV_DRAWER_ENABLED,J);AQ(this.X)}destroy(){this.X.cf(!1);try{this.X.getRootNode().removeChild(this.V)}catch(J){}g.mn(this.AR);this.B4.A();this.aB&&this.aB.dispose();
this.Z&&this.Z.dispose();super.destroy()}Lb(){this.context.C.listen(g.Jd("iv-drawer-close-button",this.V),"click",this.Bi,this);this.context.C.listen(this.A,"touchend",()=>{this.VY.start()});
this.context.C.listen(this.A,"scroll",this.rP,this);this.context.A.subscribe("onHideControls",()=>{this.RB=!0});
this.context.A.subscribe("onShowControls",()=>{this.RB=!1});
this.context.A.subscribe("onVideoAreaChange",()=>{this.RB=g.OK(this.X.getRootNode(),"ytp-autohide")});
this.AR.push(g.AM("iv-button-shown",this.f9,this));this.AR.push(g.AM("iv-button-hidden",this.ag,this));T0F(this)}findLastIndex(J){if(this.cards.length===0)return 0;var W=g.Jp(this.cards,H=>J.Oh.startMs>H.Oh.startMs||J.Oh.startMs===H.Oh.startMs&&J.Oh.timestamp>=H.Oh.timestamp?!0:!1);
return W===-1?0:W+1}Bi(){if(this.Y){wb(this.context.logger,p1(this).mS.close);var J=g.XG();J&&this.B&&g.jK(J,this.B);HM(this)}}rP(){g.xb(this.V,"iv-drawer-scrolled",this.A.scrollTop>0)}f9(){var J=g.XG(),W=p1(this);W=W?W.R9:this.R9;J&&W&&g.mo(J,[W])}ag(){var J=g.XG(),W=p1(this);W=W?W.R9:this.R9;J&&W&&g.O$(J,[W])}E_(){var J=p1(this);wb(this.context.logger,J.mS.yk);var W=g.XG();if(W&&J){let H=[];J.G_&&H.push(J.G_);J.R9&&H.push(J.R9);H.length>0&&g.mo(W,H)}}Ce(){var J=g.XG(),W=p1(this);J&&W&&g.O$(J,[W.G_])}kQ(J){var W=
p1(this),H=g.XG();this.C?J?(J=this.context.logger,wb(J,W.mS.y3),J.X.sendVideoStatsEngageEvent(4,void 0),H&&W.G_&&g.jK(H,W.G_)):(J=this.context.logger,wb(J,W.mS.y3),J.X.sendVideoStatsEngageEvent(4,void 0),H&&W.R9&&g.jK(H,W.R9)):(J=this.context.logger,wb(J,W.mS.y3),J.X.sendVideoStatsEngageEvent(4,void 0),H&&this.R9&&g.jK(H,this.R9))}};var XRY=class extends Inf{constructor(J,W,H){super(J,W);this.annotation=H;this.isActive=!1}Ca(){super.Ca();ELH(this)}show(){super.show();var J=g.XG(),W=this.annotation.data;J&&W&&(W=W.session_data)&&g.mo(J,[g.yJ(W.itct)])}hide(){super.hide();var J=g.XG(),W=this.annotation.data;J&&W&&(W=W.session_data)&&g.O$(J,[g.yJ(W.itct)])}};var gL9=class extends XRY{constructor(J,W,H){super(J,W,H);this.C=null;this.A=!1}show(){if(!this.isActive){super.show();if(!this.A){g.jJ(this.Ff(),"iv-branding");let J=this.annotation.data;this.C=this.createElement({D:"img",Tl:["branding-img","iv-click-target"],N:{"aria-label":"\u041b\u043e\u0433\u043e\u0442\u0438\u043f \u043a\u0430\u043d\u0430\u043b\u0430",src:J.image_url,width:J.image_width,height:J.image_height}});g.D8(this.C,!1);let W=this.createElement({D:"button",Tl:["branding-img-container",
"ytp-button"]});W.appendChild(this.C);this.Ff().appendChild(W);let H=this.annotation.YM();H&&BC(this,W,H,this.annotation.id,J.session_data);this.A=!0}g.D8(this.Ff(),!0);this.isActive=!0;if(this.C){try{QzP(this,this.C)}catch{}g.jJ(this.context.X.getRootNode(),"ytp-branding-shown");this.context.X.getRootNode().style.setProperty("--branding-image-width",`${this.C.getAttribute("width")}px`)}}}hide(){this.isActive&&(super.hide(),g.D8(this.Ff(),!1),this.isActive=!1,g.P7(this.context.X.getRootNode(),"ytp-branding-shown"))}destroy(){g.P7(this.context.X.getRootNode(),
"ytp-branding-shown");super.destroy()}};var zJT=class{constructor(J,W,H,D,Y,p,E){this.C=J;this.Y=W;this.O=H;this.videoData=D;this.logger=Y;this.X=p;this.A=E}};var CaF=class extends XRY{constructor(J,W,H){super(J,W,H);this.S=this.isCollapsed=this.J=!1;this.L=5E3;this.A=this.Y=this.C=this.V=null;this.B=this.createElement({D:"div",Tl:["iv-promo-contents"]});this.Z=new g.SJ(()=>{this.C.setAttribute("aria-hidden","true");g.D8(this.Y,!1);g.D8(this.A,!0)},700,this);
g.q(this,this.Z)}show(){this.isActive||(super.show(),this.J||(M6F(this),this.J=!0),g.D8(this.Ff(),!0),g.mU(function(){g.P7(this.Ff(),"iv-promo-inactive")},100,this),this.Ff().removeAttribute("aria-hidden"),this.isActive=!0,Qh(this),wRG(this),ZUB(this,this.L))}hide(){this.isActive&&(g.jJ(this.Ff(),"iv-promo-inactive"),this.isActive=!1,this.Ff().setAttribute("aria-hidden","true"))}Mm(J,W,H,D,Y,p){return this.isCollapsed?!1:super.Mm(J,W,H,D,Y,p)}VY(J){this.S=!0;
Ek(this,500,J)}zl(){this.S=!1;an9(this)}AR(J){J.stopPropagation();this.hide()}qm(J){J.stopPropagation();Qh(this);this.isCollapsed=!0;g.jJ(this.Ff(),"iv-promo-collapsed-no-delay");this.Z.start()}destroy(){this.Z.dispose();super.destroy()}};var LSP=class{constructor(J){this.X=J}};g.cx("annotations_module",class extends g.nr{constructor(J){super(J);this.AR=this.qm=!1;this.loadNumber=0;this.L={};this.logger=new LSP(this.player);this.Z=new g.rC(this);this.B=this.V=null;this.events=new g.rC(this);this.Ed=this.S=this.C=null;this.Ca=[];g.q(this,this.Z);this.Z.j(this.player,"onVideoAreaChange",()=>{this.publish("onVideoAreaChange")});
this.Z.j(this.player,"onHideControls",()=>{this.publish("onHideControls")});
this.Z.j(this.player,"onShowControls",()=>{this.publish("onShowControls")});
this.Z.j(this.player,"resize",H=>{this.publish("resize",H)});
this.Z.j(this.player,"presentingplayerstatechange",H=>{this.publish("presentingplayerstatechange",H)});
this.subscribe("presentingplayerstatechange",this.VY,this);this.subscribe("resize",this.J,this);this.player.G().RB.subscribe("vast_info_card_add",this.zl,this);g.q(this,this.events);this.DU=this.createElement({D:"div",W:"video-custom-annotations"});this.A=new g.c({D:"div",Tl:["ytp-player-content","ytp-iv-player-content"]});g.q(this,this.A);g.mL(this.player,this.A.element,4);this.A.hide();this.Y=new g.c({D:"div",Tl:["ytp-iv-video-content"]});g.q(this,this.Y);J=this.createElement({D:"div",W:"video-annotations"});
J.appendChild(this.DU);this.Y.element.appendChild(J);this.lB()?this.load():this.player.U("web_fix_annotations")&&(this.V=()=>{this.loaded||this.e$()||!this.lB()||(bUF(this),this.load())},this.player.addEventListener("videodatachange",this.V));
var W=this.createElement({D:"style"});(g.Tn("HEAD")[0]||document.body).appendChild(W);this.addOnDisposeCallback(()=>{g.fR(W)});
if(J=W.sheet){for(let H of yET)J.insertRule(H,0);for(let H of hJZ)J.insertRule(H,0)}}ED(J,W){if(!ktF(this.player.G().playerStyle))return null;switch(J){case "loadCustomAnnotationsXml":return(J=g.XE(W))&&MD(this,J),!0;case "removeCustomAnnotationById":return W&&this.C&&(cC(this.C,W),AQ(this.player)),!0}return null}getOptions(){return ktF(this.player.G().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]}lB(){var J=this.player.getVideoData(),W=J.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer;
return J.vZ||this.player.isMutedByEmbedsMutedAutoplay()?!1:this.player.U("web_fix_annotations")?mbG(this)?W?.isWatermarkEnforced===!0?!0:W?.isAnnotationsEnabled??!1:!1:mbG(this)}J(){if(this.Y){var J=this.player.dP().getVideoContentRect(!0);g.Ws(this.Y.element,J.width,J.height);g.ve(this.Y.element,J.left,J.top)}if(this.C){var W=this.player.ma();J=this.C;W=W.width;g.xb(J.V,"iv-drawer-small",W<=426);g.xb(J.V,"iv-drawer-big",W>=1280)}}VY(J){OUH(this,J.state);J.state.C(2)&&(this.g2()&&this.eI()&&this.player.getPresentingPlayerType()!==
2&&this.Pf(!1),this.cf(!1))}load(){super.load();OUH(this,this.player.getPlayerStateObject());this.loadNumber++;var J=this.player.getVideoData();t6f(this,J);g.mL(this.player,this.Y.element,4);this.J();var W=g.UY(J),H=J.GC();if(this.player.U("web_fix_annotations")){if(W&&(W.featuredChannel&&usY(this,W.featuredChannel,W.annotationId||"branding",J.videoId||null,J.eventId||null),W=this.player.getVideoData().getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer,W?.isWatermarkEnforced&&!W?.isAnnotationsEnabled))return;
H&&aU(this,H)}else H&&aU(this,H),W&&W.featuredChannel&&usY(this,W.featuredChannel,W.annotationId||"branding",J.videoId||null,J.eventId||null);this.Ed=g.Jd("ytp-cards-button",this.player.getRootNode());J.ym()&&Pax(this,J)}onVideoDataChange(){}unload(){this.player.lx("annotations_module");for(let J of Object.keys(this.L))this.L[J].destroy();this.S=null;this.C&&(this.C.destroy(),this.C=null,AQ(this.player));this.qm=!1;this.B&&(this.B.abort(),this.B=null);this.AR=!1;this.L={};this.A.hide();super.unload();
this.Y.detach();bUF(this)}zl(J){J===this.player.getVideoData().videoId&&(this.loaded?V6B(this):this.load())}g2(){return this.C?.isAvailable()||this.AR}eI(){return!!this.C&&this.C.Y}Pf(J,W=!1,H){this.g2();this.C&&(J?H?Jn(this.C,H,W):Jn(this.C,"YOUTUBE_DRAWER_AUTO_OPEN",W):HM(this.C))}cf(J,W){this.player.publish(J?"cardsteasershow":"cardsteaserhide",W)}Yk(){this.player.G().RB.unsubscribe("vast_info_card_add",this.zl,this);g.P7(this.player.getRootNode(),g.mK.IV_DRAWER_OPEN);var J=this.Ca,W=g.pD;for(let H=
0,D=J.length;H<D;H++)W.hQ(J[H]);this.Ca.length=0;super.Yk()}createElement(J){J=new g.c(J);g.q(this,J);return J.element}});g.cx("creatorendscreen",lnZ);})(_yt_player);
