(function(g){var window=this;'use strict';var dbY=async function(J,W,H){J.A=g.AZ(W,H)},k3=function(J){J.isActive()||J.start()},vLY=function(J,W){var H=new g.P8;
H.languageCode=J.languageCode;H.languageName=J.languageName;H.name=J.name;H.displayName=J.displayName;H.kind=J.kind;H.isDefault=!1;H.C=J.C;H.isTranslateable=J.isTranslateable;H.vssId=J.vssId;H.url=J.url;H.translationLanguage=W;J.xtags&&(H.xtags=J.xtags);J.captionId&&(H.captionId=J.captionId);return H},bi=function(J,W){return W?J.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},FST=function(J){return g.o_(J)||J.U("web_enable_caption_language_preference_stickiness")},BIS=async function(J,W){J=
J+"|"+W;
W=await g.sa();if(!W)throw g.ZD("gct");return(await g.zr(W)).get("captions",J)},TIH=function(J,W,H){BIS(J,W).then(D=>{D&&H(D.trackData,new g.P8(D.metadata))})},K1=function(J){if(!cEB.test(J))throw Error("'"+J+"' is not a valid hex color");
J.length==4&&(J=J.replace(oLf,"#$1$1$2$2$3$3"));J=J.toLowerCase();J=parseInt(J.slice(1),16);return[J>>16,J>>8&255,J&255]},JHB=function(){var J={},W="suggest_correction"in g.A0?g.A0.suggest_correction:"Edit caption";
W=W||"";for(let H in J){let D=()=>String(J[H]);
W=W.replace(new RegExp("\\$\\{"+H+"\\}","gi"),D);W=W.replace(new RegExp("\\$"+H,"gi"),D)}return W},rb=function(){return g.x$("yt-player-caption-display-settings")},WrH=function(J,W){var H=g.$T(J.segments,W);
H>=0||H<0&&(-H-1)%2===1||(H=-H-1,H>0&&W-J.segments[H-1]===1&&H<J.segments.length&&J.segments[H]-W===1?(g.DP(J.segments,H),g.DP(J.segments,H-1)):H>0&&W-J.segments[H-1]===1?J.segments[H-1]=W:H<J.segments.length&&J.segments[H]-W===1?J.segments[H]=W:(g.KZ(J.segments,H,0,W),g.KZ(J.segments,H+1,0,W)))},H5x=function(J){return J.C&&J.C.Z?J.C.Z+J.player.s_()<J.player.getCurrentTime():!1},DV9=function(J,W){if(J.policy.Nf&&J.player.zx()){var H=g.kw(W,J.policy,{});
H.set("pot",J.player.zx());H=H.YM()}else H=g.kw(W,J.policy,{}).YM();var D={format:"RAW",withCredentials:!0};if(J.policy.yY){D.method="POST";let E=W.V;E&&Object.keys(E).length>0?D.postBody=g.AB(E,g.hr):D.postBody=(0,g.Pm)([120,0])}J.Z&&(D.responseType="arraybuffer");var Y=++J.Ca,p=(0,g.d)();J.A=g.Uj(H,D,3,100,-1,E=>{E.errorCode==="net.timeout"&&J.player.wl("capnt",{rn:Y++})}).then(E=>{if(J.policy.Hy&&Y%100===1){var Q=(0,g.d)();
J.player.wl("caprsp",{rn:Y,ms:Q-p,kb:(E.xhr.responseText.length/1024).toFixed()})}a:{E=E.xhr;J.e$();if(J.Y){var w=!(J.Z?E.response:E.responseText)||E.status>=400;if(Q=g.iLM(E)){E=g.kw(J.Y,J.policy,{});J.Y.VZ(E,Q);DV9(J,J.Y);break a}w?J.player.wl("capfail",{status:E.status}):(g.dy("fcb_r",(0,g.d)(),J.player.getVideoData()?.Nu||""),Q=J.Y.gP[0],w=Q.La,J.S!=null&&J.L!==w&&(J.Z?J.S(E.response,(Q.segmentStartTime+J.player.s_())*1E3):J.S(E.responseText,(Q.segmentStartTime+J.player.s_())*1E3),J.L=w))}J.Y=
null;J.A=null}}).JE(E=>{J.Y=null;
J.A=null;J.player.wl("capfail",{rn:Y,status:E.xhr?.status})});
J.Y=W;WrH(J.V,J.Y.gP[0].La)},YJT=function(J,W){return W!=null&&W in J.A.C?J.A.C[W]:null},pIT=function(J,W,H){var D=[];
for(let Y in J.A.C){if(!J.A.C.hasOwnProperty(Y))continue;let p=J.A.C[Y];if(g.WJ(p,H||null)){let E=p.info.captionTrack;E&&E.languageCode===W&&D.push(p)}}return D.length?D[0]:null},E1S=function(J,W){var H=[];
for(let Y in J.A.C){if(!J.A.C.hasOwnProperty(Y))continue;var D=J.A.C[Y];if(g.WJ(D,W||null)){let p=D.info.id,E=p,Q=`.${p}`,w="",Z="";if(D=D.info.captionTrack)p=D.languageCode,E=D.displayName,Q=D.vssId,w=D.kind,Z=D.id;H.push(new g.P8({id:Y,languageCode:p,languageName:E,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:Q,kind:w,captionId:Z}))}}return H},QC9=function(J,W,H,D){var Y=W/360*16;
W>=J&&(J=640,D>H*1.3&&(J=480),Y=H/J*16);return Y},wIP=function(J){var W=1+.25*(J.fontSizeIncrement||0);
if(J.offset===0||J.offset===2)W*=.8;return W},Z5f=function(J,W){var H="vertical-rl";
J.C.fW===1&&(H="vertical-lr");g.uz&&(H=H==="vertical-lr"?"tb-lr":"tb-rl");g.yC(W,"-o-writing-mode",H);g.yC(W,"-webkit-writing-mode",H);g.yC(W,"writing-mode",H);g.yC(W,"text-orientation","upright");g.jJ(W,"ytp-vertical-caption");J.A.params.TO===3&&(g.yC(W,"text-orientation",""),g.yC(W,"transform","rotate(180deg)"))},Muf=function(J,W){var H={},D=W.background?W.background:J.C.eX.background;
if(W.backgroundOpacity!=null||W.background){var Y=W.backgroundOpacity!=null?W.backgroundOpacity:J.C.eX.backgroundOpacity;D=K1(D);H.background="rgba("+D[0]+","+D[1]+","+D[2]+","+Y+")";J.aB&&(H["box-decoration-break"]="clone",H["border-radius"]=`${J.W4*.25}px`)}if(W.fontSizeIncrement!=null||W.offset!=null)H["font-size"]=`${J.S$*wIP(W)}px`;J.experiments.Er("enable_player_captions_new_style_defaults")&&(H["line-height"]="1.375");D=1;Y=W.color||J.C.eX.color;if(W.color||W.textOpacity!=null)Y=K1(Y),D=W.textOpacity==
null?J.C.eX.textOpacity:W.textOpacity,Y="rgba("+Y[0]+","+Y[1]+","+Y[2]+","+D+")",H.color=Y,H.fill=Y;var p=W.charEdgeStyle;p===0&&(p=void 0);if(p){Y=`rgba(34, 34, 34, ${D})`;let w=`rgba(204, 204, 204, ${D})`;W.Il&&(w=Y=W.Il);let Z=J.S$/16/2,b=Math.max(Z,1);var E=Math.max(2*Z,1),Q=Math.max(3*Z,1);let K=Math.max(5*Z,1);D=[];switch(p){case 4:for(;Q<=K;Q+=Z)D.push(`${E}px ${E}px ${Q}px ${Y}`);break;case 1:E=window.devicePixelRatio>=2?.5:1;for(p=b;p<=Q;p+=E)D.push(`${p}px ${p}px ${Y}`);break;case 2:D.push(`${b}px ${b}px ${w}`);
D.push(`-${b}px -${b}px ${Y}`);break;case 3:for(Q=0;Q<5;Q++)D.push(`0 0 ${E}px ${Y}`)}H["text-shadow"]=D.join(", ")}Y="";switch(W.fontFamily){case 1:Y=J.HC?'"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", serif-monospace, monospace':'"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:Y='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:Y=J.HC?'"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", sans-serif-monospace, monospace':
'"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:Y='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:Y='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:Y=g.XD()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:Y='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}Y&&(H["font-family"]=Y);Y=W.offset;Y==
null&&(Y=J.C.eX.offset);switch(Y){case 0:H["vertical-align"]="sub";break;case 2:H["vertical-align"]="super"}W.fontFamily===7&&(H["font-variant"]="small-caps");W.bold&&(H["font-weight"]="bold");W.italic&&(H["font-style"]="italic");W.underline&&(H["text-decoration"]="underline");W.J7&&(H.visibility="hidden");W.DZ===1&&J.V&&(H["text-combine-upright"]="all",H["text-orientation"]="mixed",Y=g.p7||g.Ea,J.A.params.TO===3?H.transform=Y?"rotate(90deg)":"rotate(180deg)":Y&&(H.transform="rotate(-90deg)"));if(W.textEmphasis===
1||W.textEmphasis===2||W.textEmphasis===3||W.textEmphasis===4||W.textEmphasis===5)if(g.p7)H["font-weight"]="bold";else switch(H["text-emphasis-style"]="filled circle",H["text-emphasis-color"]="currentcolor",H["webkit-text-emphasis"]="filled circle",W.textEmphasis){case 4:case 3:H["text-emphasis-position"]="under left";H["webkit-text-emphasis-position"]="under left";break;case 5:case 2:H["text-emphasis-position"]="over right",H["webkit-text-emphasis-position"]="over right"}return H},afZ=function(J,
W){if(J.fa&&W.length===0)return 0;
J=1;for(let H=0;H<W.length;H++){let D=W[H];typeof D.text==="string"&&(J+=D.text.split("\n").length-1,D.append||H===0||J++)}return J},f1=function(J){J=J.split("px");
return J.length>0?(J=Number(J[0]))?J:0:0},KrT=function(J,W,H){J.yY=J.yY||!!H;
var D={};Object.assign(D,J.C.eX);Object.assign(D,H||W.C);Object.assign(D,J.BC.eX);(H=!J.Z)&&kmS(J);var Y=J.b9&&J.RB&&g.Rf(D,J.RB)?J.b9:b5Z(J,D),p=typeof W.text==="string",E=p?W.text.split("\n"):[W.text];for(let w=0;w<E.length;w++){var Q=w>0||!W.append;let Z=E[w];Q&&!H?(kmS(J),Y=b5Z(J,D)):Q&&H&&(H=!1);Z&&(Y.appendChild(p?g.kA(Z):Z),p||Z.tagName!=="RUBY"||Z.childElementCount!==4||g.p7||!g.X7(Z.children[2],"text-emphasis")||(Q=J.V?"padding-right":"padding-top",g.X7(Z.children[2],"text-emphasis-position")&&
(Q=J.V?"padding-left":"padding-bottom"),g.Ep?g.yC(Y,Q,"1em"):g.yC(Y,Q,"0.5em")))}J.RB=D;J.b9=Y;J.B.push(W)},kmS=function(J){if(J.Z){var W=J.Z;
if(J.aB){var H=J.C.textAlign;H===0?(W=W.firstElementChild)&&g.yC(W,{"border-bottom-left-radius":"0"}):H===1&&(W=W.lastElementChild)&&g.yC(W,{"border-bottom-right-radius":"0"})}}J.Z=g.ab("SPAN");g.yC(J.Z,{display:"block"});g.jJ(J.Z,"caption-visual-line");J.Y.appendChild(J.Z)},b5Z=function(J,W){var H=g.ab("SPAN");
g.yC(H,{display:"inline-block","white-space":"pre-wrap"});g.yC(H,Muf(J,W));H.classList.add("ytp-caption-segment");J.Z.appendChild(H);J.aB&&J.Y.children.length>1&&(J=J.C.textAlign,J===0?H.previousElementSibling||g.yC(H,{"border-top-left-radius":"0"}):J===1&&g.yC(H,{"border-top-right-radius":"0"}));H.previousElementSibling&&(g.yC(H.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.yC(H,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return H},
ffF=function(J,W,H){if(J===255&&W===255||!J&&!W)return{zf:J,
IX:W,result:0};J=rHp[J];W=rHp[W];if(J&128){var D;if(D=!(W&128))D=W,D=H.UJ()&&H.IX===D;if(D)return{zf:J,IX:W,result:1}}else if(W&128&&1<=J&&J<=31)return{zf:J,IX:W,result:2};return{zf:J,IX:W,result:3}},SJ9=function(J,W,H,D){W===255&&H===255||!W&&!H?(++J.Y===45&&J.reset(),J.V.A.clear(),J.Z.A.clear()):(J.Y=0,$VG(J.V,W,H,D))},g1P=function(J,W){J.C.sort((H,D)=>{var Y=H.time-D.time;
return Y===0?H.order-D.order:Y});
for(let H of J.C)J.time=H.time,H.type===0?SJ9(J,H.sP,H.Ml,W):H.type===1&&J.A&496&&$VG(J.Z,H.sP,H.Ml,W);J.C.length=0},O5Z=function(J,W){switch(J){case 0:return CBY[(W&127)-32];
case 1:return eVF[W&15];case 2:return AHY[W&31];case 3:return mVY[W&31]}return 0},$3=function(J,W){if(J.style.type===3){var H=0,D=0,Y=J.Z.time+0,p="",E="",Q=Y;
for(var w=1;w<=15;++w){var Z=!1;for(var b=D?D:1;b<=32;++b){var K=J.Y[w][b];if(K.C!==0){H===0&&(H=w,D=b);Z=String.fromCharCode(K.C);var C=K.timestamp;C<Y&&(Y=C);K.timestamp=Q;E&&(p+=E,E="");p+=Z;Z=!0}if((K.C===0||b===32)&&Z){E="\n";break}else if(D&&!Z)break}if(H&&!Z)break}p&&W.V(H,D,Y,Q,p)}else for(D=H=0,p=Y=J.Z.time+0,E=1;E<=15;++E)for(Q="",w=1;w<=32;++w)if(b=J.Y[E][w],K=b.C,K!==0&&(H===0&&(H=E,D=w),Z=String.fromCharCode(K),C=b.timestamp,C<=Y&&(Y=C),Q+=Z,b.reset()),w===32||K===0)Q&&W.V(H,D,Y,p,Q),
Y=p,Q="",D=H=0},S$=function(J){return J.Y[J.row][J.A]},gb=function(J,W,H){W>=2&&J.A>1&&(--J.A,S$(J).C=0);
var D=S$(J);D.timestamp=J.Z.time+0;D.C=O5Z(W,H);J.A<32&&J.A++},jCH=function(J,W,H,D){for(let E=0;E<D;E++)for(let Q=0;Q<=32;Q++){var Y=J.Y[W+E][Q],p=J.Y[H+E][Q];
Y.C=p.C;Y.timestamp=p.timestamp}},C1=function(J,W,H){for(let D=0;D<H;D++)for(let Y=0;Y<=32;Y++)J.Y[W+D][Y].reset()},e$=function(J){J.row=J.C>0?J.C:1;
J.A=1;C1(J,0,15)},UVf=function(J){J.style.set(1);
J.C=J.V;J.C.C=0;J.C.style=J.style;J.Y.mode=1<<J.C.V},An=function(J,W,H){var D=J.A,Y=!1;
switch(J.style.get()){case 4:case 1:case 2:J.style.get()===4&&D.C>0||($3(D,H),e$(J.A),e$(J.V),D.row=15,D.C=W,Y=!0)}J.style.set(3);J.C=D;J.C.style=J.style;J.Y.mode=1<<D.V;Y?D.A=1:D.C!==W&&(D.C>W?($3(D,H),C1(D,D.row-D.C,W)):D.row<W&&(W=D.C),D.C=W)},PBY=function(J){J.style.set(4);
J.C=J.text;J.C.style=J.style;J.Y.mode=1<<J.C.V},$VG=function(J,W,H,D){J.A.update();
W=ffF(W,H,J.A);switch(W.result){case 0:return;case 1:case 2:return}var Y=W.zf;W=W.IX;if(32<=Y||!Y)J.C.mode&J.C.A&&(H=Y,H&128&&(H=127),W&128&&(W=127),J=J.V.C,H&96&&gb(J,0,H),W&96&&gb(J,0,W),H!==0&&W!==0&&J.style.type===3&&$3(J,D));else if(Y&16)a:if(!J.A.matches(Y,W)&&(H=J.A,H.zf=Y,H.IX=W,H.state=2,H=Y&8?J.L:J.Y,J.V=H,J.C.mode=1<<(J.Z<<2)+(H.Z<<1)+(H.style.type===4?1:0),(J.C.mode|1<<(J.Z<<2)+(H.Z<<1)+(H.style.type!==4?1:0))&J.C.A))if(W&64){D=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(Y&7)<<1|W>>5&1];
J=W&16?((W&14)>>1)*4:0;W=H.C;switch(H.style.get()){case 4:D=W.row;break;case 3:if(D!==W.row){if(D<W.C&&(D=W.C,D===W.row))break;var p=1+W.row-W.C;let E=1+D-W.C;jCH(W,E,p,W.C);H=p;Y=W.C;E<p?(p=E+Y-p,p>0&&(H+=p,Y-=p)):(p=p+Y-E,p>0&&(Y-=p));C1(W,H,Y)}}W.row=D;W.A=J+1}else switch(Y&7){case 1:switch(W&112){case 32:gb(H.C,0,32);break a;case 48:W===57?(D=H.C,S$(D).C=0,D.A<32&&D.A++):gb(H.C,1,W&15)}break;case 2:W&32&&gb(H.C,2,W&31);break;case 3:W&32&&gb(H.C,3,W&31);break;case 4:case 5:if(32<=W&&W<=47)switch(W){case 32:UVf(H);
break;case 33:D=H.C;D.A>1&&(--D.A,S$(D).C=0);break;case 36:D=H.C;J=S$(D);for(W=0;W<=15;W++)for(H=0;H<=32;H++)if(D.Y[W][H]===J){for(;H<=32;H++)D.Y[W][H].reset();break}break;case 37:An(H,2,D);break;case 38:An(H,3,D);break;case 39:An(H,4,D);break;case 40:gb(H.C,0,32);break;case 41:D=H;D.style.set(2);D.C=D.A;D.C.C=0;D.C.style=D.style;D.Y.mode=1<<D.C.V;break;case 42:D=H;J=D.text;J.C=15;J.style.set(4);e$(J);PBY(D);break;case 43:PBY(H);break;case 44:J=H;W=J.A;switch(J.style.get()){case 1:case 2:case 3:$3(W,
D)}C1(W,0,15);break;case 45:b:{W=H;J=W.C;switch(W.style.get()){default:case 2:case 1:break b;case 4:if(J.row<15){++J.row;J.A=1;break b}break;case 3:}J.C<2&&(J.C=2,J.row<J.C&&(J.row=J.C));W=J.row-J.C+1;$3(J,D);jCH(J,W,W+1,J.C-1);C1(J,J.row,1)}break;case 46:C1(H.V,0,15);break;case 47:J=H,$3(J.A,D),J.V.updateTime(J.Y.time+0),D=J.V,J.V=J.A,J.A=D,UVf(J)}break;case 7:switch(W){case 33:case 34:case 35:D=H.C,(D.A+=W&3)>32&&(D.A=32)}}},xVp=function(J,W,H,D,Y,p,E){var Q=p[0],w=E[Q.getAttribute("p")];
if(w.Qm===1){var Z=p[1],b=p[2];p=p[3];Q.getAttribute("t");Z.getAttribute("t");b.getAttribute("t");p.getAttribute("t");Q.getAttribute("p");Z.getAttribute("p");p.getAttribute("p");E=E[b.getAttribute("p")];Q=tuP(Q.textContent,Z.textContent,b.textContent,p.textContent,E);return new m4(J,W,Y,H,Q,D,w)}switch(w.Qm){case 9:case 10:w.textEmphasis=1;break;case 11:w.textEmphasis=2;break;case 12:w.textEmphasis=3;break;case 13:w.textEmphasis=4;break;case 14:w.textEmphasis=5}return new m4(J,W,Y,H,Q.textContent||
"",D,w)},tuP=function(J,W,H,D,Y){var p=g.XD(),E=p?g.ab("DIV"):g.ab("RUBY"),Q=g.ab("SPAN");
Q.textContent=J;E.appendChild(Q);J=p?g.ab("DIV"):g.ab("RP");J.textContent=W;E.appendChild(J);W=p?g.ab("DIV"):g.ab("RT");W.textContent=H;E.appendChild(W);H=Y.Qm;if(H===10||H===11||H===12||H===13||H===14)if(g.yC(W,"text-emphasis-style","filled circle"),g.yC(W,"text-emphasis-color","currentcolor"),g.yC(W,"webkit-text-emphasis","filled circle"),Y.Qm===11||Y.Qm===13)g.yC(W,"webkit-text-emphasis-position","under left"),g.yC(W,"text-emphasis-position","under left");H=!0;if(Y.Qm===4||Y.Qm===7||Y.Qm===12||
Y.Qm===14)g.yC(E,"ruby-position","over"),g.yC(E,"-webkit-ruby-position","before");else if(Y.Qm===5||Y.Qm===6||Y.Qm===11||Y.Qm===13)g.yC(E,"ruby-position","under"),g.yC(E,"-webkit-ruby-position","after"),H=!1;Y=p?g.ab("DIV"):g.ab("RP");Y.textContent=D;E.appendChild(Y);p&&(D=H,g.yC(E,{display:"inline-block",position:"relative"}),p=E.firstElementChild.nextElementSibling,g.yC(p,"display","none"),p=p.nextElementSibling,g.yC(p,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.yC(E.lastElementChild,"display","none"),D?(g.yC(E,"padding-top","0.6em"),g.yC(p,"top","0")):(g.yC(E,"padding-bottom","0.6em"),g.yC(p,"bottom","0")));return E},zV9=function(J){var W="_"+Ok++;
return new j$(0,0x8000000000000,0,W,J)},Uk=function(J,W){J=J.getAttribute(W);
if(J!=null)return Number(J)},PM=function(J,W){J=J.getAttribute(W);
if(J!=null)return J==="1"},tn=function(J,W){J=Uk(J,W);
return J!==void 0?J:null},zq=function(J,W){J=J.getAttribute(W);
if(J!=null)return x3.test(J),J},VuT=function(J,W){var H={},D=W.getAttribute("ws");
Object.assign(H,D?J.J[D]:J.V);J=tn(W,"mh");J!=null&&(H.S8=J);J=tn(W,"ju");J!=null&&(H.textAlign=J);J=tn(W,"pd");J!=null&&(H.TO=J);J=tn(W,"sd");J!=null&&(H.fW=J);J=zq(W,"wfc");J!=null&&(H.windowColor=J);W=Uk(W,"wfo");W!==void 0&&(H.windowOpacity=W/255);return H},NMF=function(J,W){var H={},D=W.getAttribute("wp");
D&&Object.assign(H,J.S[D]);J=tn(W,"ap");J!=null&&(H.KQ=J);J=Uk(W,"cc");J!=null&&(H.q3=J);J=Uk(W,"ah");J!=null&&(H.aW=J);J=Uk(W,"rc");J!=null&&(H.cJ=J);W=Uk(W,"av");W!=null&&(H.aH=W);return H},uiS=function(J,W,H,D){var Y={};
Object.assign(Y,NMF(J,W));Object.assign(Y,VuT(J,W));D?g.Rf(Y,J.V)?(D=J.Z,Y=J.V):D="_"+Ok++:D=W.getAttribute("id")||"_"+Ok++;J=Uk(W,"t")+H;W=Uk(W,"d")||0x8000000000000;if(Y.TO===2||Y.TO===3)H=Y.cJ,Y.cJ=Y.q3,Y.q3=H;return new j$(J,W,0,D,Y)},Vh=function(J){J=g.t3(Math.round(J),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-J.length)+J},sCH=function(J,W,H,D,Y){D===0&&(D=0x8000000000000);
var p={};W.wpWinPosId&&Object.assign(p,J.V.get(W.wpWinPosId));W.wsWinStyleId&&Object.assign(p,J.Z.get(W.wsWinStyleId));J=W.rcRowCount;J!==void 0&&(p.cJ=J);W=W.ccColCount;W!==void 0&&(p.q3=W);if(p.TO===2||p.TO===3)W=p.cJ,p.cJ=p.q3,p.q3=W;return new j$(H,D,0,Y,p)},ND=function(J){var W=J.byteOffset;
J.byteOffset+=1;return J.C.getUint8(W)},ui=function(J){var W=J.byteOffset;
J.byteOffset+=4;return J.C.getUint32(W)},n19=function(J){if(typeof J==="string")return!1;
J=new GmS(J,0);return qJT(J)},qJT=function(J){if(!(J.byteOffset<J.C.byteLength)||ui(J)!==1380139777)return!1;
J.version=ND(J);if(J.version>1)return!1;ND(J);ND(J);ND(J);return!0},lfT=function(J,W){if(!W)return"";
J.V&&J.A.params.fW!==1&&(W*=-1);return`translate${J.V?"X":"Y"}(${W}px)`},yHB=function(J){J.VY=Array.from(J.element.getElementsByClassName("caption-visual-line"));
for(var W=J.A.params.cJ,H=0,D=0,Y=J.VY.length-1;H<W&&Y>-1;){var p=J.VY[Y];D+=J.V?p.offsetWidth:p.offsetHeight;H++;Y--}J.qm=D;W=Math;H=W.max;isNaN(J.DU)&&((D=J.C.q3)?(Y=g.ab("SPAN"),g.Sj(Y,"\u2013".repeat(D)),g.yC(Y,Muf(J,J.C.eX)),J.Y.appendChild(Y),J.DU=Y.offsetWidth,J.Y.removeChild(Y)):J.DU=0);D=J.Y;J.Ca=H.call(W,J.DU,J.Bi,(J.V?D.offsetHeight:D.offsetWidth)+1)},hVf=function(J,W){yHB(J);
var H=J.VY.reduce((D,Y)=>(J.V?Y.offsetWidth:Y.offsetHeight)+D,0);
H=J.qm-H;if(H!==J.B4){let D=H>0&&J.B4===0,Y=H<J.B4;W||isNaN(H)||D||!Y||(g.jJ(J.element,"ytp-rollup-mode"),J.j(J.element,"transitionend",J.Ka));g.yC(J.Y,"transform",lfT(J,H));J.B4=H}yHB(J)},IfF=function(J,W,H,D){var {formatId:Y,
La:p,startTimeMs:E,durationMs:Q}=J.w3(W),w={formatId:Y,startTimeMs:E,durationMs:Q,GV:p,hX:p},Z=i5H(J.jo,w.startTimeMs),b=Z>=0?J.jo[Z]:null,K=b?b.startTimeMs+b.durationMs:0,C=w.startTimeMs+w.durationMs;!b||w.startTimeMs-K>J.V?J.jo.splice(Z+1,0,w):(b.durationMs=Math.max(K,C)-b.startTimeMs,b.hX=Math.max(b.hX,w.hX));D(J.jo);D=g.g5(W);J=J.Z;D=D.buffer.slice(D.byteOffset,D.byteLength+D.byteOffset);W=W.info.V;J.Ca?J.S==null?g.Fx(J.logger,350058965,"Null loaded track meta data at captions data received"):
H.yF(D,J.S,W*1E3):g.Fx(J.logger,350058965,"Null Representation at captions data received")},RVY=function(J,W){J.A=(H,D)=>{if(J.X.G().experiments.Er("html5_sabr_live_support_subfragmented_captions"))(J.C?J.C=J.C.Z(H):(J.C=H,XI9(J.C)),J.C)?H.info.RL&&(LrP(J.C),IfF(J,J.C,W,D),J.C=null):g.Fx(J.logger,350058965,"Empty slice");
else if(H.info.RL){var Y=H;if(J.pP.length>0){for(Y=J.pP.shift();J.pP.length>0;)Y=Y?.Z(J.pP.shift());Y=Y?.Z(H)}Y?(XI9(Y),LrP(Y),IfF(J,Y,W,D)):g.Fx(J.logger,350058965,"Empty slice")}else J.pP.push(H)};
J.X.addEventListener("sabrCaptionsDataLoaded",J.A)},i5H=function(J,W){J=g.$T(J,{startTimeMs:W},(H,D)=>H.startTimeMs-D.startTimeMs);
return J>=0?J:-J-2},XI9=function(J){try{var W=g.AR(J)*1E3}catch(H){W=J.info.segmentStartTime*1E3}W<0&&(W=J.info.segmentStartTime*1E3);
J.info.segmentStartTime=W/1E3;J.info.V=W/1E3},LrP=function(J){try{var W=g.Nye(J)*1E3}catch(H){W=J.info.Y*1E3}W<0&&(W=J.info.Y*1E3);
J.info.Y=W/1E3;J.info.B=W/1E3},dVY=function(J,W){if(!g.kYt(J)||J.C!=null&&g.JV(W,J.C)&&J.C.C.rawcc!=null)return!1;
W=!!J.C&&J.C.isManifestless&&Object.values(J.C.C).some(H=>g.WJ(H,"386"));
J=!!J.C&&!J.C.isManifestless&&g.Qlw(J.C);return W||J},v1Y=function(J,W,H){var D=[];
for(let Y in J.A.C){if(!J.A.C.hasOwnProperty(Y))continue;let p=J.A.C[Y];if(g.WJ(p,H||null)){let E=p.info.captionTrack;E&&E.languageCode===W&&D.push(p)}}return D.length?D[0]:null},FrG=function(J,W){var H=[];
for(let Y in J.A.C){if(!J.A.C.hasOwnProperty(Y))continue;var D=J.A.C[Y];if(g.WJ(D,W||null)){let p=D.info.id,E=p,Q=`.${p}`,w="",Z="";if(D=D.info.captionTrack)p=D.languageCode,E=D.displayName,Q=D.vssId,w=D.kind,Z=D.id;H.push(new g.P8({id:Y,languageCode:p,languageName:E,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:Q,kind:w,captionId:Z}))}}return H},TMf=function(J){var W=BM9.length;
if(J.byteLength<W)return!1;J=new Uint8Array(J,0,W);for(let H=0;H<W;H++)if(BM9[H]!==J[H])return!1;return!0},sk=function(J){J=J.split(":");
var W=0;for(let H of J)W=W*60+Number(H);return W*1E3},cHS=function(J,W,H,D){D=Object.assign({S8:0},D);
return new j$(J,W,H,"_"+Ok++,D)},o1S=function(J,W,H,D,Y,p,E,Q,w){switch(E.tagName){case "b":Q.bold=!0;
break;case "i":Q.italic=!0;break;case "u":Q.underline=!0}for(let b=0;b<E.childNodes.length;b++){var Z=E.childNodes[b];if(Z.nodeType===3)Z=new m4(W,H,D,Y.id,Z.nodeValue,p||b>0,g.yS(Q)?void 0:Q),w.push(Z),Y.C.push(Z);else{let K={};Object.assign(K,Q);o1S(J,W,H,D,Y,!0,Z,K,w)}}},WU9=function(J,W,H){if(typeof W==="string"||n19(W))return[{trackData:W,
vn:H}];if(typeof W==="string"&&W.substring(0,6)==="WEBVTT"||typeof W!=="string"&&TMf(W))return[{trackData:W,vn:H}];var D=new DataView(W);if(D.byteLength<=8||D.getUint32(4)!==1718909296)return[];var Y=g.huw(D);if(J.G5&&Y){var p=g.ko(Y),E=g.bF(Y);Y=Y.segmentNumber;p&&Y&&J.G5.T8(Y,p,E)}J=g.OO(D,1835295092);if(!J||!J.length||!J[0].size)return[];p=[];for(E=0;E<J.length;E++)Y=J[E],Y=new Uint8Array(W,Y.dataOffset,Y.size-(Y.dataOffset-Y.offset)),Y=g.pt(Y),p.push({trackData:Y,vn:H+E*1E3});JKS(D,p,H);return p=
p.filter(Q=>!!Q.trackData)},Dmf=function(J,W,H){J.C||(J.C=new HAZ);
J=J.C.Y(W,H);Math.random()<.01&&g.Jx(Error("Deprecated subtitles format in web player: WebVTT"));return J},JKS=function(J,W,H){var D=g.gh(J,0,1836476516),Y=9E4;
D&&(Y=g.CX(D)||9E4);D=0;var p=g.OO(J,1836019558);for(let Q=0;Q<p.length;Q++){var E=p[Q];Q<W.length&&(E=g.gh(J,E.dataOffset,1953653094))&&(E=g.gh(J,E.dataOffset,1952867444))&&(E=g.mI(E)/Y*1E3,Q===0&&(D=E),W[Q].vn=E-D+H||H*Q*1E3)}},YlF=function(J){var W={};
if(J=g.V8(J))W.lang=J,g.wFV.test(J)&&(W.TO=1);return W},Gq=function(J){return J.Y==="HLS"&&J.Ag?!0:J.b9&&J.Ag&&J.Y!=="LIVE"&&J.Y!=="SABR_LIVE"},prF=function(J){return!J.V&&J.b9&&J.fa&&(J.Y==="LIVE"||J.Y==="SABR_LIVE")},qD=function(J,W,H=!1){var D=J.O.U("enable_player_captions_new_style_defaults")?Exp:QIY,Y=D.eX;
J.Z={};Object.assign(J.Z,D);J.Z.eX={};Object.assign(J.Z.eX,Y);J.L={eX:{}};var p=W.backgroundOverride?J.L:J.Z,E=W.background||Y.background;x3.test(E);p.eX.background=E;p=W.colorOverride?J.L:J.Z;E=W.color||Y.color;x3.test(E);p.eX.color=E;p=W.windowColorOverride?J.L:J.Z;E=W.windowColor||D.windowColor;x3.test(E);p.windowColor=E;p=W.backgroundOpacityOverride?J.L:J.Z;E=W.backgroundOpacity;E==null&&(E=Y.backgroundOpacity);p.eX.backgroundOpacity=E;p=W.fontSizeIncrementOverride?J.L:J.Z;E=W.fontSizeIncrement;
E==null&&(E=Y.fontSizeIncrement);p.eX.fontSizeIncrement=E;E=W.fontStyleOverride?J.L:J.Z;p=W.fontStyle;p==null&&(p=Y.bold&&Y.italic?3:Y.bold?1:Y.italic?2:0);E=E.eX;switch(p){case 1:E.bold=!0;delete E.italic;break;case 2:delete E.bold;E.italic=!0;break;case 3:E.bold=!0;E.italic=!0;break;default:delete E.bold,delete E.italic}p=W.textOpacityOverride?J.L:J.Z;E=W.textOpacity;E==null&&(E=Y.textOpacity);p.eX.textOpacity=E;p=W.windowOpacityOverride?J.L:J.Z;E=W.windowOpacity;E==null&&(E=D.windowOpacity);p.windowOpacity=
E;D=W.charEdgeStyleOverride?J.L:J.Z;p=W.charEdgeStyle;p==null&&(p=Y.charEdgeStyle);D.eX.charEdgeStyle=p;D=W.fontFamilyOverride?J.L:J.Z;p=W.fontFamily;p==null&&(p=Y.fontFamily);D.eX.fontFamily=p;J.loaded&&J.Ig();H&&g.tf("yt-player-caption-display-settings",W,2592E3)},n1=function(J,W,H){W&&!J.AR?(W=zV9({TO:0,
lang:"ru"}),J.AR=[W,new m4(W.start,W.end-W.start,0,W.id,H??"\u0421\u0443\u0431\u0442\u0438\u0442\u0440\u044b \u0431\u0443\u0434\u0443\u0442 \u0432\u044b\u0433\u043b\u044f\u0434\u0435\u0442\u044c \u0442\u0430\u043a")],J.player.yR(J.AR)):!W&&J.AR&&(wrY(J,J.AR),J.AR=null)},MnH=function(J){if(J.O.U("enable_player_captions_persistence_state_machine")){var W=g.x$("yt-player-caption-persistence");
if(W==null){let H=g.G8().u9(65);if(H===!0)W=!1;else{let D=g.o_(J.O)?li(J):ZAH(J);D!=null?W=!!D:H===!1&&(W=!0)}W!==void 0&&yh(J,W)}return W}},li=function(J){if(!J.X.isInline())return g.x$("yt-player-sticky-caption")},ZAH=function(J){if(!J.storage)return null;
try{var W=J.storage.get("module-enabled")}catch(H){J.storage.remove("module-enabled")}return W},hn=function(J){if(J.O.U("enable_player_captions_persistence_state_machine"))return MnH(J);
var W=void 0,H=g.G8().u9(65);if(g.o_(J.O)&&H!=null){if(li(J)!=null)return!1;W=!H}return W},aXf=function(J){if(J.O.Mt===1||J.videoData.Sf===1||g.CQ(J.videoData,"yt:cc")==="alwayson")return!0;
if(J.videoData.captionTracks.length)var W=J.getAudioTrack().A;if(J.O.U("enable_player_captions_persistence_state_machine")){var H=MnH(J);if(H!==void 0)return!!H}else if(J.O.Mt===2&&(g.o_(J.O)?H=li(J):H=ZAH(J),H!=null))return!!H;H=bi(J.player.getAudioTrack(),g.o_(J.O));var D=g.CQ(J.videoData,"yt:cc");if(hn(J)===void 0){if(H==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return D?D==="on":!0;if(H==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return D==="on"}else return D==="on";return W==="ON"||g.CQ(J.videoData,
"yt:cc")==="on"},ii=function(J,W=!1){if(J.A&&!W||!J.videoData.captionTracks.length)return!1;
J=J.getAudioTrack();return!!J.C||J.A==="FORCED_ON"},kvG=function(J,W){if(J.A){var H=J.X.WC().Ff().textTracks,D=null;
J.Y==="HLS"?D=J.A.getId():D=J.A.toString();for(let p=0;p<H.length;p++){var Y=H[p];Y.id===D&&(W?Y.mode!=="showing"&&(Y.mode="showing",Y=J.A,J.YY(Y,!!Y,IU(J)?"g":J.B?"m":"s")):Y.mode==="showing"&&(Y.mode="disabled"))}}},IU=function(J){var W=XM(J);
return!!W&&J.A===W},bAf=function(J,W){if(J.Y==="HLS")return!1;
g.x7(J.videoData)&&(W=!0);W||(W=J.Y==="TTS"?!1:J.Y==="INNERTUBE"?!1:!0);return W||J.O.U("web_watch_disable_account_level_captions_settings")&&g.o_(J.O)?!0:!!g.G8().u9(66)},XM=function(J){return J.J&&J.J.C},L1=function(J,W){if(!J.C)return null;
if(J.J&&J.J.V)return J.J.V;W=bAf(J,W);W=g.NN(J.C.C,W);var H=null;if(FST(J.O)){var D=J.X.isInline()?void 0:g.x$("yt-player-caption-sticky-language");var Y=[D,J.videoData.captionsLanguagePreference,J.O.captionsLanguagePreference,g.CQ(J.videoData,"yt:cc_default_lang")];let Q=!1;for(let w=0;w<Y.length;w++){let Z=Y[w];if(Z){Q=!0;for(var p=0;p<W.length;p++)if(g.V8(W[p])===Z)return W[p];for(p=0;p<W.length;p++)if(g.V8(W[p]).split("-")[0]===Z.split("-")[0])return W[p]}}if(Q&&J.C&&(Y=J.C.J,Y.length))for(var E of Y)if(E.languageCode===
D){H=E;break}}else for(E=[J.videoData.captionsLanguagePreference,J.O.captionsLanguagePreference,g.CQ(J.videoData,"yt:cc_default_lang")],D=0;D<E.length;D++)for(Y=0;Y<W.length;Y++)if(g.V8(W[Y])===E[D])return W[Y];E=null;J.J&&J.J.Y&&(E=J.J.Y);E||(E=W.find(Q=>Q.isDefault)||null);
E||(E=W[0]||XM(J));E&&H&&g.V8(E).split("-")[0]!==H.languageCode.split("-")[0]&&(E=vLY(E,H));return E},FM=function(J,W,H){J.loaded&&J.unload();
H!=null&&(J.B=H,J.B&&(J.O.U("enable_player_captions_persistence_state_machine")?yh(J,!!W):g.o_(J.O)?RU(J,!!W):db(J,!!W)));W!==null||ii(J,!0)||J.YY(W,!!W,J.B?"m":"s");J.A=W;ii(J)&&(J.A=XM(J));vM(J,J.A??void 0);J.load()},yh=function(J,W){J.O.U("enable_player_captions_persistence_state_machine")&&g.tf("yt-player-caption-persistence",W,3122064E3)},RU=function(J,W){J.X.isInline()||g.tf("yt-player-sticky-caption",W,2592E3)},db=function(J,W){if(J.storage)try{J.storage.set("module-enabled",W)}catch(H){}},
vM=function(J,W){J.O.U("html5_modify_caption_vss_logging")&&(J.videoData.jn=W)},rKB=function(J,W){var H=J.zl[W.id];
H&&H.A!==W&&(H.dispose(),delete J.zl[W.id],H=null);H||(H=KUf(J,W))&&(J.zl[W.id]=H)},fXT=function(J,W){var H=W.windowId;
J.aB[H]||(J.aB[H]=[]);J.aB[H].push(W)},KUf=function(J,W){var H=$mP(J);
if(!H)return null;var D=J.A?g.V8(J.A):null;D&&g.wFV.test(D)&&(W.params.TO=1);var Y=J.Ka.getPlayerSize();D=Y.height*J.Ca.height;Y=Y.width*J.Ca.width;J.O.playerStyle!=="google-live"||J.Z.isDefault||Object.assign(W.params,J.Z);switch(W.params.S8!=null?W.params.S8:W.C.length>1?1:0){case 1:return new SlG(W,J.Z,J.L,H.width,H.height,Y,D,J.O.experiments,J.W4.bind(J),J.X);case 2:return new gxZ(W,J.Z,J.L,H.width,H.height,Y,D,J.O.experiments,J.W4.bind(J),J.X);default:return new BM(W,J.Z,J.L,H.width,H.height,
Y,D,J.O.experiments,J.W4.bind(J),J.X)}},$mP=function(J){var W=J.Ka.getVideoContentRect(!0).height,H=J.Ka.getVideoContentRect(!0).width;
if(!W||!H)return null;W*=J.Ca.height;H*=J.Ca.width;return{width:H,height:W}},wrY=function(J,W){J.player.Ro(W);
for(let H of W)g.pZ(J.DU,H);k3(J.yY)},CGT=function(J,W){if(!J.C)return{};
if(W){g.yS(W)||J.BR(W.vss_id,"m");if(J.V&&J.Y!=="HLS"||!g.eL(W))return;if(g.yS(W)){FM(J,null,!0);return}let D;var H=g.NN(J.C.C,!0);for(let Y=0;Y<H.length;Y++){let p=H[Y];p.languageCode!==W.languageCode||D&&(p.languageName!==W.languageName||(p.captionId||"")!==(W.captionId||"")||g.xg(p)!==W.displayName)||(D=W.translationLanguage?vLY(p,W.translationLanguage):p)}J.RV(W.position);!D||D===J.A&&J.loaded||(W=g.ek(),H=g.V8(D),W.length&&H===W[W.length-1]||(W.push(H),g.tf("yt-player-caption-language-preferences",
W)),FST(J.O)&&!J.X.isInline()&&g.tf("yt-player-caption-sticky-language",H,2592E3),FM(J,D,!0))}else return J.loaded&&J.A&&!IU(J)?g.zy(J.A):{};return""};
g.JQ.prototype.T8=g.De(67,function(J,W,H){this.A.set(J,{pz:W,hO:H})});
g.WC.prototype.T8=g.De(66,function(J,W,H){this.Ca.T8(J,W,H)});
g.lE.prototype.qm=g.De(65,function(){return!1});
g.lE.prototype.V=g.De(64,function(){});
g.yL.prototype.V=g.De(63,function(J,W,H){this.e$();W=this.L(J,W);var D=this.Ur.G().U("html5_report_captions_ctmp_qoe"),Y=(0,g.d)();this.Y();dbY(this,W,{format:"RAW",onSuccess:p=>{this.A=null;if(D){var E=(p.responseText.length/1024).toFixed();let Q=(0,g.d)();this.videoData.wl("capresp",{ms:Q-Y,kb:E})}E=p.getResponseHeader&&p.getResponseHeader("Content-Length")?Number(p.getResponseHeader("Content-Length")):0;H.yF(p.responseText,J,void 0,void 0,E)},
onError:D?p=>{this.videoData.wl("capfail",{status:p?.status??0})}:void 0,
withCredentials:!0})});
g.hq.prototype.V=g.De(62,function(J,W,H){this.e$();W=this.L(J,W);this.Y();this.A=g.AZ(W,{format:"RAW",onSuccess:D=>{this.A=null;var Y=D.getResponseHeader&&D.getResponseHeader("Content-Length")?Number(D.getResponseHeader("Content-Length")):0;H.yF(D.responseText,J,void 0,void 0,Y)},
withCredentials:!0})});
g.KJ.prototype.B=g.De(61,function(){this.mediaElement.B()});
g.Mn.prototype.B=g.De(60,function(){var J=g.on(document,"track",void 0,this.C);for(let W=0;W<J.length;W++)g.fR(J[W])});
g.KJ.prototype.B4=g.De(59,function(){return this.mediaElement.B4()});
g.Mn.prototype.B4=g.De(58,function(){return!(!this.C.textTracks||!this.C.textTracks.addEventListener)});
g.KJ.prototype.RB=g.De(57,function(){return this.mediaElement.RB()});
g.Mn.prototype.RB=g.De(56,function(){return!!this.C.textTracks});
g.KJ.prototype.AR=g.De(55,function(J){this.mediaElement.AR(J)});
g.Mn.prototype.AR=g.De(54,function(J){for(let W=0;W<J.length;W++)this.C.appendChild(J[W])});
g.Kr.prototype.BR=g.De(40,function(J,W){this.app.hR().BR(J,W)});
g.q1.prototype.BR=g.De(39,function(J,W){this.IB.BR(J,W)});
g.zU.prototype.BR=g.De(38,function(J,W){J=[J,W];g.pq(this,g.wo(this.provider),"cfi",J)});
g.Nk.prototype.BR=g.De(37,function(J,W){this.qoe&&this.qoe.BR(J,W)});
g.Ig.prototype.BR=g.De(36,function(J,W){this.hg.BR(J,W)});
g.Bp.prototype.BR=g.De(35,function(){});
g.Go.prototype.BR=g.De(34,function(J,W){g.kX(this,37,[J,W])});
g.Kr.prototype.YY=g.De(33,function(J,W,H){this.app.hR().YY(J,W,H)});
g.q1.prototype.YY=g.De(32,function(J,W,H){this.IB.YY(J,W,H)});
g.zU.prototype.YY=g.De(31,function(J,W,H){if(this.b9!==J||this.Ag!==W)W=W==="rawcc"?"":W,H=[J,W,this.b9,H],g.pq(this,g.wo(this.provider),"cfs",H),this.b9=J,this.Ag=W});
g.Nk.prototype.YY=g.De(30,function(J,W,H){this.qoe&&this.qoe.YY(J,W,H)});
g.Ig.prototype.YY=g.De(29,function(J,W,H){this.hg.YY(J,W,H)});
g.Bp.prototype.YY=g.De(28,function(){});
g.Go.prototype.YY=g.De(27,function(J,W,H){g.kX(this,36,[J,W,H])});
g.Jq.prototype.yr=g.De(9,function(J){return(J=this.Y(J))?J.C:0});
g.D3.prototype.yr=g.De(8,function(){return 0});
var oLf=/#(.)(.)(.)/,cEB=/^#(?:[0-9a-f]{3}){1,2}$/i,ezF={en:"English"},AKB=class extends g.lE{constructor(J){super(J);this.A=new Set}Z(J){var W=this.Ur.WC();if(W&&W.Ff()){W=W.Ff().textTracks;for(let H of W)H.kind==="subtitles"&&!this.A.has(H.language)&&H.language&&(g.o6(this.C,new g.P8({languageCode:H.language,languageName:H.language,kind:H.kind,id:H.id,displayName:ezF[H.label]||H.label,vss_id:`.${H.language}`})),this.A.add(H.language))}g.NN(this.C).length>0&&J.ud()}},mmF=class{constructor(){this.segments=
[]}contains(J){J=g.$T(this.segments,J);return J>=0||J<0&&(-J-1)%2===1}length(){return this.segments.length/2}},OAS=class extends g.UQ{constructor(J,W,H,D,Y,p){super();this.policy=J;this.player=W;this.F4=H;this.S=D;this.Z=Y;this.qm=p;this.V=new mmF;this.L=-1;this.A=this.Y=this.C=null;this.Ca=0;this.B=new g.SJ(this.AR,1E3,this);this.events=new g.rC(this);g.q(this,this.B);g.q(this,this.events);this.events.j(W,"SEEK_COMPLETE",this.J);this.J();this.AR()}Yk(){super.Yk();this.A&&this.A.cancel()}J(){this.seekTo(this.player.getCurrentTime())}seekTo(J){J-=
this.player.s_();var W=this.C;this.C=g.h2(this.F4.B(J).gP);W!==this.C&&this.qm&&this.qm()}reset(){this.V=new mmF;this.L=-1;this.A&&(this.A.cancel(),this.A=null)}AR(){this.e$();var J;if(J=this.C!=null)J=this.C,J=J.F4.V(J);if(J&&!this.A&&!(this.C&&this.C.segmentStartTime-this.player.getCurrentTime()>30)){J=this.C;J=J.F4.b9(J);let Y=J.gP[0];if(this.player.getVideoData()?.enableServerStitchedDai){var W=this.player.LI();if(W){var H=Y.F4.info.id;let p=Y.La;var D=J.gP[0].V;if(this.policy.yY){if(W=g.xq2(W,
D,p,H,3))J.V=W}else if(H=W.A9(D,p,H,3))if(D=2,W.nP.has(p)?D=0:g.GN(W,p)&&(D=1),W=D,W===0)H&&(J.C=new g.Bv(H));else if(W===2){this.B.start();H5x(this)&&this.seekTo(this.player.getCurrentTime());return}}}Y.F4.index.m3(Y.La)?(this.V.contains(J.gP[0].La)||DV9(this,J),this.C=g.h2(J.gP)):H5x(this)&&this.seekTo(this.player.getCurrentTime())}this.B.start()}},jIS=class extends g.lE{constructor(J,W){super(W);this.A=J;this.X=W;this.S=null;this.AR=!1;this.logger=new g.vv("caps");this.Ca=g.JV(this.X,this.A)}V(J,
W,H){this.Y();W=YJT(this,J.getId());W||(W=J.languageCode,W=this.A.isManifestless?pIT(this,W,"386"):pIT(this,W));if(W){var D=(W.index.yr(W.index.IF())-W.index.getStartTime(W.index.IF()))*1E3,Y=new g.$Nt(this.X.G());this.S=new OAS(Y,this.X,W,(p,E)=>{H.yF(p,J,E,D)},this.Ca||g.Zm(W.info),()=>{this.S&&this.S.reset();
this.AR=!0})}}qm(){var J=this.AR;
this.AR=!1;return J}Z(J){var W=this.X.G().U("html5_fallback_if_rawcc_missing");var H=this.A.C.rawcc!=null;if(!this.Ca||!H&&W)W=this.A.isManifestless?E1S(this,"386"):E1S(this);else{if(!H){g.Fx(this.logger,386248249,"rawcc used but unavailable");return}W=[new g.P8({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.P8({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(let D of W)g.o6(this.C,
D);J.ud()}Y(){this.S&&(this.S.dispose(),this.S=null)}L(){return""}},x3=/^#(?:[0-9a-f]{3}){1,2}$/i;var Umx=["left","right","center","justify"];var m4=class extends g.ha{constructor(J,W,H,D,Y,p=!1,E=null){super(J,J+W,{priority:H,namespace:"captions"});this.windowId=D;this.text=Y;this.append=p;this.C=E}toString(){return super.toString()}};var BM=class extends g.c{constructor(J,W,H,D,Y,p,E,Q,w,Z){var b=Z.isInline()&&!0,K={};Object.assign(K,W);Object.assign(K,J.params);Object.assign(K,H);var C={};Object.assign(C,W.eX);J.params.eX&&Object.assign(C,J.params.eX);Object.assign(C,H.eX);b&&(K.windowOpacity=.6,C.backgroundOpacity=0);K.eX=C;var e=K.TO===1,m=[{D:"span",W:"captions-text",N:{style:"word-wrap: normal; display: block;"}}],u=Q.Er("caption_edit_on_hover")&&Z.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
u&&m.unshift({D:"button",W:"caption-edit",N:{tabindex:"0","aria-label":JHB()},K:[{D:"svg",N:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},K:[{D:"path",N:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({D:"div",W:"caption-window",N:{id:`caption-window-${J.id}`,dir:e?"rtl":"ltr",tabindex:"0",lang:K.lang},K:m});this.experiments=
Q;this.B=[];this.yY=!1;this.A=J;this.RB=this.b9=null;this.Cr=p;this.Tz=E;this.Z=null;this.maxWidth=p*.96;this.maxHeight=E*.96;this.C=K;this.BC=H;this.zl=W;this.Y=this.ZU("captions-text");J=this.Y.style;this.aB=Q.Er("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in J||"WebkitBoxDecorationBreak"in J);this.HC=Q.Er("web_player_misc_bugfix_b");this.S$=QC9(D,Y,p,E);this.ue=w;u&&(this.L=this.ZU("caption-edit"),this.j(this.L,"click",()=>{this.ue()}));
this.type=0;this.W4=this.S$*wIP(C);this.yq=b;this.fa=Q.Er("enable_centered_caption_for_tvfilm_video")&&Z.getVideoData().isTvfilmVideo;this.J=Z.G().QY().C.u9(g.l2t);D=new g.Gz(this.element,!0);g.q(this,D);D.subscribe("dragstart",this.m8,this);D.subscribe("dragmove",this.Ea,this);D.subscribe("dragend",this.Ua,this);this.Ig=this.JR=this.YQ=this.Ag=0;D="";this.C.windowOpacity&&(D=K1(this.C.windowColor),D="rgba("+D[0]+","+D[1]+","+D[2]+","+this.C.windowOpacity+")");Y={"background-color":D,display:this.C.isVisible===
!1?"none":"","text-align":Umx[this.C.textAlign]};this.aB&&(Y["border-radius"]=D?`${this.W4*.25}px`:"");(this.V=this.A.params.TO===2||this.A.params.TO===3)&&Z5f(this,this.element);g.yC(this.element,Y);b&&this.element.parentElement?.style.setProperty("--caption-window-color",D);switch(this.C.KQ){case 0:case 1:case 2:g.jJ(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.jJ(this.element,"ytp-caption-window-bottom")}}m8(J,W){this.JR=J;this.Ig=W;var H=g.Jo(this.element,this.element.parentElement);
this.Ag=J-H.x;this.YQ=W-H.y}Ea(J,W){if(J!==this.JR||W!==this.Ig){g.OK(this.element,"ytp-dragging")||g.jJ(this.element,"ytp-dragging");var H=g.Hs(this.element);J=J-this.Ag-.02*this.Cr;var D=W-this.YQ-.02*this.Tz,Y=(J+H.width/2)/this.maxWidth*3;Y=Math.floor(g.t3(Y,0,2));var p=(D+H.height/2)/this.maxHeight*3;p=Math.floor(g.t3(p,0,2));W=Y+p*3;J=(J+Y/2*H.width)/this.maxWidth;J=g.t3(J,0,1)*100;H=(D+p/2*H.height)/this.maxHeight;H=g.t3(H,0,1)*100;this.A.params.KQ=W;this.A.params.aH=H;this.A.params.aW=J;this.A.params.isDefault=
!1;this.C.KQ=W;this.C.aH=H;this.C.aW=J;this.C.isDefault=!1;this.zl.KQ=W;this.zl.aH=H;this.zl.aW=J;this.zl.isDefault=!1;this.ag()}}Ua(){g.P7(this.element,"ytp-dragging")}ag(){this.S(this.B)}S(J){var W=this.yq?0:Math.min(this.E_(),this.maxWidth),H=this.kQ(),D=this.yq;if(D){var Y=getComputedStyle(this.Y.parentNode);Y=f1(Y.borderLeftWidth)+f1(Y.borderRightWidth)+f1(Y.paddingLeft)+f1(Y.paddingRight)}else Y=0;var p=Y;Y="";this.A.params.TO===3&&(Y="rotate(180deg)");var E=D?`calc(96% - ${p}px)`:"96%";g.yC(this.element,
{top:0,left:0,right:"",bottom:"",width:W?`${W}px`:"",height:H?`${H}px`:"","max-width":E,"max-height":E,margin:"",transform:""});this.Mm(J);Y={transform:Y,top:"",left:"",width:W?`${W}px`:"",height:H?`${H}px`:"","max-width":"","max-height":""};E=this.C.KQ;var Q=this.C.aW,w=this.C.aH;this.fa&&E!=null&&(Q=50,E=Math.floor(E/3)*3+1);Q=Q*.96+2;switch(E){case 0:case 3:case 6:(D=this.C.eX.fontSizeIncrement)&&D>0&&this.C.TO!==2&&this.C.TO!==3&&(Q=Math.max(Q/(1+D*2),2));Y.left=`${Q}%`;break;case 1:case 4:case 7:Y.left=
`${Q}%`;Q=0;this.J||(Q=this.Y.offsetWidth);W||Q?(W=W||Q+1,Y.width=`${W}px`,Y["margin-left"]=D?`${W/-2-p/2}px`:`${W/-2}px`):(this.J&&(Y.width="max-content"),Y.transform+=" translateX(-50%)");break;case 2:case 5:case 8:Y.right=`${100-Q}%`}D=w*.96+2;switch(E){case 0:case 1:case 2:Y.top=`${D}%`;break;case 3:case 4:case 5:Y.top=`${D}%`;D=0;this.J||(D=this.element.clientHeight);(H=H||D)?(Y.height=`${H}px`,Y["margin-top"]=`${H/-2}px`):Y.transform+=" translateY(-50%)";break;case 6:case 7:case 8:Y.bottom=
`${100-D}%`}g.yC(this.element,Y);this.L&&(this.J?H=this.W4:(J=afZ(this,J),H=this.fa?J>0?this.Y.offsetHeight/J:0:this.Y.offsetHeight/J),this.L.style.height=`${H}px`,this.L.style.width=`${H}px`,this.element.style.paddingLeft=`${H+5}px`,this.element.style.paddingRight=`${H+5}px`,this.J||(J=Number(this.element.style.marginLeft.replace("px",""))-H-5,H=Number(this.element.style.marginRight.replace("px",""))-H-5,this.element.style.marginLeft=`${J}px`,this.element.style.marginRight=`${H}px`))}Mm(J){if(this.type===
0&&this.A.params.cJ!==void 0&&this.experiments.Er("web_enable_popon_asr_captions")){var W=J,H=this.A.params.cJ;if(W.length===0||H<=0)J=[];else{J=[];for(let Y=W.length-1;Y>=0;Y--){var D=W[Y];J.unshift(D);let p=afZ(this,J);if(p>H){J.shift();typeof D.text==="string"&&(W=D.text.split("\n"),H=p-H,W.length-H>0&&(H=W.slice(H),D=new m4(D.start,D.end-D.start,D.priority||0,D.windowId,H.join("\n"),D.append,D.C),J.unshift(D)));break}}}}for(D=0;D<J.length&&J[D]===this.B[D];D++);if(this.yY||this.B.length>D)D=0,
this.yY=!1,this.B=[],this.Z=this.RB=this.b9=null,g.KR(this.Y);for(;D<J.length;D++)KrT(this,J[D])}E_(){return 0}kQ(){return 0}toString(){return super.toString()}};var tnB=class{constructor(){this.Y=this.time=this.mode=this.A=0;this.V=new PGx(this);this.Z=new PGx(this);this.C=[];this.clear()}clear(){this.Y=this.time=this.mode=0;this.C=[];this.reset()}reset(){this.mode=0;this.V.reset(0);this.Z.reset(1)}},rHp=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],xmT=class{constructor(){this.type=0}set(J){this.type=J}get(){return this.type}},zzp=class{constructor(){this.state=this.IX=this.zf=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}UJ(){return this.state!==0}matches(J,W){return this.UJ()&&J===this.zf&&W===this.IX}},Vn9=class{constructor(){this.timestamp=this.C=0}reset(){this.timestamp=
this.C=0}},Tq=class{constructor(J){this.Z=J;this.Y=[];this.C=this.A=this.row=0;this.style=new xmT;this.V=0;for(J=0;J<=15;J++){this.Y[J]=[];for(let W=0;W<=32;W++)this.Y[J][W]=new Vn9}}updateTime(J){for(let W=1;W<=15;++W)for(let H=1;H<=32;++H)this.Y[W][H].timestamp=J}debugString(){var J="\n";for(let W=1;W<=15;++W){for(let H=1;H<=32;++H){let D=this.Y[W][H];J=D.C===0?J+"_":J+String.fromCharCode(D.C)}J+="\n"}return J}reset(J){for(let W=0;W<=15;W++)for(let H=0;H<=32;H++)this.Y[W][H].reset();this.V=J;this.C=
0;this.A=this.row=1}},CBY=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],eVF=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],AHY=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,
199,200,202,203,235,206,207,239,212,217,249,219,171,187],mVY=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],N9f=class{constructor(J){this.Y=J;this.Z=0;this.style=new xmT;this.L=new Tq(this.Y);this.B=new Tq(this.Y);this.text=new Tq(this.Y);this.A=this.L;this.V=this.B;this.C=this.A}reset(J,W){this.Z=W;this.style.set(2);this.A=this.L;this.V=this.B;this.C=this.A;var H=(J<<2)+(W<<1);this.L.reset(H);this.B.reset(H);this.text.reset((J<<
2)+(W<<1)+1)}},PGx=class{constructor(J){this.C=J;this.Z=0;this.Y=new N9f(this.C);this.L=new N9f(this.C);this.A=new zzp;this.V=this.Y}reset(J){this.Z=J;this.A.clear();this.V=this.Y;this.Y.reset(J,0);this.L.reset(J,1)}};var u$B=class{V(){}};var cM=class extends g.UQ{reset(){}};var j$=class extends g.ha{constructor(J,W,H,D,Y){super(J,J+W,{priority:H,namespace:"captions"});this.id=D;this.params=Y;this.C=[]}toString(){return super.toString()}},Ok=0;var sIG=class extends cM{constructor(J){super();this.V=J;this.pens={};this.S={};this.J={};this.Z="_"+Ok++;this.B={};this.A=this.C=null;this.L=!0}reset(){this.B={};this.A=this.C=null;this.L=!0}Y(J,W){J=J.firstChild;J.getAttribute("format");W=W||0;Number.isFinite(W);J=Array.from(J.childNodes);for(var H of J)if(H.nodeType===1)switch(H.tagName){case "head":var D=H;break;case "body":var Y=H}if(D){D=Array.from(D.childNodes);for(var p of D)if(p.nodeType===1)switch(p.tagName){case "pen":H=p.getAttribute("id");
D=this.pens;J={};var E=p.getAttribute("p");E&&Object.assign(J,this.pens[E]);E=PM(p,"b");E!=null&&(J.bold=E);E=PM(p,"i");E!=null&&(J.italic=E);E=PM(p,"u");E!=null&&(J.underline=E);E=tn(p,"et");E!=null&&(J.charEdgeStyle=E);E=tn(p,"of");E!=null&&(J.offset=E);E=zq(p,"bc");E!=null&&(J.background=E);E=zq(p,"ec");E!=null&&(J.Il=E);E=zq(p,"fc");E!=null&&(J.color=E);E=tn(p,"fs");E!=null&&E!==0&&(J.fontFamily=E);E=Uk(p,"sz");E!==void 0&&(J.fontSizeIncrement=E/100-1);E=Uk(p,"bo");E!==void 0&&(J.backgroundOpacity=
E/255);E=Uk(p,"fo");E!==void 0&&(J.textOpacity=E/255);E=tn(p,"rb");E!=null&&E!==10&&E!==0&&(J.Qm=E>10?E-1:E);E=tn(p,"hg");E!=null&&(J.DZ=E);D[H]=J;break;case "ws":D=p.getAttribute("id");this.J[D]=VuT(this,p);break;case "wp":D=p.getAttribute("id"),this.S[D]=NMF(this,p)}}if(Y){p=[];Y=Array.from(Y.childNodes);for(u of Y)if(u.nodeType===1)switch(u.tagName){case "w":this.C=uiS(this,u,W,!1);(Y=this.B[this.C.id])&&Y.end>this.C.start&&(Y.end=this.C.start);this.B[this.C.id]=this.C;p.push(this.C);break;case "p":var Q=
u;J=W;Y=[];D=Q.getAttribute("w")||this.Z;H=!!PM(Q,"a");J=(Uk(Q,"t")||0)+J;E=Uk(Q,"d")||5E3;H||(!this.L&&this.A&&this.A.windowId===D&&this.A.end>J&&(this.A.end=J),this.A&&this.A.text==="\n"&&(this.A.text=""));let n=H?6:5;var w=Q.getAttribute("p");w=w?this.pens[w]:null;let l=Array.from(Q.childNodes);l.length&&(this.L=Q.getAttribute("d")!=null);for(Q=0;Q<l.length;Q++){var Z=l[Q],b=void 0;Q>0&&(H=!0);let h;Z.nodeType===1&&(h=Z);if(h&&h.tagName==="s"){if((Z=(Z=h.getAttribute("p"))?this.pens[Z]:null)&&
Z.Qm&&(Z.Qm===1?(Z=l.slice(Q,Q+4),Z.length===4&&(b=xVp(J,E,D,H,n,Z,this.pens),Q+=3)):b=xVp(J,E,D,H,n,[h],this.pens)),!b){var K=h;b=J;Z=E;var C=D,e=H;let X=K.textContent?K.textContent:"";var m=K.getAttribute("p");m=m?this.pens[m]:null;K=Uk(K,"t")||0;b=new m4(b+K,Z-K,n,C,X,e,m)}}else b=new m4(J,E,n,D,Z.textContent||"",H,w);Y.push(b);this.A=b}if(Y.length>0){Y[0].windowId===this.Z&&(this.C=uiS(this,u,W,!0),p.push(this.C));for(let h of Y)h.windowId=this.C.id,this.C.C.push(h),p.push(h)}}var u=p}else u=
[];return u}};var GvF=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),qlH=class extends cM{constructor(J){super();this.L=J;this.C=new Map;this.V=new Map;this.Z=new Map;this.A=new Map}reset(){this.A.clear()}Y(J,W){J=JSON.parse(J);if(!J)return[];if(J.pens){var H=J.pens,D=0;for(var Y of H){H={};var p=Y.pParentId;p&&Object.assign(H,this.C.get(p));Y.bAttr&&(H.bold=!0);Y.iAttr&&(H.italic=!0);Y.uAttr&&(H.underline=!0);p=Y.ofOffset;p!=null&&(H.offset=p);Y.szPenSize!==void 0&&(H.fontSizeIncrement=Y.szPenSize/100-1);
p=Y.etEdgeType;p!=null&&(H.charEdgeStyle=p);Y.ecEdgeColor!==void 0&&(H.Il=Vh(Y.ecEdgeColor));p=Y.fsFontStyle;p!=null&&p!==0&&(H.fontFamily=p);Y.fcForeColor!==void 0&&(H.color=Vh(Y.fcForeColor));Y.foForeAlpha!==void 0&&(H.textOpacity=Y.foForeAlpha/255);Y.bcBackColor!==void 0&&(H.background=Vh(Y.bcBackColor));Y.boBackAlpha!==void 0&&(H.backgroundOpacity=Y.boBackAlpha/255);(p=Y.rbRuby)&&p!==10&&(H.Qm=p>10?p-1:p,H.textEmphasis=GvF.get(H.Qm));Y.hgHorizGroup&&(H.DZ=Y.hgHorizGroup);this.C.set(D++,H)}}if(J.wsWinStyles){D=
J.wsWinStyles;Y=0;for(var E of D)D={},(H=E.wsParentId)?Object.assign(D,this.Z.get(H)):Object.assign(D,this.L),E.mhModeHint!==void 0&&(D.S8=E.mhModeHint),E.juJustifCode!==void 0&&(D.textAlign=E.juJustifCode),E.pdPrintDir!==void 0&&(D.TO=E.pdPrintDir),E.sdScrollDir!==void 0&&(D.fW=E.sdScrollDir),E.wfcWinFillColor!==void 0&&(D.windowColor=Vh(E.wfcWinFillColor)),E.wfoWinFillAlpha!==void 0&&(D.windowOpacity=E.wfoWinFillAlpha/255),this.Z.set(Y++,D)}if(J.wpWinPositions){Y=J.wpWinPositions;E=0;for(var Q of Y)Y=
{},(D=Q.wpParentId)&&Object.assign(Y,this.V.get(D)),Q.ahHorPos!==void 0&&(Y.aW=Q.ahHorPos),Q.apPoint!==void 0&&(Y.KQ=Q.apPoint),Q.avVerPos!==void 0&&(Y.aH=Q.avVerPos),Q.ccCols!==void 0&&(Y.q3=Q.ccCols),Q.rcRows!==void 0&&(Y.cJ=Q.rcRows),this.V.set(E++,Y)}if(J.events){J=J.events;Q=[];for(let v of J)if(E=(v.tStartMs||0)+W,Y=v.dDurationMs||0,v.id)D=String(v.id),J=sCH(this,v,E,Y,D),Q.push(J),this.A.set(D,J);else{v.wWinId?D=v.wWinId.toString():(D="_"+Ok++,J=sCH(this,v,E,Y,D),Q.push(J),this.A.set(D,J));
J=Q;var w=v;Y===0&&(Y=5E3);H=this.A.get(D);let HV=(p=!!w.aAppend)?6:5,SL=w.segs,PV=null;w.pPenId&&(PV=this.C.get(w.pPenId));for(w=0;w<SL.length;w++){var Z=SL[w],b=Z.utf8;if(b){var K=Z.tOffsetMs||0;let Uw=null;Z.pPenId&&(Uw=this.C.get(Z.pPenId));if((H.params.S8!=null?H.params.S8:H.C.length>1?1:0)===2&&p&&b==="\n")continue;Z=null;var C=[],e;if(e=Uw&&Uw.Qm===1)a:{e=SL;var m=w;if(m+3>=e.length||!e[m+1].pPenId||!e[m+2].pPenId||!e[m+3].pPenId){e=!1;break a}var u=e[m+1].pPenId;(u=this.C.get(u))&&u.Qm&&u.Qm===
2?(u=e[m+2].pPenId,u=this.C.get(u),!u||!u.Qm||u.Qm<3?e=!1:(u=e[m+3].pPenId,e=(u=this.C.get(u))&&u.Qm&&u.Qm===2?!0:!1)):e=!1}if(e)K=SL[w+1].utf8,Z=SL[w+3].utf8,e=SL[w+2].utf8,m=this.C.get(SL[w+2].pPenId),b=tuP(b,K,e,Z,m),Z=new m4(E,Y,HV,D,b,p,Uw),w+=3;else{if(b.indexOf("<")>-1){C=Uw;e=PV;m=E;u=Y;var n=K,l=HV,h=p;let Lo=[];var X=g.XE(`<html>${b}</html>`);if(!X.getElementsByTagName("parsererror").length&&X.firstChild?.childNodes.length)for(let Te of X.firstChild.childNodes){X=Te.textContent?.replace(/\n/g,
"")??"";if(Te.nodeType===3&&(!X||X.match(/^ *$/)!=null))continue;let Qk={};Object.assign(Qk,C||e);switch(Te?.tagName){case "b":Qk.bold=!0;break;case "i":Qk.italic=!0;break;case "u":Qk.underline=!0}Lo.push(new m4(m+n,u-n,l,H.id,X,h,Qk))}C=Lo}C.length||(C=[new m4(E+K,Y-K,HV,H.id,b,p,Uw||PV)])}if(C.length)for(let Lo of C)J.push(Lo),H.C.push(Lo);else Z&&(J.push(Z),H.C.push(Z))}p=!0}}W=Q}else W=[];return W}};var nx9=class extends g.lE{constructor(J,W,H){super(J);this.videoData=W;this.audioTrack=H;this.J=W.dV}V(J,W,H){TIH(this.videoData.videoId,J.vssId,H.yF)}Z(J){if(this.audioTrack)for(let W of this.audioTrack.captionTracks)g.o6(this.C,W);J.ud()}};var SlG=class extends BM{constructor(J,W,H,D,Y,p,E,Q,w,Z){super(J,W,H,D,Y,p,E,Q,w,Z);this.type=1}Mm(J){var W=this.A.C;super.Mm(J);for(J=J.length;J<W.length;J++){let Y=W[J],p;if(D&&Y.C===H)p=D;else{p={};Object.assign(p,Y.C);Object.assign(p,lXB);var H=Y.C;var D=p}KrT(this,Y,p)}}},lXB={J7:!0};var GmS=class extends u$B{constructor(J,W){super();this.trackData=J;this.L=W;this.version=this.Z=this.Y=this.byteOffset=0;this.A=[];this.C=new DataView(this.trackData)}V(J,W,H,D,Y){if(H<D){let p="_"+Ok++;H=H/1E3-this.L;D=D/1E3-this.L;J=new j$(H,D-H,5,p,{textAlign:0,KQ:0,aW:W*2.5,aH:J*5.33});Y=new m4(H,D-H,5,p,Y);this.A.push(J);this.A.push(Y)}}},yKf=class extends cM{constructor(J,W){super();this.A=J;this.V=W;this.track=this.V.languageName==="CC3"?4:0;this.C=new tnB;this.C.A=1<<this.track}Y(J){J=new GmS(J,
this.A);if(qJT(J)){for(;J.byteOffset<J.C.byteLength;)for(J.version===0?J.Y=ui(J)*(1E3/45):J.version===1&&(J.Y=ui(J)*4294967296+ui(J)),J.Z=ND(J);J.Z>0;J.Z--){var W=ND(J);let H=ND(J),D=ND(J);W&4&&(W&3)===this.track&&(this.track===0||this.track===1)&&(W=this.C,W.C.push({time:J.Y,type:this.track,sP:H,Ml:D,order:W.C.length}))}g1P(this.C,J);return J.A}return[]}reset(){this.C.clear()}};var gxZ=class extends BM{constructor(J,W,H,D,Y,p,E,Q,w,Z){super(J,W,H,D,Y,p,E,Q,w,Z);this.type=2;this.VY=[];this.Ca=this.qm=this.B4=0;this.DU=NaN;this.Bi=0;this.Ce=null;this.f9=new g.SJ(this.Ka,433,this);this.L&&(Z.createClientVe(this.L,this,167342),this.j(this.L,"click",()=>{Z.logClick(this.L)}),J=new g.Gz(this.element,!0),g.q(this,J),J.subscribe("hoverstart",()=>{Z.logVisibility(this.L,!0)},this));
g.jJ(this.element,"ytp-caption-window-rollup");g.q(this,this.f9);g.yC(this.element,"overflow","hidden")}ag(){g.CD(this.f9)}Ka(){this.element.removeEventListener("transitionend",this.Ka,!1);g.P7(this.element,"ytp-rollup-mode");this.S(this.Ce,!0)}kQ(){return this.V?this.Ca:this.qm}E_(){return this.V?this.qm:this.Ca}S(J,W){this.Ce=J;if(this.A.params.cJ){var H=0;for(let D=0;D<this.B.length&&H<J.length;D++)this.B[D]===J[H]&&H++;H>0&&H<J.length&&(J=this.B.concat(J.slice(H)));this.Bi=this.Ca;this.qm=this.Ca=
0;super.S(J);hVf(this,W)}super.S(J)}};var hzS=class{constructor(J,W,H,D){this.X=J;this.Z=W;this.logger=H;this.Hi=D;this.jo=[];this.C=null;this.Y=[];this.pP=[];this.A=null;this.K9={kB4:()=>this.A,
n_:()=>this.jo,
M9l:Y=>{this.Y=Y},
Lm4:()=>this.Y};
J=g.K9(this.X.G().experiments,"html5_override_micro_discontinuities_threshold_ms");this.V=J>0?J:10}unload(){this.A!=null&&(this.X.removeEventListener("sabrCaptionsDataLoaded",this.A),this.A=null);this.jo=[];this.C=null;this.Y=[];this.X.publish("sabrCaptionsBufferedRangesUpdated",this.jo)}w3(J){return{formatId:g.ap(J.info.F4.info,this.Hi),La:J.info.La+(this.Hi?0:1),startTimeMs:J.info.V*1E3,durationMs:J.info.B*1E3}}};var iAF=class extends g.lE{constructor(J,W){super(W);this.A=J;this.X=W;this.logger=new g.vv("caps");this.S=this.Ca=null;this.AR=new hzS(this.X,this,this.logger,this.A.Hi)}V(J,W,H){this.Y();W=J.getId();W=W!=null&&W in this.A.C?this.A.C[W]:null;W||(W=J.languageCode,W=this.A.isManifestless?v1Y(this,W,"386"):v1Y(this,W));W&&(this.S=J,this.Ca=W,RVY(this.AR,H),this.X.publish("sabrCaptionsTrackChanged",g.ap(W.info,this.A.Hi)))}Z(J){var W=this.A.isManifestless?FrG(this,"386"):FrG(this);for(let H of W)g.o6(this.C,
H);J.ud()}Y(){this.S&&(this.S=this.Ca=null,this.AR.unload(),this.X.publish("sabrCaptionsTrackChanged",null))}L(){return""}};var BM9="WEBVTT".split("").map(J=>J.charCodeAt(0)),HAZ=class extends cM{constructor(){super()}Y(J,W){J instanceof ArrayBuffer&&(J=g.pt(new Uint8Array(J)));
var H=[];J=J.split(IXP);for(let m=1;m<J.length;m++){var D=J[m],Y=W;if(D!==""&&!Xrf.test(D)){var p=Wt.exec(D);if(p&&p.length>=4){var E=sk(p[1]),Q=sk(p[2])-E;E+=Y;var w=(p=p[3])?p.split(" "):[];p={};var Z=null;var b="";var K=null,C="";for(let u of w){w=u.split(":");if(w.length!==2)continue;var e=w[1];switch(w[0]){case "line":w=e.split(",");w[0].endsWith("%")&&(Z=w[0],p.aH=Number.parseInt(Z,10),w.length===2&&(b=w[1].trim()));break;case "position":w=e.split(",");K=w[0];p.aW=Number.parseInt(K,10);w.length===
2&&(C=w[1].trim());break;case "align":switch(e){case "start":p.textAlign=0;break;case "middle":p.textAlign=2;break;case "end":p.textAlign=1}}}Z||b||(b="end");if(!K)switch(p.textAlign){case 0:p.aW=0;break;case 1:p.aW=100;break;case 2:p.aW=50}if(p.textAlign!=null){Z=0;switch(b){case "center":Z+=3;break;case "end":Z+=6;break;default:Z+=0}switch(C){case "line-left":Z+=0;break;case "center":Z+=1;break;case "line-right":Z+=2;break;default:switch(p.textAlign){case 0:Z+=0;break;case 2:Z+=1;break;case 1:Z+=
2}}b=Z<0||Z>8?7:Z;p.KQ=b}D=D.substring(Wt.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");C=p;p={};if(D.indexOf("<")<0&&D.indexOf("&")<0)Y=cHS(E,Q,5,C),E=new m4(E,Q,5,Y.id,D,!1,g.yS(p)?void 0:p),H.push(Y),H.push(E),Y.C.push(E);else for(b=D.split(LUB),b.length===1?(D=5,C=cHS(E,Q,D,C)):(Z=D=6,C=Object.assign({q3:32},C),C=new j$(E,Q,Z,"_"+Ok++,C)),H.push(C),Z=E,K=0;K<b.length;K++)if(w=b[K],K%2===0){e=g.XE(`<html>${w}</html>`);let u;e.getElementsByTagName("parsererror").length?(u=e.createElement("span"),
u.appendChild(e.createTextNode(w))):u=e.firstChild;o1S(this,Z,Q-(Z-E),D,C,K>0,u,p,H)}else Z=sk(w)+Y}Wt.lastIndex=0}}return H}},Xrf=/^NOTE/,IXP=/(?:\r\n|\r|\n){2,}/,Wt=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),LUB=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var RzF=class extends g.UQ{constructor(J,W){super();this.X=J;this.O=W;this.C=null;this.G5=this.X.LI();this.logger=new g.vv("caps")}clear(){this.C&&this.C.dispose();this.C=null}reset(){this.C&&this.C.reset()}Yk(){super.Yk();this.clear()}};var QIY={windowColor:"#080808",windowOpacity:0,textAlign:2,KQ:7,aW:50,aH:100,isDefault:!0,eX:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},Exp={windowColor:"#080808",windowOpacity:0,textAlign:0,KQ:7,aW:50,aH:100,isDefault:!0,eX:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.cx("captions",class extends g.nr{constructor(J){super(J);this.X=J;this.DU=[];this.zl={};this.aB={};this.B=!1;this.Y="NONE";this.C=this.J=this.AR=this.B4=this.S$=null;this.JR={ud:()=>{this.ud()},
yF:(D,Y,p,E,Q=0)=>{var w=Number(this.videoData.G().QY().C.u9(g.TjS)??0);Q>0&&w>0&&this.videoData.lengthSeconds>0&&Q/this.videoData.lengthSeconds>w?this.X.wl("tts",{dropcap:Q}):this.yF(D,Y,p,E)}};
this.A=null;this.O=this.X.G();this.videoData=this.X.getVideoData();this.Ka=this.X.dP();this.Z={eX:{}};this.L={eX:{}};this.videoData.yq()?this.Y="OFFLINE":g.DnX(this.videoData,this.X)?this.Y="HLS":dVY(this.videoData,this.X)?this.Y="SABR_LIVE":g.YoS(this.videoData,this.X)?this.Y="LIVE":this.videoData.captionTracks.length?this.Y="INNERTUBE":this.videoData.S$&&(this.Y="TTS");this.b9=this.O.controlsType==="3";this.Mm=new RzF(this.X,this.O);this.VY=new g.rC(this);this.S=new g.c({D:"div",W:"ytp-caption-window-container",
N:{id:"ytp-caption-window-container"}});this.Ca={top:0,right:0,bottom:0,left:0,width:1,height:1};var W=null,H=g.WH("yt-html5-player-modules::subtitlesModuleData");H&&(W=new g.Rt(H));this.storage=W;W=J.WC();this.Ag=!!W?.RB();this.fa=!!W?.B4();this.V=Gq(this);this.qm=prF(this);g.q(this,this.Mm);this.V?this.RB=this.yY=null:(this.yY=new g.fD(this.yq,void 0,this),g.q(this,this.yY),this.RB=new g.SJ(this.ag,2E3,this),g.q(this,this.RB));g.q(this,this.VY);g.mL(this.player,this.S.element,4);g.q(this,this.S);
this.V||this.VY.j(J,"resize",this.Ig);W=g.lf(this.O)&&!g.$$()&&!this.X.isFullscreen();H=this.O.QY().C.u9(g.S7t)&&g.gx(this.O)&&g.xE;(this.YQ=(W||H)&&!this.V&&!this.qm)&&this.VY.j(J,W?"resize":"fullscreentoggled",this.E_);this.VY.j(J,"onPlaybackAudioChange",this.kQ);this.VY.j(J,g.VI("captions"),D=>{this.onCueRangeEnter(D)});
this.VY.j(J,g.N0("captions"),D=>{this.onCueRangeExit(D)});
qD(this,rb()||{});g.BD(this.player,"onCaptionsModuleAvailable");this.Y==="HLS"&&this.V&&(J=this.X.WC().Ff(),this.fa&&this.VY.j(J.textTracks,"addtrack",this.Bi))}Yk(){if(this.V||this.qm){let J=this.X.WC();J&&!J.e$()&&J.B()}else n1(this,!1);super.Yk()}pW(){return this.O.U("html5_honor_caption_availabilities_in_audio_track")&&this.Y!=="LIVE"&&this.Y!=="SABR_LIVE"}lB(){if(this.b9)return this.V||this.qm;if(this.Y==="HLS")return this.V;var J=this.getAudioTrack();if(this.pW()){if(!J.captionTracks.length)return!1;
if(!this.C)return!0}J=bi(J,g.o_(this.O));return J==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:J==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?ii(this):hn(this)||ii(this)?!0:aXf(this)}load(){super.load();this.J=this.getAudioTrack();if(this.C)this.A&&(this.Mm.clear(),this.V?kvG(this,!0):this.player.getPresentingPlayerType()!==3&&this.C.V(this.A,"json3",this.JR),this.Y!=="HLS"&&this.V||this.qm||IU(this)||g.BD(this.player,"captionschanged",g.zy(this.A)));else{let J;this.Y==="OFFLINE"?J=new nx9(this.player,this.videoData,
this.getAudioTrack()):this.Y==="SABR_LIVE"?J=new iAF(this.videoData.C,this.player):this.Y==="HLS"?J=new AKB(this.player):this.Y==="LIVE"?J=new jIS(this.videoData.C,this.player):this.Y==="INNERTUBE"?J=new g.yL(this.player,this.videoData,this.getAudioTrack()):J=new g.hq(this.player,this.videoData.S$,this.videoData.videoId,g.CNM(this.videoData),this.videoData.cH,this.videoData.eventId);this.C=J;g.q(this,this.C);this.C.Z(this.JR)}}unload(){this.V&&this.A?kvG(this,!1):(this.RB&&this.RB.NJ(),this.player.lx("captions"),
this.DU=[],this.C&&this.C.Y(),this.Mm.clear(),this.AR&&this.player.yR(this.AR),this.Ig());super.unload();this.player.xG();g.BD(this.player,"captionschanged",{})}create(){this.lB()&&this.load();var J;a:{if(this.O.U("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(J=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(let W of J)if(W.kind==="asr"&&W.languageCode===
"en"){J=!0;break a}J=!1}J&&this.X.publish("showpromotooltip",this.S.element)}ud(){var J=bi(this.player.getAudioTrack(),g.o_(this.O));var W=J==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?L1(this,this.B):J==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&ii(this)?XM(this):hn(this)||this.B||aXf(this)?L1(this,this.B):ii(this)?XM(this):null;if(this.Y!=="HLS"&&this.V||this.qm){let H=g.NN(this.C.C,!0);J=[];for(let D=0;D<H.length;D++){let Y=H[D],p=g.ab("TRACK");p.setAttribute("kind","subtitles");p.setAttribute("label",
g.xg(Y));p.setAttribute("srclang",g.V8(Y));p.setAttribute("id",Y.toString());this.qm||p.setAttribute("src",this.C.L(Y,"vtt"));Y===W&&p.setAttribute("default","1");J.push(p)}W=this.X.WC();W.AR(J);J=W.Ff();this.fa&&this.VY.j(J.textTracks,"change",this.rP)}else!this.A&&W&&FM(this,W),g.BD(this.player,"onCaptionsTrackListChanged"),g.TJ(this.player,"onApiChange")}rP(){var J=this.X.WC().Ff().textTracks,W=null;for(let H=0;H<J.length;H++)if(J[H].mode==="showing")a:{W=g.NN(this.C.C,!0);for(let D=0;D<W.length;D++)if(W[D].toString()===
J[H].id){W=W[D];break a}W=null}(this.loaded?this.A:null)!==W&&FM(this,W,!0)}Bi(){this.C?.Z(this.JR)}sz(){!this.A&&this.V||this.unload()}yF(J,W,H,D){if(J){vM(this,this.A??void 0);this.C.qm()&&(this.DU=[],this.X.lx("captions"),k3(this.yY),this.Mm.reset());a:{var Y=this.Mm;D=D||0;H=WU9(Y,J,H||0);J=[];try{for(let l of H){let h=l.trackData,X=l.vn,v=Y.O.U("safari_live_drm_captions_fix");if(typeof h!=="string"){H=J;var p=H.concat;if(v&&TMf(h))var E=Dmf(Y,h,X);else{var Q=Y,w=W,Z=h,b=X,K=D;if(!n19(Z))throw Error("Invalid binary caption track data");
Q.C||(Q.C=new yKf(K,w));E=Q.C.Y(Z,b)}var C=p.call(H,E)}else{if(h.substring(0,6)==="WEBVTT")var e=J.concat(Dmf(Y,h,X));else{H=J;var m=H.concat;b:{w=Y;Q=W;if(h[0]==="{")try{w.C||(w.C=new qlH(YlF(Q)));var u=w.C.Y(h,X);break b}catch(PV){g.cb(PV);u=[];break b}let HV=g.XE(h);if(!HV||!HV.firstChild){let PV=Error("Invalid caption track data");PV.params=h;throw PV;}if(HV.firstChild.tagName==="timedtext"){if(Number(HV.firstChild.getAttribute("format"))===3){Z=HV;w.C||(w.C=new sIG(YlF(Q)));u=w.C.Y(Z,X);break b}let PV=
Error("Unsupported subtitles format in web player (Format2)");PV.params=h;throw PV;}if(HV.firstChild.tagName==="transcript"){let PV=Error("Unsupported subtitles format in web player (Format1)");PV.params=h;throw PV;}let SL=Error("Invalid caption track data");SL.params=h;throw SL;}e=m.call(H,u)}C=e}J=C}var n=J;break a}catch(l){g.Fx(Y.logger,187101178,`Captions parsing failed: ${l.message}. `);Y.clear();n=[];break a}n=void 0}this.O.U("html5_sabr_live_support_subfragmented_captions")&&this.C instanceof
iAF&&(W=this.C.AR,Y=[],n.length>0&&(Y=n.slice(W.Y.length)),W.Y=!W.C||W.C.info.RL?[]:n,n=Y);n.length>0&&(W=this.A,this.YY(W,!!W,IU(this)?"g":this.B?"m":"s"));this.player.yR(n,void 0,this.Y==="LIVE"||this.Y==="SABR_LIVE");!this.B||this.qm||IU(this)||g.fs(this.O)||g.n6(this.O)||g.$O(this.O)||this.O.VY==="shortspage"||this.player.isInline()||(this.RB.NJ(),n=zV9({KQ:0,aW:5,aH:5,cJ:2,textAlign:0,TO:0,lang:"ru"}),this.B4=[n],W=["\u0414\u043b\u044f \u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u043d\u0430\u0436\u043c\u0438\u0442\u0435 \u043d\u0430 \u0437\u043d\u0430\u0447\u043e\u043a ",
""],this.S$||(Y=new g.z6(g.BP()),g.q(this,Y),this.S$=Y.element),Y=n.end-n.start,(C=g.xg(this.A))&&this.B4.push(new m4(n.start,Y,0,n.id,C)),this.B4.push(new m4(n.start,Y,0,n.id,W[0]),new m4(n.start,Y,0,n.id,this.S$,!0),new m4(n.start,Y,0,n.id,W[1],!0)),this.player.yR(this.B4),g.gL(this.RB));!this.B||this.qm||IU(this)||(this.O.U("enable_player_captions_persistence_state_machine")?yh(this,!0):g.o_(this.O)?RU(this,!0):db(this,!0),this.J&&(this.J.V=this.A),this.player.xG());this.B=!1}}onCueRangeEnter(J){this.DU.push(J);
k3(this.yY)}onCueRangeExit(J){g.pZ(this.DU,J);this.C instanceof jIS&&this.C.Ca&&this.player.Ro([J]);k3(this.yY)}getCaptionWindowContainerId(){return this.S.element.id}ag(){wrY(this,this.B4);this.B4=null}yq(){if(!this.YQ||!this.V){this.yY.stop();g.If(this.aB);this.DU.sort(g.zs);var J=this.DU;if(this.AR){let W=g.IS(J,function(H){return this.AR.indexOf(H)===-1},this);
W.length&&(J=W)}for(let W of J)W instanceof j$?rKB(this,W):fXT(this,W);for(let [W,H]of Object.entries(this.zl)){let D=W,Y=H;this.aB[D]?(Y.element.parentNode||(Y instanceof gxZ||Y instanceof SlG||g.tp(this.zl,(p,E)=>{E!==D&&p.A.params.KQ===Y.A.params.KQ&&p.A.params.aW===Y.A.params.aW&&p.A.params.aH===Y.A.params.aH&&(p.dispose(),delete this.zl[E]);return E===D},this),this.S.element.appendChild(Y.element)),Y.S(this.aB[D])):(Y.dispose(),delete this.zl[D])}}}ob(){qD(this,{},!0);
g.BD(this.player,"captionssettingschanged")}Mb(){var J=this.O.U("enable_player_captions_new_style_defaults")?Exp:QIY,W=J.eX;J={background:W.background,backgroundOpacity:W.backgroundOpacity,charEdgeStyle:W.charEdgeStyle,color:W.color,fontFamily:W.fontFamily,fontSizeIncrement:W.fontSizeIncrement,fontStyle:W.bold&&W.italic?3:W.bold?1:W.italic?2:0,textOpacity:W.textOpacity,windowColor:J.windowColor,windowOpacity:J.windowOpacity};W=rb()||{};W.background!=null&&(J.background=W.background);W.backgroundOverride!=
null&&(J.backgroundOverride=W.backgroundOverride);W.backgroundOpacity!=null&&(J.backgroundOpacity=W.backgroundOpacity);W.backgroundOpacityOverride!=null&&(J.backgroundOpacityOverride=W.backgroundOpacityOverride);W.charEdgeStyle!=null&&(J.charEdgeStyle=W.charEdgeStyle);W.charEdgeStyleOverride!=null&&(J.charEdgeStyleOverride=W.charEdgeStyleOverride);W.color!=null&&(J.color=W.color);W.colorOverride!=null&&(J.colorOverride=W.colorOverride);W.fontFamily!=null&&(J.fontFamily=W.fontFamily);W.fontFamilyOverride!=
null&&(J.fontFamilyOverride=W.fontFamilyOverride);W.fontSizeIncrement!=null&&(J.fontSizeIncrement=W.fontSizeIncrement);W.fontSizeIncrementOverride!=null&&(J.fontSizeIncrementOverride=W.fontSizeIncrementOverride);W.fontStyle!=null&&(J.fontStyle=W.fontStyle);W.fontStyleOverride!=null&&(J.fontStyleOverride=W.fontStyleOverride);W.textOpacity!=null&&(J.textOpacity=W.textOpacity);W.textOpacityOverride!=null&&(J.textOpacityOverride=W.textOpacityOverride);W.windowColor!=null&&(J.windowColor=W.windowColor);
W.windowColorOverride!=null&&(J.windowColorOverride=W.windowColorOverride);W.windowOpacity!=null&&(J.windowOpacity=W.windowOpacity);W.windowOpacityOverride!=null&&(J.windowOpacityOverride=W.windowOpacityOverride);return J}h1(J,W){var H={};Object.assign(H,rb());Object.assign(H,J);qD(this,H,W);g.BD(this.player,"captionssettingschanged")}Ig(){!this.V&&this.loaded&&(g.OF(this.zl,function(J,W){J.dispose();delete this.zl[W]},this),this.yq())}ED(J,W){switch(J){case "fontSize":if(isNaN(W))break;
J=g.t3(W,-2,4);this.h1({fontSizeIncrement:J});return J;case "reload":W&&!this.V&&FM(this,this.A,!0);break;case "stickyLoading":W!==void 0&&this.O.AR&&(this.O.U("enable_player_captions_persistence_state_machine")?yh(this,!(!W||!W.userInitiated)):g.o_(this.O)?RU(this,!!W):db(this,!!W));break;case "track":return CGT(this,W);case "tracklist":return this.C?g.Xt(g.NN(this.C.C,!(!W||!W.includeAsr)),H=>g.zy(H)):[];
case "translationLanguages":return this.C?this.C.J.map(H=>Object.assign({},H)):[];
case "sampleSubtitles":this.V||W===void 0||n1(this,!!W);break;case "sampleSubtitlesCustomized":this.V||n1(this,!!W,W);break;case "recommendedTranslationLanguages":return g.ek();case "defaultTranslationSourceTrackIndices":return this.C?this.C.zl:[]}}getOptions(){var J="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.O.AR&&J.push("stickyLoading");return J}Wl(){var J=this.A;if(this.X.YG("captions")){if(this.O.U("html5_modify_caption_vss_logging"))return(J=this.videoData.jn??
null)?{cc:g.pvp(J)}:{};if(J){let W=J.vssId;J.translationLanguage&&W&&(W=`t${W}.${g.V8(J)}`);return{cc:W}}}return{}}bA(J){this.isSubtitlesOn()?(this.O.U("enable_player_captions_persistence_state_machine")&&J?yh(this,!1):g.o_(this.O)?RU(this,!1):db(this,!1),vM(this),FM(this,null,!0)):this.pj(J)}pj(J){var W=IU(this)||!this.A?L1(this,!0):this.A;W&&this.BR(W.vssId,"m");this.isSubtitlesOn()||FM(this,W,this.O.U("enable_player_captions_persistence_state_machine")?J:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.A&&!IU(this)}kQ(){var J=IU(this);ii(this,J)?FM(this,this.getAudioTrack().C,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.pW()&&(this.B=!1,this.A=null,this.C&&(this.C.dispose(),this.C=null)),this.lB()&&(J?FM(this,L1(this,!1),!1):this.load()))}RV(J){J&&(this.Ca={top:J.top,right:J.right,bottom:J.bottom,left:J.left,width:1-J.left-J.right,height:1-J.top-J.bottom},this.S.element.style.top=`${this.Ca.top*100}%`,this.S.element.style.left=`${this.Ca.left*100}%`,this.S.element.style.width=
`${this.Ca.width*100}%`,this.S.element.style.height=`${this.Ca.height*100}%`,this.S.element.style.position="absolute",J=$mP(this))&&(this.S.element.style.width=`${J.width}px`,this.S.element.style.height=`${J.height}px`)}onVideoDataChange(J,W){J==="newdata"&&(this.videoData=W,this.loaded&&this.unload(),this.B=!1,this.A=null,this.C&&(this.C.dispose(),this.C=null,g.BD(this.player,"captionschanged",{})),this.lB()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}E_(){if(this.O.QY().C.u9(g.S7t)){if(this.loaded&&
this.unload(),this.b9=this.X.isFullscreen()||this.O.controlsType==="3",this.V=Gq(this),this.qm=prF(this),this.V||this.qm){var J=this.X.WC();J&&!J.e$()&&J.B();this.ud()}}else(J=this.X.WC())&&!J.e$()&&J.B(),this.X.isFullscreen()?(this.V=this.b9=!0,this.loaded&&this.ud()):(this.b9=this.O.controlsType==="3",this.V=Gq(this));FM(this,this.A)}W4(){var J=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;J&&g.LQ(this.player,"innertubeCommand",J)}YY(J,W,H){var D=
/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,Y="";J&&(Y=J.vssId,Y=Y.replace(D,""));var p="";J&&J.getId()&&(p=J.getId()||"");J&&J.getXtags()&&(J=J.getXtags(),J=J.replace(D,""),p=p.concat(`;${J}`));this.Y==="HLS"&&(p="");this.X.YY(W?Y:"",W?p:"",H)}BR(J,W){J=(J||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");J.length>0&&this.X.BR(J,W)}});})(_yt_player);
