(function(g){var window=this;'use strict';var gX=function(J){J.isActive()||J.start()},Ce=function(J){var W={languageCode:J.languageCode,
languageName:J.languageName,displayName:g.TB(J),kind:J.kind,name:J.name,id:J.id,is_servable:J.C,is_default:J.isDefault,is_translateable:J.isTranslateable,vss_id:J.vssId};J.xtags&&(W.xtags=J.xtags);J.captionId&&(W.captionId=J.captionId);J.translationLanguage&&(W.translationLanguage=J.translationLanguage);return W},wte=function(J,W){var H=new g.Fm;
H.languageCode=J.languageCode;H.languageName=J.languageName;H.name=J.name;H.displayName=J.displayName;H.kind=J.kind;H.isDefault=!1;H.C=J.C;H.isTranslateable=J.isTranslateable;H.vssId=J.vssId;H.url=J.url;H.translationLanguage=W;J.xtags&&(H.xtags=J.xtags);J.captionId&&(H.captionId=J.captionId);return H},e5=function(J,W){return W?J.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},Zjt=function(J){return g.kB(J)||J.L("web_enable_caption_language_preference_stickiness")},McS=async function(J,W){J=
J+"|"+W;
W=await g.LH();if(!W)throw g.Y$("gct");return(await g.fQ(W)).get("captions",J)},aQ2=function(J,W,H){McS(J,W).then(D=>{D&&H(D.trackData,new g.Fm(D.metadata))})},Ag=function(J){if(!kge.test(J))throw Error("'"+J+"' is not a valid hex color");
J.length==4&&(J=J.replace(bjW,"#$1$1$2$2$3$3"));J=J.toLowerCase();J=parseInt(J.slice(1),16);return[J>>16,J>>8&255,J&255]},KWL=function(){var J={},W="suggest_correction"in g.Cg?g.Cg.suggest_correction:"Edit caption";
W=W||"";for(let H in J){let D=()=>String(J[H]);
W=W.replace(new RegExp("\\$\\{"+H+"\\}","gi"),D);W=W.replace(new RegExp("\\$"+H,"gi"),D)}return W},ml=function(){return g.gS("yt-player-caption-display-settings")},rhX=function(J,W){g.If(W,H=>J.equals(H))||W.push(J)},O8=function(J,W){switch(W.kind){case "asr":rhX(W,J.Y);
break;default:rhX(W,J.A)}},fQt=async function(J,W,H){J.A=g.c7(W,H)},$Me=function(J,W){var H=g.Dg(J.segments,W);
H>=0||H<0&&(-H-1)%2===1||(H=-H-1,H>0&&W-J.segments[H-1]===1&&H<J.segments.length&&J.segments[H]-W===1?(g.v9(J.segments,H),g.v9(J.segments,H-1)):H>0&&W-J.segments[H-1]===1?J.segments[H-1]=W:H<J.segments.length&&J.segments[H]-W===1?J.segments[H]=W:(g.J4(J.segments,H,0,W),g.J4(J.segments,H+1,0,W)))},Sbe=function(J){return J.C&&J.C.Z?J.C.Z+J.player.Rg()<J.player.getCurrentTime():!1},g0t=function(J,W){if(J.policy.pv&&J.player.CQ()){var H=g.C9(W,J.policy,{});
H.set("pot",J.player.CQ());H=H.Dq()}else H=g.C9(W,J.policy,{}).Dq();var D={format:"RAW",withCredentials:!0};if(J.policy.yY){D.method="POST";let E=W.V;E&&Object.keys(E).length>0?D.postBody=g.hI(E,g.pI):D.postBody=(0,g.Ky)([120,0])}J.Z&&(D.responseType="arraybuffer");var Y=++J.zl,p=(0,g.R)();J.A=g.E1(H,D,3,100,-1,E=>{E.errorCode==="net.timeout"&&J.player.S("capnt",{rn:Y++})}).then(E=>{if(J.policy.mY&&Y%100===1){var Q=(0,g.R)();
J.player.S("caprsp",{rn:Y,ms:Q-p,kb:(E.xhr.responseText.length/1024).toFixed()})}a:{E=E.xhr;J.F4();if(J.Y){var w=!(J.Z?E.response:E.responseText)||E.status>=400;if(Q=g.F_(E)){E=g.C9(J.Y,J.policy,{});J.Y.Cq(E,Q);g0t(J,J.Y);break a}w?J.player.S("capfail",{status:E.status}):(g.PO("fcb_r",(0,g.R)(),J.player.getVideoData()?.Zh||""),Q=J.Y.JR[0],w=Q.DU,J.B!=null&&J.D!==w&&(J.Z?J.B(E.response,(Q.segmentStartTime+J.player.Rg())*1E3):J.B(E.responseText,(Q.segmentStartTime+J.player.Rg())*1E3),J.D=w))}J.Y=null;
J.A=null}}).Ec(E=>{J.Y=null;
J.A=null;J.player.S("capfail",{rn:Y,status:E.xhr?.status})});
J.Y=W;$Me(J.V,J.Y.JR[0].DU)},Cbo=function(J,W){return W!=null&&W in J.A.C?J.A.C[W]:null},est=function(J,W,H){var D=[];
for(let Y in J.A.C){if(!J.A.C.hasOwnProperty(Y))continue;let p=J.A.C[Y];if(g.qz(p,H||null)){let E=p.info.captionTrack;E&&E.languageCode===W&&D.push(p)}}return D.length?D[0]:null},Aht=function(J,W){var H=[];
for(let Y in J.A.C){if(!J.A.C.hasOwnProperty(Y))continue;var D=J.A.C[Y];if(g.qz(D,W||null)){let p=D.info.id,E=p,Q=`.${p}`,w="",k="";if(D=D.info.captionTrack)p=D.languageCode,E=D.displayName,Q=D.vssId,w=D.kind,k=D.id;H.push(new g.Fm({id:Y,languageCode:p,languageName:E,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:Q,kind:w,captionId:k}))}}return H},j5=function(J){if(typeof DOMParser!="undefined")return g.kV(new DOMParser,g.ZB(J),"application/xml");
throw Error("Your browser does not support loading xml documents");},mM2=function(J,W,H,D){var Y=W/360*16;
W>=J&&(J=640,D>H*1.3&&(J=480),Y=H/J*16);return Y},Oj2=function(J){var W=1+.25*(J.fontSizeIncrement||0);
if(J.offset===0||J.offset===2)W*=.8;return W},j2V=function(J,W){var H="vertical-rl";
J.C.Gw===1&&(H="vertical-lr");g.d5&&(H=H==="vertical-lr"?"tb-lr":"tb-rl");g.oz(W,"-o-writing-mode",H);g.oz(W,"-webkit-writing-mode",H);g.oz(W,"writing-mode",H);g.oz(W,"text-orientation","upright");g.en(W,"ytp-vertical-caption");J.Y.params.wN===3&&(g.oz(W,"text-orientation",""),g.oz(W,"transform","rotate(180deg)"))},UMw=function(J,W){var H={},D=W.background?W.background:J.C.PZ.background;
if(W.backgroundOpacity!=null||W.background){var Y=W.backgroundOpacity!=null?W.backgroundOpacity:J.C.PZ.backgroundOpacity;D=Ag(D);H.background="rgba("+D[0]+","+D[1]+","+D[2]+","+Y+")";J.Mm&&(H["box-decoration-break"]="clone",H["border-radius"]=`${J.gP*.25}px`)}if(W.fontSizeIncrement!=null||W.offset!=null)H["font-size"]=`${J.Ka*Oj2(W)}px`;J.experiments.W4("enable_player_captions_new_style_defaults")&&(H["line-height"]="1.375");D=1;Y=W.color||J.C.PZ.color;if(W.color||W.textOpacity!=null)Y=Ag(Y),D=W.textOpacity==
null?J.C.PZ.textOpacity:W.textOpacity,Y="rgba("+Y[0]+","+Y[1]+","+Y[2]+","+D+")",H.color=Y,H.fill=Y;var p=W.charEdgeStyle;p===0&&(p=void 0);if(p){Y=`rgba(34, 34, 34, ${D})`;let w=`rgba(204, 204, 204, ${D})`;W.hp&&(w=Y=W.hp);let k=J.Ka/16/2,K=Math.max(k,1);var E=Math.max(2*k,1),Q=Math.max(3*k,1);let r=Math.max(5*k,1);D=[];switch(p){case 4:for(;Q<=r;Q+=k)D.push(`${E}px ${E}px ${Q}px ${Y}`);break;case 1:E=window.devicePixelRatio>=2?.5:1;for(p=K;p<=Q;p+=E)D.push(`${p}px ${p}px ${Y}`);break;case 2:D.push(`${K}px ${K}px ${w}`);
D.push(`-${K}px -${K}px ${Y}`);break;case 3:for(Q=0;Q<5;Q++)D.push(`0 0 ${E}px ${Y}`)}H["text-shadow"]=D.join(", ")}Y="";switch(W.fontFamily){case 1:Y=J.ix?'"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", serif-monospace, monospace':'"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:Y='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:Y=J.ix?'"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", sans-serif-monospace, monospace':
'"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:Y='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:Y='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:Y=g.O1()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:Y='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}Y&&(H["font-family"]=Y);Y=W.offset;Y==
null&&(Y=J.C.PZ.offset);switch(Y){case 0:H["vertical-align"]="sub";break;case 2:H["vertical-align"]="super"}W.fontFamily===7&&(H["font-variant"]="small-caps");W.bold&&(H["font-weight"]="bold");W.italic&&(H["font-style"]="italic");W.underline&&(H["text-decoration"]="underline");W.R$&&(H.visibility="hidden");W.eB===1&&J.D&&(H["text-combine-upright"]="all",H["text-orientation"]="mixed",Y=g.gm||g.WN,J.Y.params.wN===3?H.transform=Y?"rotate(90deg)":"rotate(180deg)":Y&&(H.transform="rotate(-90deg)"));if(W.textEmphasis===
1||W.textEmphasis===2||W.textEmphasis===3||W.textEmphasis===4||W.textEmphasis===5)if(g.gm)H["font-weight"]="bold";else switch(H["text-emphasis-style"]="filled circle",H["text-emphasis-color"]="currentcolor",H["webkit-text-emphasis"]="filled circle",W.textEmphasis){case 4:case 3:H["text-emphasis-position"]="under left";H["webkit-text-emphasis-position"]="under left";break;case 5:case 2:H["text-emphasis-position"]="over right",H["webkit-text-emphasis-position"]="over right"}return H},PbL=function(J,
W){if(J.dP&&W.length===0)return 0;
J=1;for(let H=0;H<W.length;H++){let D=W[H];typeof D.text==="string"&&(J+=D.text.split("\n").length-1,D.append||H===0||J++)}return J},U8=function(J){J=J.split("px");
return J.length>0?(J=Number(J[0]))?J:0:0},zse=function(J,W,H){J.u9=J.u9||!!H;
var D={};Object.assign(D,J.C.PZ);Object.assign(D,H||W.C);Object.assign(D,J.BO.PZ);(H=!J.X)&&tc2(J);var Y=J.oB&&J.i9&&g.w8(D,J.i9)?J.oB:xML(J,D),p=typeof W.text==="string",E=p?W.text.split("\n"):[W.text];for(let w=0;w<E.length;w++){var Q=w>0||!W.append;let k=E[w];Q&&!H?(tc2(J),Y=xML(J,D)):Q&&H&&(H=!1);k&&(Y.appendChild(p?g.uQ(k):k),p||k.tagName!=="RUBY"||k.childElementCount!==4||g.gm||!g.Df(k.children[2],"text-emphasis")||(Q=J.D?"padding-right":"padding-top",g.Df(k.children[2],"text-emphasis-position")&&
(Q=J.D?"padding-left":"padding-bottom"),g.U9?g.oz(Y,Q,"1em"):g.oz(Y,Q,"0.5em")))}J.i9=D;J.oB=Y;J.K.push(W)},tc2=function(J){if(J.X){var W=J.X;
if(J.Mm){var H=J.C.textAlign;H===0?(W=W.firstElementChild)&&g.oz(W,{"border-bottom-left-radius":"0"}):H===1&&(W=W.lastElementChild)&&g.oz(W,{"border-bottom-right-radius":"0"})}}J.X=g.Ni("SPAN");g.oz(J.X,{display:"block"});g.en(J.X,"caption-visual-line");J.Z.appendChild(J.X)},xML=function(J,W){var H=g.Ni("SPAN");
g.oz(H,{display:"inline-block","white-space":"pre-wrap"});g.oz(H,UMw(J,W));H.classList.add("ytp-caption-segment");J.X.appendChild(H);J.Mm&&J.Z.children.length>1&&(J=J.C.textAlign,J===0?H.previousElementSibling||g.oz(H,{"border-top-left-radius":"0"}):J===1&&g.oz(H,{"border-top-right-radius":"0"}));H.previousElementSibling&&(g.oz(H.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.oz(H,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return H},
NKM=function(J,W,H){if(J===255&&W===255||!J&&!W)return{Q_:J,
ot:W,result:0};J=Vce[J];W=Vce[W];if(J&128){var D;if(D=!(W&128))D=W,D=H.z9()&&H.ot===D;if(D)return{Q_:J,ot:W,result:1}}else if(W&128&&1<=J&&J<=31)return{Q_:J,ot:W,result:2};return{Q_:J,ot:W,result:3}},s2w=function(J,W,H,D){W===255&&H===255||!W&&!H?(++J.Y===45&&J.reset(),J.V.A.clear(),J.Z.A.clear()):(J.Y=0,uNe(J.V,W,H,D))},GgX=function(J,W){J.C.sort((H,D)=>{var Y=H.time-D.time;
return Y===0?H.order-D.order:Y});
for(let H of J.C)J.time=H.time,H.type===0?s2w(J,H.gC,H.qd,W):H.type===1&&J.A&496&&uNe(J.Z,H.gC,H.qd,W);J.C.length=0},hsw=function(J,W){switch(J){case 0:return qbS[(W&127)-32];
case 1:return n0M[W&15];case 2:return lQt[W&31];case 3:return yh2[W&31]}return 0},PF=function(J,W){if(J.style.type===3){var H=0,D=0,Y=J.Z.time+0,p="",E="",Q=Y;
for(var w=1;w<=15;++w){var k=!1;for(var K=D?D:1;K<=32;++K){var r=J.Y[w][K];if(r.C!==0){H===0&&(H=w,D=K);k=String.fromCharCode(r.C);var C=r.timestamp;C<Y&&(Y=C);r.timestamp=Q;E&&(p+=E,E="");p+=k;k=!0}if((r.C===0||K===32)&&k){E="\n";break}else if(D&&!k)break}if(H&&!k)break}p&&W.V(H,D,Y,Q,p)}else for(D=H=0,p=Y=J.Z.time+0,E=1;E<=15;++E)for(Q="",w=1;w<=32;++w)if(K=J.Y[E][w],r=K.C,r!==0&&(H===0&&(H=E,D=w),k=String.fromCharCode(r),C=K.timestamp,C<=Y&&(Y=C),Q+=k,K.reset()),w===32||r===0)Q&&W.V(H,D,Y,p,Q),
Y=p,Q="",D=H=0},tg=function(J){return J.Y[J.row][J.A]},xu=function(J,W,H){W>=2&&J.A>1&&(--J.A,tg(J).C=0);
var D=tg(J);D.timestamp=J.Z.time+0;D.C=hsw(W,H);J.A<32&&J.A++},ijS=function(J,W,H,D){for(let E=0;E<D;E++)for(let Q=0;Q<=32;Q++){var Y=J.Y[W+E][Q],p=J.Y[H+E][Q];
Y.C=p.C;Y.timestamp=p.timestamp}},z7=function(J,W,H){for(let D=0;D<H;D++)for(let Y=0;Y<=32;Y++)J.Y[W+D][Y].reset()},VW=function(J){J.row=J.C>0?J.C:1;
J.A=1;z7(J,0,15)},IQe=function(J){J.style.set(1);
J.C=J.V;J.C.C=0;J.C.style=J.style;J.Y.mode=1<<J.C.V},NJ=function(J,W,H){var D=J.A,Y=!1;
switch(J.style.get()){case 4:case 1:case 2:J.style.get()===4&&D.C>0||(PF(D,H),VW(J.A),VW(J.V),D.row=15,D.C=W,Y=!0)}J.style.set(3);J.C=D;J.C.style=J.style;J.Y.mode=1<<D.V;Y?D.A=1:D.C!==W&&(D.C>W?(PF(D,H),z7(D,D.row-D.C,W)):D.row<W&&(W=D.C),D.C=W)},XtL=function(J){J.style.set(4);
J.C=J.text;J.C.style=J.style;J.Y.mode=1<<J.C.V},uNe=function(J,W,H,D){J.A.update();
W=NKM(W,H,J.A);switch(W.result){case 0:return;case 1:case 2:return}var Y=W.Q_;W=W.ot;if(32<=Y||!Y)J.C.mode&J.C.A&&(H=Y,H&128&&(H=127),W&128&&(W=127),J=J.V.C,H&96&&xu(J,0,H),W&96&&xu(J,0,W),H!==0&&W!==0&&J.style.type===3&&PF(J,D));else if(Y&16)a:if(!J.A.matches(Y,W)&&(H=J.A,H.Q_=Y,H.ot=W,H.state=2,H=Y&8?J.D:J.Y,J.V=H,J.C.mode=1<<(J.Z<<2)+(H.Z<<1)+(H.style.type===4?1:0),(J.C.mode|1<<(J.Z<<2)+(H.Z<<1)+(H.style.type!==4?1:0))&J.C.A))if(W&64){D=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(Y&7)<<1|W>>5&1];
J=W&16?((W&14)>>1)*4:0;W=H.C;switch(H.style.get()){case 4:D=W.row;break;case 3:if(D!==W.row){if(D<W.C&&(D=W.C,D===W.row))break;var p=1+W.row-W.C;let E=1+D-W.C;ijS(W,E,p,W.C);H=p;Y=W.C;E<p?(p=E+Y-p,p>0&&(H+=p,Y-=p)):(p=p+Y-E,p>0&&(Y-=p));z7(W,H,Y)}}W.row=D;W.A=J+1}else switch(Y&7){case 1:switch(W&112){case 32:xu(H.C,0,32);break a;case 48:W===57?(D=H.C,tg(D).C=0,D.A<32&&D.A++):xu(H.C,1,W&15)}break;case 2:W&32&&xu(H.C,2,W&31);break;case 3:W&32&&xu(H.C,3,W&31);break;case 4:case 5:if(32<=W&&W<=47)switch(W){case 32:IQe(H);
break;case 33:D=H.C;D.A>1&&(--D.A,tg(D).C=0);break;case 36:D=H.C;J=tg(D);for(W=0;W<=15;W++)for(H=0;H<=32;H++)if(D.Y[W][H]===J){for(;H<=32;H++)D.Y[W][H].reset();break}break;case 37:NJ(H,2,D);break;case 38:NJ(H,3,D);break;case 39:NJ(H,4,D);break;case 40:xu(H.C,0,32);break;case 41:D=H;D.style.set(2);D.C=D.A;D.C.C=0;D.C.style=D.style;D.Y.mode=1<<D.C.V;break;case 42:D=H;J=D.text;J.C=15;J.style.set(4);VW(J);XtL(D);break;case 43:XtL(H);break;case 44:J=H;W=J.A;switch(J.style.get()){case 1:case 2:case 3:PF(W,
D)}z7(W,0,15);break;case 45:b:{W=H;J=W.C;switch(W.style.get()){default:case 2:case 1:break b;case 4:if(J.row<15){++J.row;J.A=1;break b}break;case 3:}J.C<2&&(J.C=2,J.row<J.C&&(J.row=J.C));W=J.row-J.C+1;PF(J,D);ijS(J,W,W+1,J.C-1);z7(J,J.row,1)}break;case 46:z7(H.V,0,15);break;case 47:J=H,PF(J.A,D),J.V.updateTime(J.Y.time+0),D=J.V,J.V=J.A,J.A=D,IQe(J)}break;case 7:switch(W){case 33:case 34:case 35:D=H.C,(D.A+=W&3)>32&&(D.A=32)}}},RsM=function(J,W,H,D,Y,p,E){var Q=p[0],w=E[Q.getAttribute("p")];
if(w.rD===1){var k=p[1],K=p[2];p=p[3];Q.getAttribute("t");k.getAttribute("t");K.getAttribute("t");p.getAttribute("t");Q.getAttribute("p");k.getAttribute("p");p.getAttribute("p");E=E[K.getAttribute("p")];Q=LWe(Q.textContent,k.textContent,K.textContent,p.textContent,E);return new u_(J,W,Y,H,Q,D,w)}switch(w.rD){case 9:case 10:w.textEmphasis=1;break;case 11:w.textEmphasis=2;break;case 12:w.textEmphasis=3;break;case 13:w.textEmphasis=4;break;case 14:w.textEmphasis=5}return new u_(J,W,Y,H,Q.textContent||
"",D,w)},LWe=function(J,W,H,D,Y){var p=g.O1(),E=p?g.Ni("DIV"):g.Ni("RUBY"),Q=g.Ni("SPAN");
Q.textContent=J;E.appendChild(Q);J=p?g.Ni("DIV"):g.Ni("RP");J.textContent=W;E.appendChild(J);W=p?g.Ni("DIV"):g.Ni("RT");W.textContent=H;E.appendChild(W);H=Y.rD;if(H===10||H===11||H===12||H===13||H===14)if(g.oz(W,"text-emphasis-style","filled circle"),g.oz(W,"text-emphasis-color","currentcolor"),g.oz(W,"webkit-text-emphasis","filled circle"),Y.rD===11||Y.rD===13)g.oz(W,"webkit-text-emphasis-position","under left"),g.oz(W,"text-emphasis-position","under left");H=!0;if(Y.rD===4||Y.rD===7||Y.rD===12||
Y.rD===14)g.oz(E,"ruby-position","over"),g.oz(E,"-webkit-ruby-position","before");else if(Y.rD===5||Y.rD===6||Y.rD===11||Y.rD===13)g.oz(E,"ruby-position","under"),g.oz(E,"-webkit-ruby-position","after"),H=!1;Y=p?g.Ni("DIV"):g.Ni("RP");Y.textContent=D;E.appendChild(Y);p&&(D=H,g.oz(E,{display:"inline-block",position:"relative"}),p=E.firstElementChild.nextElementSibling,g.oz(p,"display","none"),p=p.nextElementSibling,g.oz(p,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.oz(E.lastElementChild,"display","none"),D?(g.oz(E,"padding-top","0.6em"),g.oz(p,"top","0")):(g.oz(E,"padding-bottom","0.6em"),g.oz(p,"bottom","0")));return E},dMo=function(J){var W="_"+s8++;
return new G7(0,0x8000000000000,0,W,J)},qJ=function(J,W){J=J.getAttribute(W);
if(J!=null)return Number(J)},ne=function(J,W){J=J.getAttribute(W);
if(J!=null)return J==="1"},l_=function(J,W){J=qJ(J,W);
return J!==void 0?J:null},hg=function(J,W){J=J.getAttribute(W);
if(J!=null)return yW.test(J),J},v0e=function(J,W){var H={},D=W.getAttribute("ws");
Object.assign(H,D?J.K[D]:J.V);J=l_(W,"mh");J!=null&&(H.oN=J);J=l_(W,"ju");J!=null&&(H.textAlign=J);J=l_(W,"pd");J!=null&&(H.wN=J);J=l_(W,"sd");J!=null&&(H.Gw=J);J=hg(W,"wfc");J!=null&&(H.windowColor=J);W=qJ(W,"wfo");W!==void 0&&(H.windowOpacity=W/255);return H},FWV=function(J,W){var H={},D=W.getAttribute("wp");
D&&Object.assign(H,J.B[D]);J=l_(W,"ap");J!=null&&(H.zm=J);J=qJ(W,"cc");J!=null&&(H.GJ=J);J=qJ(W,"ah");J!=null&&(H.V7=J);J=qJ(W,"rc");J!=null&&(H.Mt=J);W=qJ(W,"av");W!=null&&(H.i6=W);return H},BKS=function(J,W,H,D){var Y={};
Object.assign(Y,FWV(J,W));Object.assign(Y,v0e(J,W));D?g.w8(Y,J.V)?(D=J.Z,Y=J.V):D="_"+s8++:D=W.getAttribute("id")||"_"+s8++;J=qJ(W,"t")+H;W=qJ(W,"d")||0x8000000000000;if(Y.wN===2||Y.wN===3)H=Y.Mt,Y.Mt=Y.GJ,Y.GJ=H;return new G7(J,W,0,D,Y)},i_=function(J){J=g.qj(Math.round(J),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-J.length)+J},TKw=function(J,W,H,D,Y){D===0&&(D=0x8000000000000);
var p={};W.wpWinPosId&&Object.assign(p,J.V.get(W.wpWinPosId));W.wsWinStyleId&&Object.assign(p,J.Z.get(W.wsWinStyleId));J=W.rcRowCount;J!==void 0&&(p.Mt=J);W=W.ccColCount;W!==void 0&&(p.GJ=W);if(p.wN===2||p.wN===3)W=p.Mt,p.Mt=p.GJ,p.GJ=W;return new G7(H,D,0,Y,p)},Ii=function(J){var W=J.byteOffset;
J.byteOffset+=1;return J.C.getUint8(W)},XO=function(J){var W=J.byteOffset;
J.byteOffset+=4;return J.C.getUint32(W)},Jst=function(J){if(typeof J==="string")return!1;
J=new ch2(J,0);return o02(J)},o02=function(J){if(!(J.byteOffset<J.C.byteLength)||XO(J)!==1380139777)return!1;
J.version=Ii(J);if(J.version>1)return!1;Ii(J);Ii(J);Ii(J);return!0},W0e=function(J,W){if(!W)return"";
J.D&&J.Y.params.Gw!==1&&(W*=-1);return`translate${J.D?"X":"Y"}(${W}px)`},H$t=function(J){J.Tl=Array.from(J.element.getElementsByClassName("caption-visual-line"));
for(var W=J.Y.params.Mt,H=0,D=0,Y=J.Tl.length-1;H<W&&Y>-1;){var p=J.Tl[Y];D+=J.D?p.offsetWidth:p.offsetHeight;H++;Y--}J.zl=D;W=Math;H=W.max;isNaN(J.yY)&&((D=J.C.GJ)?(Y=g.Ni("SPAN"),g.X4(Y,"\u2013".repeat(D)),g.oz(Y,UMw(J,J.C.PZ)),J.Z.appendChild(Y),J.yY=Y.offsetWidth,J.Z.removeChild(Y)):J.yY=0);D=J.Z;J.tR=H.call(W,J.yY,J.XO,(J.D?D.offsetHeight:D.offsetWidth)+1)},DaW=function(J,W){H$t(J);
var H=J.Tl.reduce((D,Y)=>(J.D?Y.offsetWidth:Y.offsetHeight)+D,0);
H=J.zl-H;if(H!==J.j$){let D=H>0&&J.j$===0,Y=H<J.j$;W||isNaN(H)||D||!Y||(g.en(J.element,"ytp-rollup-mode"),J.O(J.element,"transitionend",J.Ff));g.oz(J.Z,"transform",W0e(J,H));J.j$=H}H$t(J)},pkt=function(J,W,H,D){var {formatId:Y,
DU:p,startTimeMs:E,durationMs:Q}=J.X(W),w={formatId:Y,startTimeMs:E,durationMs:Q,Cr:p,yu:p},k=YTL(J.Bi,w.startTimeMs),K=k>=0?J.Bi[k]:null,r=K?K.startTimeMs+K.durationMs:0,C=w.startTimeMs+w.durationMs;!K||w.startTimeMs-r>J.V?J.Bi.splice(k+1,0,w):(K.durationMs=Math.max(r,C)-K.startTimeMs,K.yu=Math.max(K.yu,w.yu));D(J.Bi);D=g.qe(W);J=J.Z;D=D.buffer.slice(D.byteOffset,D.byteLength+D.byteOffset);W=W.info.V;J.IB?J.B==null?g.uH(J.logger,350058965,"Null loaded track meta data at captions data received"):
H.Y8(D,J.B,W*1E3):g.uH(J.logger,350058965,"Null Representation at captions data received")},wko=function(J,W){J.A=(H,D)=>{if(J.J.j().experiments.W4("html5_sabr_live_support_subfragmented_captions"))(J.C?J.C=J.C.Z(H):(J.C=H,ECM(J.C)),J.C)?H.info.hX&&(QOM(J.C),pkt(J,J.C,W,D),J.C=null):g.uH(J.logger,350058965,"Empty slice");
else if(H.info.hX){var Y=H;if(J.Rw.length>0){for(Y=J.Rw.shift();J.Rw.length>0;)Y=Y?.Z(J.Rw.shift());Y=Y?.Z(H)}Y?(ECM(Y),QOM(Y),pkt(J,Y,W,D)):g.uH(J.logger,350058965,"Empty slice")}else J.Rw.push(H)};
J.J.addEventListener("sabrCaptionsDataLoaded",J.A)},YTL=function(J,W){J=g.Dg(J,{startTimeMs:W},(H,D)=>H.startTimeMs-D.startTimeMs);
return J>=0?J:-J-2},ECM=function(J){try{var W=g.hX(J)*1E3}catch(H){W=J.info.segmentStartTime*1E3}W<0&&(W=J.info.segmentStartTime*1E3);
J.info.segmentStartTime=W/1E3;J.info.V=W/1E3},QOM=function(J){try{var W=g.RQ(J)*1E3}catch(H){W=J.info.Y*1E3}W<0&&(W=J.info.Y*1E3);
J.info.Y=W/1E3;J.info.X=W/1E3},Z$2=function(J,W){if(!g.yO(J)||J.C!=null&&g.Gz(W,J.C)&&J.C.C.rawcc!=null)return!1;
W=!!J.C&&J.C.isManifestless&&Object.values(J.C.C).some(H=>g.qz(H,"386"));
J=!!J.C&&!J.C.isManifestless&&g.r5(J.C);return W||J},MoX=function(J,W,H){var D=[];
for(let Y in J.A.C){if(!J.A.C.hasOwnProperty(Y))continue;let p=J.A.C[Y];if(g.qz(p,H||null)){let E=p.info.captionTrack;E&&E.languageCode===W&&D.push(p)}}return D.length?D[0]:null},ajX=function(J,W){var H=[];
for(let Y in J.A.C){if(!J.A.C.hasOwnProperty(Y))continue;var D=J.A.C[Y];if(g.qz(D,W||null)){let p=D.info.id,E=p,Q=`.${p}`,w="",k="";if(D=D.info.captionTrack)p=D.languageCode,E=D.displayName,Q=D.vssId,w=D.kind,k=D.id;H.push(new g.Fm({id:Y,languageCode:p,languageName:E,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:Q,kind:w,captionId:k}))}}return H},b$S=function(J){var W=k3W.length;
if(J.byteLength<W)return!1;J=new Uint8Array(J,0,W);for(let H=0;H<W;H++)if(k3W[H]!==J[H])return!1;return!0},Le=function(J){J=J.split(":");
var W=0;for(let H of J)W=W*60+Number(H);return W*1E3},K0W=function(J,W,H,D){D=Object.assign({oN:0},D);
return new G7(J,W,H,"_"+s8++,D)},rsw=function(J,W,H,D,Y,p,E,Q,w){switch(E.tagName){case "b":Q.bold=!0;
break;case "i":Q.italic=!0;break;case "u":Q.underline=!0}for(let K=0;K<E.childNodes.length;K++){var k=E.childNodes[K];if(k.nodeType===3)k=new u_(W,H,D,Y.id,k.nodeValue,p||K>0,g.px(Q)?void 0:Q),w.push(k),Y.C.push(k);else{let r={};Object.assign(r,Q);rsw(J,W,H,D,Y,!0,k,r,w)}}},$aW=function(J,W,H){if(typeof W==="string"||Jst(W))return[{trackData:W,
He:H}];if(typeof W==="string"&&W.substring(0,6)==="WEBVTT"||typeof W!=="string"&&b$S(W))return[{trackData:W,He:H}];var D=new DataView(W);if(D.byteLength<=8||D.getUint32(4)!==1718909296)return[];var Y=g.ah(D);if(J.L9&&Y){var p=g.dY(Y),E=g.vy(Y);Y=Y.segmentNumber;p&&Y&&J.L9.H5(Y,p,E)}J=g.wt(D,1835295092);if(!J||!J.length||!J[0].size)return[];p=[];for(E=0;E<J.length;E++)Y=J[E],Y=new Uint8Array(W,Y.dataOffset,Y.size-(Y.dataOffset-Y.offset)),Y=g.eE(Y),p.push({trackData:Y,He:H+E*1E3});fjt(D,p,H);return p=
p.filter(Q=>!!Q.trackData)},gC2=function(J,W,H){J.C||(J.C=new STW);
J=J.C.Y(W,H);Math.random()<.01&&g.cP(Error("Deprecated subtitles format in web player: WebVTT"));return J},fjt=function(J,W,H){var D=g.o4(J,0,1836476516),Y=9E4;
D&&(Y=g.HA(D)||9E4);D=0;var p=g.wt(J,1836019558);for(let Q=0;Q<p.length;Q++){var E=p[Q];Q<W.length&&(E=g.o4(J,E.dataOffset,1953653094))&&(E=g.o4(J,E.dataOffset,1952867444))&&(E=g.E6(E)/Y*1E3,Q===0&&(D=E),W[Q].He=E-D+H||H*Q*1E3)}},CsS=function(J){var W={};
if(J=g.ca(J))W.lang=J,g.OSw.test(J)&&(W.wN=1);return W},Ri=function(J){return J.Y==="HLS"&&J.kQ?!0:J.u9&&J.kQ&&J.Y!=="LIVE"&&J.Y!=="SABR_LIVE"},elt=function(J){return!J.V&&J.u9&&J.dP&&(J.Y==="LIVE"||J.Y==="SABR_LIVE")},dX=function(J,W,H=!1){var D=J.W.L("enable_player_captions_new_style_defaults")?AsL:maL,Y=D.PZ;
J.Z={};Object.assign(J.Z,D);J.Z.PZ={};Object.assign(J.Z.PZ,Y);J.D={PZ:{}};var p=W.backgroundOverride?J.D:J.Z,E=W.background||Y.background;yW.test(E);p.PZ.background=E;p=W.colorOverride?J.D:J.Z;E=W.color||Y.color;yW.test(E);p.PZ.color=E;p=W.windowColorOverride?J.D:J.Z;E=W.windowColor||D.windowColor;yW.test(E);p.windowColor=E;p=W.backgroundOpacityOverride?J.D:J.Z;E=W.backgroundOpacity;E==null&&(E=Y.backgroundOpacity);p.PZ.backgroundOpacity=E;p=W.fontSizeIncrementOverride?J.D:J.Z;E=W.fontSizeIncrement;
E==null&&(E=Y.fontSizeIncrement);p.PZ.fontSizeIncrement=E;E=W.fontStyleOverride?J.D:J.Z;p=W.fontStyle;p==null&&(p=Y.bold&&Y.italic?3:Y.bold?1:Y.italic?2:0);E=E.PZ;switch(p){case 1:E.bold=!0;delete E.italic;break;case 2:delete E.bold;E.italic=!0;break;case 3:E.bold=!0;E.italic=!0;break;default:delete E.bold,delete E.italic}p=W.textOpacityOverride?J.D:J.Z;E=W.textOpacity;E==null&&(E=Y.textOpacity);p.PZ.textOpacity=E;p=W.windowOpacityOverride?J.D:J.Z;E=W.windowOpacity;E==null&&(E=D.windowOpacity);p.windowOpacity=
E;D=W.charEdgeStyleOverride?J.D:J.Z;p=W.charEdgeStyle;p==null&&(p=Y.charEdgeStyle);D.PZ.charEdgeStyle=p;D=W.fontFamilyOverride?J.D:J.Z;p=W.fontFamily;p==null&&(p=Y.fontFamily);D.PZ.fontFamily=p;J.loaded&&J.hR();H&&g.$_("yt-player-caption-display-settings",W,2592E3)},vF=function(J,W,H){W&&!J.N?(W=dMo({wN:0,
lang:"ru"}),J.N=[W,new u_(W.start,W.end-W.start,0,W.id,H??"\u0421\u0443\u0431\u0442\u0438\u0442\u0440\u044b \u0431\u0443\u0434\u0443\u0442 \u0432\u044b\u0433\u043b\u044f\u0434\u0435\u0442\u044c \u0442\u0430\u043a")],J.player.FB(J.N)):!W&&J.N&&(O$p(J,J.N),J.N=null)},Uat=function(J){if(J.W.L("enable_player_captions_persistence_state_machine")){var W=g.gS("yt-player-caption-persistence");
if(W==null){let H=g.js().pa(65);if(H===!0)W=!1;else{let D=g.kB(J.W)?FO(J):jO2(J);D!=null?W=!!D:H===!1&&(W=!0)}W!==void 0&&BF(J,W)}return W}},FO=function(J){if(!J.J.isInline())return g.gS("yt-player-sticky-caption")},jO2=function(J){if(!J.storage)return null;
try{var W=J.storage.get("module-enabled")}catch(H){J.storage.remove("module-enabled")}return W},T7=function(J){if(J.W.L("enable_player_captions_persistence_state_machine"))return Uat(J);
var W=void 0,H=g.js().pa(65);if(g.kB(J.W)&&H!=null){if(FO(J)!=null)return!1;W=!H}return W},PsX=function(J){if(J.W.PS===1||J.videoData.Gx===1||g.ta(J.videoData,"yt:cc")==="alwayson")return!0;
if(J.videoData.captionTracks.length)var W=J.getAudioTrack().A;if(J.W.L("enable_player_captions_persistence_state_machine")){var H=Uat(J);if(H!==void 0)return!!H}else if(J.W.PS===2&&(g.kB(J.W)?H=FO(J):H=jO2(J),H!=null))return!!H;H=e5(J.player.getAudioTrack(),g.kB(J.W));var D=g.ta(J.videoData,"yt:cc");if(T7(J)===void 0){if(H==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return D?D==="on":!0;if(H==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return D==="on"}else return D==="on";return W==="ON"||g.ta(J.videoData,
"yt:cc")==="on"},cF=function(J,W=!1){if(J.A&&!W||!J.videoData.captionTracks.length)return!1;
J=J.getAudioTrack();return!!J.C||J.A==="FORCED_ON"},toV=function(J){return J.W.L("html5_honor_caption_availabilities_in_audio_track")&&J.Y!=="LIVE"&&J.Y!=="SABR_LIVE"},xa2=function(J,W){if(J.A){var H=J.J.vC().BC().textTracks,D=null;
J.Y==="HLS"?D=J.A.getId():D=J.A.toString();for(let p=0;p<H.length;p++){var Y=H[p];Y.id===D&&(W?Y.mode!=="showing"&&(Y.mode="showing",Y=J.A,J.e0(Y,!!Y,oi(J)?"g":J.B?"m":"s")):Y.mode==="showing"&&(Y.mode="disabled"))}}},oi=function(J){var W=Jz(J);
return!!W&&J.A===W},zlW=function(J,W){if(J.Y==="HLS")return!1;
g.nC(J.videoData)&&(W=!0);W||(W=J.Y==="TTS"?!1:J.Y==="INNERTUBE"?!1:!0);return W||J.W.L("web_watch_disable_account_level_captions_settings")&&g.kB(J.W)?!0:!!g.js().pa(66)},Jz=function(J){return J.K&&J.K.C},W4=function(J,W){if(!J.C)return null;
if(J.K&&J.K.V)return J.K.V;W=zlW(J,W);W=J.C.C.C(W);var H=null;if(Zjt(J.W)){var D=J.J.isInline()?void 0:g.gS("yt-player-caption-sticky-language");var Y=[D,J.videoData.captionsLanguagePreference,J.W.captionsLanguagePreference,g.ta(J.videoData,"yt:cc_default_lang")];let Q=!1;for(let w=0;w<Y.length;w++){let k=Y[w];if(k){Q=!0;for(var p=0;p<W.length;p++)if(g.ca(W[p])===k)return W[p];for(p=0;p<W.length;p++)if(g.ca(W[p]).split("-")[0]===k.split("-")[0])return W[p]}}if(Q&&J.C&&(Y=J.C.K,Y.length))for(var E of Y)if(E.languageCode===
D){H=E;break}}else for(E=[J.videoData.captionsLanguagePreference,J.W.captionsLanguagePreference,g.ta(J.videoData,"yt:cc_default_lang")],D=0;D<E.length;D++)for(Y=0;Y<W.length;Y++)if(g.ca(W[Y])===E[D])return W[Y];E=null;J.K&&J.K.Y&&(E=J.K.Y);E||(E=W.find(Q=>Q.isDefault)||null);
E||(E=W[0]||Jz(J));E&&H&&g.ca(E).split("-")[0]!==H.languageCode.split("-")[0]&&(E=wte(E,H));return E},pM=function(J,W,H){J.loaded&&J.unload();
H!=null&&(J.B=H,J.B&&(J.W.L("enable_player_captions_persistence_state_machine")?BF(J,!!W):g.kB(J.W)?H4(J,!!W):Dk(J,!!W)));W!==null||cF(J,!0)||J.e0(W,!!W,J.B?"m":"s");J.A=W;cF(J)&&(J.A=Jz(J));YK(J,J.A??void 0);J.load()},BF=function(J,W){J.W.L("enable_player_captions_persistence_state_machine")&&g.$_("yt-player-caption-persistence",W,3122064E3)},H4=function(J,W){J.J.isInline()||g.$_("yt-player-sticky-caption",W,2592E3)},Dk=function(J,W){if(J.storage)try{J.storage.set("module-enabled",W)}catch(H){}},
YK=function(J,W){J.W.L("html5_modify_caption_vss_logging")&&(J.videoData.OT=W)},NuS=function(J,W){var H=J.tR[W.id];
H&&H.Y!==W&&(H.dispose(),delete J.tR[W.id],H=null);H||(H=Vo2(J,W))&&(J.tR[W.id]=H)},ukt=function(J,W){var H=W.windowId;
J.i9[H]||(J.i9[H]=[]);J.i9[H].push(W)},Vo2=function(J,W){var H=sOX(J);
if(!H)return null;var D=J.A?g.ca(J.A):null;D&&g.OSw.test(D)&&(W.params.wN=1);var Y=J.Ff.getPlayerSize();D=Y.height*J.zl.height;Y=Y.width*J.zl.width;J.W.playerStyle!=="google-live"||J.Z.isDefault||Object.assign(W.params,J.Z);switch(W.params.oN!=null?W.params.oN:W.C.length>1?1:0){case 1:return new G3S(W,J.Z,J.D,H.width,H.height,Y,D,J.W.experiments,J.gP.bind(J),J.J);case 2:return new qT2(W,J.Z,J.D,H.width,H.height,Y,D,J.W.experiments,J.gP.bind(J),J.J);default:return new EG(W,J.Z,J.D,H.width,H.height,
Y,D,J.W.experiments,J.gP.bind(J),J.J)}},sOX=function(J){var W=J.Ff.getVideoContentRect(!0).height,H=J.Ff.getVideoContentRect(!0).width;
if(!W||!H)return null;W*=J.zl.height;H*=J.zl.width;return{width:H,height:W}},O$p=function(J,W){J.player.dN(W);
for(let H of W)g.FH(J.Tl,H);gX(J.yY)},nCw=function(J,W){if(!J.C)return{};
if(W){g.px(W)||J.Um(W.vss_id,"m");if(J.V&&J.Y!=="HLS"||!g.gW(W))return;if(g.px(W)){pM(J,null,!0);return}let D;var H=J.C.C.C(!0);for(let Y=0;Y<H.length;Y++){let p=H[Y];p.languageCode!==W.languageCode||D&&(p.languageName!==W.languageName||(p.captionId||"")!==(W.captionId||"")||g.TB(p)!==W.displayName)||(D=W.translationLanguage?wte(p,W.translationLanguage):p)}J.FI(W.position);!D||D===J.A&&J.loaded||(W=g.Uc(),H=g.ca(D),W.length&&H===W[W.length-1]||(W.push(H),g.$_("yt-player-caption-language-preferences",
W)),Zjt(J.W)&&!J.J.isInline()&&g.$_("yt-player-caption-sticky-language",H,2592E3),pM(J,D,!0))}else return J.loaded&&J.A&&!oi(J)?Ce(J.A):{};return""};
g.t0.prototype.H5=g.HV(134,function(J,W,H){this.A.set(J,{Np:W,kO:H})});
g.x8.prototype.H5=g.HV(133,function(J,W,H){this.b9.H5(J,W,H)});
g.$k.prototype.B=g.HV(132,function(){this.mediaElement.B()});
g.bg.prototype.B=g.HV(131,function(){var J=g.g8(document,"track",void 0,this.C);for(let W=0;W<J.length;W++)g.iQ(J[W])});
g.$k.prototype.j$=g.HV(130,function(){return this.mediaElement.j$()});
g.bg.prototype.j$=g.HV(129,function(){return!(!this.C.textTracks||!this.C.textTracks.addEventListener)});
g.$k.prototype.i9=g.HV(128,function(){return this.mediaElement.i9()});
g.bg.prototype.i9=g.HV(127,function(){return!!this.C.textTracks});
g.$k.prototype.zl=g.HV(126,function(J){this.mediaElement.zl(J)});
g.bg.prototype.zl=g.HV(125,function(J){for(let W=0;W<J.length;W++)this.C.appendChild(J[W])});
g.J0.prototype.Um=g.HV(48,function(J,W){this.app.Gl().Um(J,W)});
g.d4.prototype.Um=g.HV(47,function(J,W){this.U.Um(J,W)});
g.ra.prototype.Um=g.HV(46,function(J,W){J=[J,W];g.Iq(this,g.Lw(this.provider),"cfi",J)});
g.S4.prototype.Um=g.HV(45,function(J,W){this.qoe&&this.qoe.Um(J,W)});
g.Rg.prototype.Um=g.HV(44,function(J,W){this.ag.Um(J,W)});
g.j4.prototype.Um=g.HV(43,function(){});
g.LT.prototype.Um=g.HV(42,function(J,W){g.g4(this,37,[J,W])});
g.J0.prototype.e0=g.HV(41,function(J,W,H){this.app.Gl().e0(J,W,H)});
g.d4.prototype.e0=g.HV(40,function(J,W,H){this.U.e0(J,W,H)});
g.ra.prototype.e0=g.HV(39,function(J,W,H){if(this.Mm!==J||this.NQ!==W)W=W==="rawcc"?"":W,H=[J,W,this.Mm,H],g.Iq(this,g.Lw(this.provider),"cfs",H),this.Mm=J,this.NQ=W});
g.S4.prototype.e0=g.HV(38,function(J,W,H){this.qoe&&this.qoe.e0(J,W,H)});
g.Rg.prototype.e0=g.HV(37,function(J,W,H){this.ag.e0(J,W,H)});
g.j4.prototype.e0=g.HV(36,function(){});
g.LT.prototype.e0=g.HV(35,function(J,W,H){g.g4(this,36,[J,W,H])});
g.oM.prototype.B1=g.HV(11,function(){return this.L9});
g.NY.prototype.B1=g.HV(10,function(){return this.Gl().D2()});
g.J0.prototype.D2=g.HV(9,function(){return this.app.B1()});
g.d4.prototype.D2=g.HV(8,function(){return this.U.D2()});
g.Rg.prototype.D2=g.HV(7,function(){return this.loader?.B1()||null});
g.j4.prototype.D2=g.HV(6,function(){return null});
g.LT.prototype.D2=g.HV(5,function(){return null});
g.lP.prototype.pM=g.HV(3,function(J){return(J=this.Y(J))?J.C:0});
g.h7.prototype.pM=g.HV(2,function(){return 0});
var bjW=/#(.)(.)(.)/,kge=/^#(?:[0-9a-f]{3}){1,2}$/i,ljt=class{constructor(){this.Y=[];this.A=[]}C(J){return J?this.A.concat(this.Y):this.A}},Qj=class extends g.RA{constructor(J){super();this.QY=J;this.C=new ljt;this.tR=new ljt;this.Z=null;this.K=[];this.zl=[]}X(){}V(){}Y(){}D(){return""}b9(){return!1}QE(J,W){if(this.QY.j().L("html5_dispatch_tracklist_loaded_event")){this.Z&&(this.Z.reject(),this.Z=null);var H=[];this.QY.Yk("trackListLoaded",this.C,H,W);this.QY.j().L("enable_po_decoration_of_forced_tracks")&&
this.QY.Yk("trackListLoaded",this.tR,H,W);H.length?(W=new g.AE,W.promise.then(J.QE,()=>{}),this.Z=W,Promise.all(H).then(W.resolve,W.reject).finally(()=>{this.Z=null})):J.QE()}else J.QE()}VY(){this.Z&&(this.Z.reject(),this.Z=null);
this.Y();super.VY()}},ysM={en:"English"},hl2=class extends Qj{constructor(J){super(J);this.A=new Set}V(J){var W=this.QY.vC();if(W&&W.BC()){W=W.BC().textTracks;for(let H of W)H.kind==="subtitles"&&!this.A.has(H.language)&&H.language&&(O8(this.C,new g.Fm({languageCode:H.language,languageName:H.language,kind:H.kind,id:H.id,displayName:ysM[H.label]||H.label,vss_id:`.${H.language}`})),this.A.add(H.language))}this.C.C().length>0&&J.QE()}},i$2=class extends Qj{constructor(J,W,H){super(J);this.videoData=
W;this.audioTrack=H;this.A=null;this.B=!1;this.K=W.Yq;this.zl=W.E1;this.B=g.nC(W)}X(J,W,H){this.F4();W=this.D(J,W);var D=this.QY.j().L("html5_report_captions_ctmp_qoe"),Y=(0,g.R)();this.Y();fQt(this,W,{format:"RAW",onSuccess:p=>{this.A=null;if(D){var E=(p.responseText.length/1024).toFixed();let Q=(0,g.R)();this.videoData.S("capresp",{ms:Q-Y,kb:E})}E=p.getResponseHeader&&p.getResponseHeader("Content-Length")?Number(p.getResponseHeader("Content-Length")):0;H.Y8(p.responseText,J,void 0,void 0,E)},
onError:D?p=>{this.videoData.S("capfail",{status:p?.status??0})}:void 0,
withCredentials:!0})}V(J){if(this.audioTrack){for(let W of this.audioTrack.captionTracks)O8(this.C,W);this.audioTrack.C&&O8(this.tR,this.audioTrack.C)}this.QE(J,this.videoData.videoId)}D(J,W){var H=J.Dq(),D={fmt:W};if(W==="srv3"||W==="3"||W==="json3")g.O1()?Object.assign(D,{xorb:2,xobt:1,xovt:1}):Object.assign(D,{xorb:2,xobt:3,xovt:3});J.translationLanguage&&(D.tlang=g.ca(J));this.B&&(D.xosf="1");Object.assign(D,this.QY.j().C);return g.P7(H,D)}Y(){this.A&&this.A.abort()}},Ij2=class{constructor(){this.segments=
[]}contains(J){J=g.Dg(this.segments,J);return J>=0||J<0&&(-J-1)%2===1}length(){return this.segments.length/2}},Xke=class extends g.RA{constructor(J,W,H,D,Y,p){super();this.policy=J;this.player=W;this.wl=H;this.B=D;this.Z=Y;this.IB=p;this.V=new Ij2;this.D=-1;this.A=this.Y=this.C=null;this.zl=0;this.X=new g.KA(this.K,1E3,this);this.events=new g.iP(this);g.n(this,this.X);g.n(this,this.events);this.events.O(W,"SEEK_COMPLETE",this.N);this.N();this.K()}VY(){super.VY();this.A&&this.A.cancel()}N(){this.seekTo(this.player.getCurrentTime())}seekTo(J){J-=
this.player.Rg();var W=this.C;this.C=g.ux(this.wl.X(J).JR);W!==this.C&&this.IB&&this.IB()}reset(){this.V=new Ij2;this.D=-1;this.A&&(this.A.cancel(),this.A=null)}K(){this.F4();var J;if(J=this.C!=null)J=this.C,J=J.wl.V(J);if(J&&!this.A&&!(this.C&&this.C.segmentStartTime-this.player.getCurrentTime()>30)){J=this.C;J=J.wl.u9(J);let Y=J.JR[0];if(this.player.getVideoData()?.enableServerStitchedDai){var W=this.player.D2();if(W){var H=Y.wl.info.id;let p=Y.DU;var D=J.JR[0].V;if(this.policy.yY){if(W=g.kxt(W,
D,p,H,3))J.V=W}else if(H=W.Vv(D,p,H,3))if(D=2,W.Ej.has(p)?D=0:g.y_(W,p)&&(D=1),W=D,W===0)H&&(J.C=new g.xd(H));else if(W===2){this.X.start();Sbe(this)&&this.seekTo(this.player.getCurrentTime());return}}}Y.wl.index.AT(Y.DU)?(this.V.contains(J.JR[0].DU)||g0t(this,J),this.C=g.ux(J.JR)):Sbe(this)&&this.seekTo(this.player.getCurrentTime())}this.X.start()}},L02=class extends Qj{constructor(J,W){super(W);this.A=J;this.J=W;this.B=null;this.N=!1;this.logger=new g.Ne("caps");this.IB=g.Gz(this.J,this.A)}X(J,
W,H){this.Y();W=Cbo(this,J.getId());W||(W=J.languageCode,W=this.A.isManifestless?est(this,W,"386"):est(this,W));if(W){var D=(W.index.pM(W.index.Oj())-W.index.getStartTime(W.index.Oj()))*1E3,Y=new g.cxX(this.J.j());this.B=new Xke(Y,this.J,W,(p,E)=>{H.Y8(p,J,E,D)},this.IB||g.Ih(W.info),()=>{this.B&&this.B.reset();
this.N=!0})}}b9(){var J=this.N;
this.N=!1;return J}V(J){var W=this.J.j().L("html5_fallback_if_rawcc_missing");var H=this.A.C.rawcc!=null;if(!this.IB||!H&&W)W=this.A.isManifestless?Aht(this,"386"):Aht(this);else{if(!H){g.uH(this.logger,386248249,"rawcc used but unavailable");return}W=[new g.Fm({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Fm({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(let D of W)O8(this.C,
D);J.QE()}Y(){this.B&&(this.B.dispose(),this.B=null)}D(){return""}},Rl2=class extends Qj{constructor(J,W,H,D,Y,p){super(J);this.videoId=H;this.N=Y;this.eventId=p;this.IB={};this.A=null;J=D||g.jJ(W).hl||"";J=J.split("_").join("-");this.B=g.P7(W,{hl:J})}X(J,W,H){this.F4();W=this.D(J,W);this.Y();this.A=g.c7(W,{format:"RAW",onSuccess:D=>{this.A=null;var Y=D.getResponseHeader&&D.getResponseHeader("Content-Length")?Number(D.getResponseHeader("Content-Length")):0;H.Y8(D.responseText,J,void 0,void 0,Y)},
withCredentials:!0})}V(J){var W=this.B,H={type:"list",tlangs:1,v:this.videoId,vssids:1};this.N&&(H.asrs=1);W=g.P7(W,H);this.Y();this.A=g.c7(W,{format:"RAW",onSuccess:D=>{this.A=null;if((D=D.responseXML)&&D.firstChild){var Y=D.getElementsByTagName("track");for(var p=0;p<Y.length;p++){var E=Y[p],Q=E.getAttribute("lang_code");let w=E.getAttribute("lang_translated"),k=E.getAttribute("name"),K=E.getAttribute("kind"),r=E.getAttribute("id"),C=E.getAttribute("lang_default")==="true",e=E.getAttribute("cantran")===
"true";E=E.getAttribute("vss_id");O8(this.C,new g.Fm({languageCode:Q,languageName:w,name:k,kind:K,id:r,is_servable:!0,is_translateable:e,vss_id:E,is_default:C}))}D=D.getElementsByTagName("target");Y=D.length;for(p=0;p<Y;p++)Q={languageCode:D[p].getAttribute("lang_code"),languageName:D[p].getAttribute("lang_translated"),languageOriginal:D[p].getAttribute("lang_original"),id:D[p].getAttribute("id"),isDefault:D[p].getAttribute("lang_default")==="true"},this.IB[Q.languageCode]=Q.languageName,this.K.push(Q)}this.QE(J,
this.videoId)},
withCredentials:!0})}D(J,W){var H=this.B;W={v:this.videoId,type:"track",lang:J.languageCode,name:J.getName(),kind:J.kind,fmt:W};var D=this.QY.j();D.L("captions_url_add_ei")&&(W.ei=this.eventId);J.translationLanguage&&(W.tlang=g.ca(J));Object.assign(W,D.C);return H=g.P7(H,W)}Y(){this.A&&this.A.abort()}},yW=/^#(?:[0-9a-f]{3}){1,2}$/i;var dao=["left","right","center","justify"];var u_=class extends g.Yv{constructor(J,W,H,D,Y,p=!1,E=null){super(J,J+W,{priority:H,namespace:"captions"});this.windowId=D;this.text=Y;this.append=p;this.C=E}toString(){return super.toString()}};var EG=class extends g.kD{constructor(J,W,H,D,Y,p,E,Q,w,k){var K=k.isInline()&&!0,r={};Object.assign(r,W);Object.assign(r,J.params);Object.assign(r,H);var C={};Object.assign(C,W.PZ);J.params.PZ&&Object.assign(C,J.params.PZ);Object.assign(C,H.PZ);K&&(r.windowOpacity=.6,C.backgroundOpacity=0);r.PZ=C;var e=r.wN===1,P=[{G:"span",AR:"captions-text",X4:{style:"word-wrap: normal; display: block;"}}],u=Q.W4("caption_edit_on_hover")&&k.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
u&&P.unshift({G:"button",AR:"caption-edit",X4:{tabindex:"0","aria-label":KWL()},ZU:[{G:"svg",X4:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},ZU:[{G:"path",X4:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({G:"div",AR:"caption-window",X4:{id:`caption-window-${J.id}`,dir:e?"rtl":"ltr",tabindex:"0",lang:r.lang},ZU:P});
this.experiments=Q;this.K=[];this.u9=!1;this.Y=J;this.i9=this.oB=null;this.SF=p;this.p_=E;this.X=null;this.maxWidth=p*.96;this.maxHeight=E*.96;this.C=r;this.BO=H;this.b9=W;this.Z=this.aB("captions-text");J=this.Z.style;this.Mm=Q.W4("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in J||"WebkitBoxDecorationBreak"in J);this.ix=Q.W4("web_player_misc_bugfix_b");this.Ka=mM2(D,Y,p,E);this.UJ=w;u&&(this.B=this.aB("caption-edit"),this.O(this.B,"click",()=>{this.UJ()}));
this.type=0;this.gP=this.Ka*Oj2(C);this.G5=K;this.dP=Q.W4("enable_centered_caption_for_tvfilm_video")&&k.getVideoData().isTvfilmVideo;this.IB=k.j().La().C.pa(g.Dy2);D=new g.e4(this.element,!0);g.n(this,D);D.subscribe("dragstart",this.j0,this);D.subscribe("dragmove",this.mH,this);D.subscribe("dragend",this.iZ,this);this.Qq=this.kQ=this.hg=this.lW=0;D="";this.C.windowOpacity&&(D=Ag(this.C.windowColor),D="rgba("+D[0]+","+D[1]+","+D[2]+","+this.C.windowOpacity+")");Y={"background-color":D,display:this.C.isVisible===
!1?"none":"","text-align":dao[this.C.textAlign]};this.Mm&&(Y["border-radius"]=D?`${this.gP*.25}px`:"");(this.D=this.Y.params.wN===2||this.Y.params.wN===3)&&j2V(this,this.element);g.oz(this.element,Y);K&&this.element.parentElement?.style.setProperty("--caption-window-color",D);switch(this.C.zm){case 0:case 1:case 2:g.en(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.en(this.element,"ytp-caption-window-bottom")}}j0(J,W){this.kQ=J;this.Qq=W;var H=g.wM(this.element,this.element.parentElement);
this.lW=J-H.x;this.hg=W-H.y}mH(J,W){if(J!==this.kQ||W!==this.Qq){g.CA(this.element,"ytp-dragging")||g.en(this.element,"ytp-dragging");var H=g.K5(this.element);J=J-this.lW-.02*this.SF;var D=W-this.hg-.02*this.p_,Y=(J+H.width/2)/this.maxWidth*3;Y=Math.floor(g.qj(Y,0,2));var p=(D+H.height/2)/this.maxHeight*3;p=Math.floor(g.qj(p,0,2));W=Y+p*3;J=(J+Y/2*H.width)/this.maxWidth;J=g.qj(J,0,1)*100;H=(D+p/2*H.height)/this.maxHeight;H=g.qj(H,0,1)*100;this.Y.params.zm=W;this.Y.params.i6=H;this.Y.params.V7=J;this.Y.params.isDefault=
!1;this.C.zm=W;this.C.i6=H;this.C.V7=J;this.C.isDefault=!1;this.b9.zm=W;this.b9.i6=H;this.b9.V7=J;this.b9.isDefault=!1;this.le()}}iZ(){g.mU(this.element,"ytp-dragging")}le(){this.N(this.K)}N(J){var W=this.G5?0:Math.min(this.tX(),this.maxWidth),H=this.NQ(),D=this.G5;if(D){var Y=getComputedStyle(this.Z.parentNode);Y=U8(Y.borderLeftWidth)+U8(Y.borderRightWidth)+U8(Y.paddingLeft)+U8(Y.paddingRight)}else Y=0;var p=Y;Y="";this.Y.params.wN===3&&(Y="rotate(180deg)");var E=D?`calc(96% - ${p}px)`:"96%";g.oz(this.element,
{top:0,left:0,right:"",bottom:"",width:W?`${W}px`:"",height:H?`${H}px`:"","max-width":E,"max-height":E,margin:"",transform:""});this.hR(J);Y={transform:Y,top:"",left:"",width:W?`${W}px`:"",height:H?`${H}px`:"","max-width":"","max-height":""};E=this.C.zm;var Q=this.C.V7,w=this.C.i6;this.dP&&E!=null&&(Q=50,E=Math.floor(E/3)*3+1);Q=Q*.96+2;switch(E){case 0:case 3:case 6:(D=this.C.PZ.fontSizeIncrement)&&D>0&&this.C.wN!==2&&this.C.wN!==3&&(Q=Math.max(Q/(1+D*2),2));Y.left=`${Q}%`;break;case 1:case 4:case 7:Y.left=
`${Q}%`;Q=0;this.IB||(Q=this.Z.offsetWidth);W||Q?(W=W||Q+1,Y.width=`${W}px`,Y["margin-left"]=D?`${W/-2-p/2}px`:`${W/-2}px`):(this.IB&&(Y.width="max-content"),Y.transform+=" translateX(-50%)");break;case 2:case 5:case 8:Y.right=`${100-Q}%`}D=w*.96+2;switch(E){case 0:case 1:case 2:Y.top=`${D}%`;break;case 3:case 4:case 5:Y.top=`${D}%`;D=0;this.IB||(D=this.element.clientHeight);(H=H||D)?(Y.height=`${H}px`,Y["margin-top"]=`${H/-2}px`):Y.transform+=" translateY(-50%)";break;case 6:case 7:case 8:Y.bottom=
`${100-D}%`}g.oz(this.element,Y);this.B&&(this.IB?H=this.gP:(J=PbL(this,J),H=this.dP?J>0?this.Z.offsetHeight/J:0:this.Z.offsetHeight/J),this.B.style.height=`${H}px`,this.B.style.width=`${H}px`,this.element.style.paddingLeft=`${H+5}px`,this.element.style.paddingRight=`${H+5}px`,this.IB||(J=Number(this.element.style.marginLeft.replace("px",""))-H-5,H=Number(this.element.style.marginRight.replace("px",""))-H-5,this.element.style.marginLeft=`${J}px`,this.element.style.marginRight=`${H}px`))}hR(J){if(this.type===
0&&this.Y.params.Mt!==void 0&&this.experiments.W4("web_enable_popon_asr_captions")){var W=J,H=this.Y.params.Mt;if(W.length===0||H<=0)J=[];else{J=[];for(let Y=W.length-1;Y>=0;Y--){var D=W[Y];J.unshift(D);let p=PbL(this,J);if(p>H){J.shift();typeof D.text==="string"&&(W=D.text.split("\n"),H=p-H,W.length-H>0&&(H=W.slice(H),D=new u_(D.start,D.end-D.start,D.priority||0,D.windowId,H.join("\n"),D.append,D.C),J.unshift(D)));break}}}}for(D=0;D<J.length&&J[D]===this.K[D];D++);if(this.u9||this.K.length>D)D=0,
this.u9=!1,this.K=[],this.X=this.i9=this.oB=null,g.s9(this.Z);for(;D<J.length;D++)zse(this,J[D])}tX(){return 0}NQ(){return 0}toString(){return super.toString()}};var F0X=class{constructor(){this.Y=this.time=this.mode=this.A=0;this.V=new vC2(this);this.Z=new vC2(this);this.C=[];this.clear()}clear(){this.Y=this.time=this.mode=0;this.C=[];this.reset()}reset(){this.mode=0;this.V.reset(0);this.Z.reset(1)}},Vce=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],But=class{constructor(){this.type=0}set(J){this.type=J}get(){return this.type}},Tue=class{constructor(){this.state=this.ot=this.Q_=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}z9(){return this.state!==0}matches(J,W){return this.z9()&&J===this.Q_&&W===this.ot}},csW=class{constructor(){this.timestamp=this.C=0}reset(){this.timestamp=
this.C=0}},wG=class{constructor(J){this.Z=J;this.Y=[];this.C=this.A=this.row=0;this.style=new But;this.V=0;for(J=0;J<=15;J++){this.Y[J]=[];for(let W=0;W<=32;W++)this.Y[J][W]=new csW}}updateTime(J){for(let W=1;W<=15;++W)for(let H=1;H<=32;++H)this.Y[W][H].timestamp=J}debugString(){var J="\n";for(let W=1;W<=15;++W){for(let H=1;H<=32;++H){let D=this.Y[W][H];J=D.C===0?J+"_":J+String.fromCharCode(D.C)}J+="\n"}return J}reset(J){for(let W=0;W<=15;W++)for(let H=0;H<=32;H++)this.Y[W][H].reset();this.V=J;this.C=
0;this.A=this.row=1}},qbS=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],n0M=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],lQt=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,
199,200,202,203,235,206,207,239,212,217,249,219,171,187],yh2=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],oCe=class{constructor(J){this.Y=J;this.Z=0;this.style=new But;this.D=new wG(this.Y);this.X=new wG(this.Y);this.text=new wG(this.Y);this.A=this.D;this.V=this.X;this.C=this.A}reset(J,W){this.Z=W;this.style.set(2);this.A=this.D;this.V=this.X;this.C=this.A;var H=(J<<2)+(W<<1);this.D.reset(H);this.X.reset(H);this.text.reset((J<<
2)+(W<<1)+1)}},vC2=class{constructor(J){this.C=J;this.Z=0;this.Y=new oCe(this.C);this.D=new oCe(this.C);this.A=new Tue;this.V=this.Y}reset(J){this.Z=J;this.A.clear();this.V=this.Y;this.Y.reset(J,0);this.D.reset(J,1)}};var JbM=class{V(){}};var Zk=class extends g.RA{reset(){}};var G7=class extends g.Yv{constructor(J,W,H,D,Y){super(J,J+W,{priority:H,namespace:"captions"});this.id=D;this.params=Y;this.C=[]}toString(){return super.toString()}},s8=0;var WuV=class extends Zk{constructor(J){super();this.V=J;this.pens={};this.B={};this.K={};this.Z="_"+s8++;this.X={};this.A=this.C=null;this.D=!0}reset(){this.X={};this.A=this.C=null;this.D=!0}Y(J,W){J=J.firstChild;J.getAttribute("format");W=W||0;Number.isFinite(W);J=Array.from(J.childNodes);for(var H of J)if(H.nodeType===1)switch(H.tagName){case "head":var D=H;break;case "body":var Y=H}if(D){D=Array.from(D.childNodes);for(var p of D)if(p.nodeType===1)switch(p.tagName){case "pen":H=p.getAttribute("id");
D=this.pens;J={};var E=p.getAttribute("p");E&&Object.assign(J,this.pens[E]);E=ne(p,"b");E!=null&&(J.bold=E);E=ne(p,"i");E!=null&&(J.italic=E);E=ne(p,"u");E!=null&&(J.underline=E);E=l_(p,"et");E!=null&&(J.charEdgeStyle=E);E=l_(p,"of");E!=null&&(J.offset=E);E=hg(p,"bc");E!=null&&(J.background=E);E=hg(p,"ec");E!=null&&(J.hp=E);E=hg(p,"fc");E!=null&&(J.color=E);E=l_(p,"fs");E!=null&&E!==0&&(J.fontFamily=E);E=qJ(p,"sz");E!==void 0&&(J.fontSizeIncrement=E/100-1);E=qJ(p,"bo");E!==void 0&&(J.backgroundOpacity=
E/255);E=qJ(p,"fo");E!==void 0&&(J.textOpacity=E/255);E=l_(p,"rb");E!=null&&E!==10&&E!==0&&(J.rD=E>10?E-1:E);E=l_(p,"hg");E!=null&&(J.eB=E);D[H]=J;break;case "ws":D=p.getAttribute("id");this.K[D]=v0e(this,p);break;case "wp":D=p.getAttribute("id"),this.B[D]=FWV(this,p)}}if(Y){p=[];Y=Array.from(Y.childNodes);for(u of Y)if(u.nodeType===1)switch(u.tagName){case "w":this.C=BKS(this,u,W,!1);(Y=this.X[this.C.id])&&Y.end>this.C.start&&(Y.end=this.C.start);this.X[this.C.id]=this.C;p.push(this.C);break;case "p":var Q=
u;J=W;Y=[];D=Q.getAttribute("w")||this.Z;H=!!ne(Q,"a");J=(qJ(Q,"t")||0)+J;E=qJ(Q,"d")||5E3;H||(!this.D&&this.A&&this.A.windowId===D&&this.A.end>J&&(this.A.end=J),this.A&&this.A.text==="\n"&&(this.A.text=""));let h=H?6:5;var w=Q.getAttribute("p");w=w?this.pens[w]:null;let y=Array.from(Q.childNodes);y.length&&(this.D=Q.getAttribute("d")!=null);for(Q=0;Q<y.length;Q++){var k=y[Q],K=void 0;Q>0&&(H=!0);let X;k.nodeType===1&&(X=k);if(X&&X.tagName==="s"){if((k=(k=X.getAttribute("p"))?this.pens[k]:null)&&
k.rD&&(k.rD===1?(k=y.slice(Q,Q+4),k.length===4&&(K=RsM(J,E,D,H,h,k,this.pens),Q+=3)):K=RsM(J,E,D,H,h,[X],this.pens)),!K){var r=X;K=J;k=E;var C=D,e=H;let F=r.textContent?r.textContent:"";var P=r.getAttribute("p");P=P?this.pens[P]:null;r=qJ(r,"t")||0;K=new u_(K+r,k-r,h,C,F,e,P)}}else K=new u_(J,E,h,D,k.textContent||"",H,w);Y.push(K);this.A=K}if(Y.length>0){Y[0].windowId===this.Z&&(this.C=BKS(this,u,W,!0),p.push(this.C));for(let X of Y)X.windowId=this.C.id,this.C.C.push(X),p.push(X)}}var u=p}else u=
[];return u}};var H3S=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),f2t=class extends Zk{constructor(J){super();this.D=J;this.C=new Map;this.V=new Map;this.Z=new Map;this.A=new Map}reset(){this.A.clear()}Y(J,W){J=JSON.parse(J);if(!J)return[];if(J.pens){var H=J.pens,D=0;for(var Y of H){H={};var p=Y.pParentId;p&&Object.assign(H,this.C.get(p));Y.bAttr&&(H.bold=!0);Y.iAttr&&(H.italic=!0);Y.uAttr&&(H.underline=!0);p=Y.ofOffset;p!=null&&(H.offset=p);Y.szPenSize!==void 0&&(H.fontSizeIncrement=Y.szPenSize/100-1);
p=Y.etEdgeType;p!=null&&(H.charEdgeStyle=p);Y.ecEdgeColor!==void 0&&(H.hp=i_(Y.ecEdgeColor));p=Y.fsFontStyle;p!=null&&p!==0&&(H.fontFamily=p);Y.fcForeColor!==void 0&&(H.color=i_(Y.fcForeColor));Y.foForeAlpha!==void 0&&(H.textOpacity=Y.foForeAlpha/255);Y.bcBackColor!==void 0&&(H.background=i_(Y.bcBackColor));Y.boBackAlpha!==void 0&&(H.backgroundOpacity=Y.boBackAlpha/255);(p=Y.rbRuby)&&p!==10&&(H.rD=p>10?p-1:p,H.textEmphasis=H3S.get(H.rD));Y.hgHorizGroup&&(H.eB=Y.hgHorizGroup);this.C.set(D++,H)}}if(J.wsWinStyles){D=
J.wsWinStyles;Y=0;for(var E of D)D={},(H=E.wsParentId)?Object.assign(D,this.Z.get(H)):Object.assign(D,this.D),E.mhModeHint!==void 0&&(D.oN=E.mhModeHint),E.juJustifCode!==void 0&&(D.textAlign=E.juJustifCode),E.pdPrintDir!==void 0&&(D.wN=E.pdPrintDir),E.sdScrollDir!==void 0&&(D.Gw=E.sdScrollDir),E.wfcWinFillColor!==void 0&&(D.windowColor=i_(E.wfcWinFillColor)),E.wfoWinFillAlpha!==void 0&&(D.windowOpacity=E.wfoWinFillAlpha/255),this.Z.set(Y++,D)}if(J.wpWinPositions){Y=J.wpWinPositions;E=0;for(var Q of Y)Y=
{},(D=Q.wpParentId)&&Object.assign(Y,this.V.get(D)),Q.ahHorPos!==void 0&&(Y.V7=Q.ahHorPos),Q.apPoint!==void 0&&(Y.zm=Q.apPoint),Q.avVerPos!==void 0&&(Y.i6=Q.avVerPos),Q.ccCols!==void 0&&(Y.GJ=Q.ccCols),Q.rcRows!==void 0&&(Y.Mt=Q.rcRows),this.V.set(E++,Y)}if(J.events){J=J.events;Q=[];for(let T of J)if(E=(T.tStartMs||0)+W,Y=T.dDurationMs||0,T.id)D=String(T.id),J=TKw(this,T,E,Y,D),Q.push(J),this.A.set(D,J);else{T.wWinId?D=T.wWinId.toString():(D="_"+s8++,J=TKw(this,T,E,Y,D),Q.push(J),this.A.set(D,J));
J=Q;var w=T;Y===0&&(Y=5E3);H=this.A.get(D);let Qt=(p=!!w.aAppend)?6:5,ke=w.segs,A2=null;w.pPenId&&(A2=this.C.get(w.pPenId));for(w=0;w<ke.length;w++){var k=ke[w],K=k.utf8;if(K){var r=k.tOffsetMs||0;let xe=null;k.pPenId&&(xe=this.C.get(k.pPenId));if((H.params.oN!=null?H.params.oN:H.C.length>1?1:0)===2&&p&&K==="\n")continue;k=null;var C=[],e;if(e=xe&&xe.rD===1)a:{e=ke;var P=w;if(P+3>=e.length||!e[P+1].pPenId||!e[P+2].pPenId||!e[P+3].pPenId){e=!1;break a}var u=e[P+1].pPenId;(u=this.C.get(u))&&u.rD&&u.rD===
2?(u=e[P+2].pPenId,u=this.C.get(u),!u||!u.rD||u.rD<3?e=!1:(u=e[P+3].pPenId,e=(u=this.C.get(u))&&u.rD&&u.rD===2?!0:!1)):e=!1}if(e)r=ke[w+1].utf8,k=ke[w+3].utf8,e=ke[w+2].utf8,P=this.C.get(ke[w+2].pPenId),K=LWe(K,r,e,k,P),k=new u_(E,Y,Qt,D,K,p,xe),w+=3;else{if(K.indexOf("<")>-1){C=xe;e=A2;P=E;u=Y;var h=r,y=Qt,X=p;let BV=[];var F=j5(`<html>${K}</html>`);if(!F.getElementsByTagName("parsererror").length&&F.firstChild?.childNodes.length)for(let Ft of F.firstChild.childNodes){F=Ft.textContent?.replace(/\n/g,
"")??"";if(Ft.nodeType===3&&(!F||F.match(/^ *$/)!=null))continue;let XH={};Object.assign(XH,C||e);switch(Ft?.tagName){case "b":XH.bold=!0;break;case "i":XH.italic=!0;break;case "u":XH.underline=!0}BV.push(new u_(P+h,u-h,y,H.id,F,X,XH))}C=BV}C.length||(C=[new u_(E+r,Y-r,Qt,H.id,K,p,xe||A2)])}if(C.length)for(let BV of C)J.push(BV),H.C.push(BV);else k&&(J.push(k),H.C.push(k))}p=!0}}W=Q}else W=[];return W}};var $22=class extends Qj{constructor(J,W,H){super(J);this.videoData=W;this.audioTrack=H;this.K=W.Yq}X(J,W,H){aQ2(this.videoData.videoId,J.vssId,H.Y8)}V(J){if(this.audioTrack)for(let W of this.audioTrack.captionTracks)O8(this.C,W);J.QE()}};var G3S=class extends EG{constructor(J,W,H,D,Y,p,E,Q,w,k){super(J,W,H,D,Y,p,E,Q,w,k);this.type=1}hR(J){var W=this.Y.C;super.hR(J);for(J=J.length;J<W.length;J++){let Y=W[J],p;if(D&&Y.C===H)p=D;else{p={};Object.assign(p,Y.C);Object.assign(p,SSt);var H=Y.C;var D=p}zse(this,Y,p)}}},SSt={R$:!0};var ch2=class extends JbM{constructor(J,W){super();this.trackData=J;this.D=W;this.version=this.Z=this.Y=this.byteOffset=0;this.A=[];this.C=new DataView(this.trackData)}V(J,W,H,D,Y){if(H<D){let p="_"+s8++;H=H/1E3-this.D;D=D/1E3-this.D;J=new G7(H,D-H,5,p,{textAlign:0,zm:0,V7:W*2.5,i6:J*5.33});Y=new u_(H,D-H,5,p,Y);this.A.push(J);this.A.push(Y)}}},gMM=class extends Zk{constructor(J,W){super();this.A=J;this.V=W;this.track=this.V.languageName==="CC3"?4:0;this.C=new F0X;this.C.A=1<<this.track}Y(J){J=new ch2(J,
this.A);if(o02(J)){for(;J.byteOffset<J.C.byteLength;)for(J.version===0?J.Y=XO(J)*(1E3/45):J.version===1&&(J.Y=XO(J)*4294967296+XO(J)),J.Z=Ii(J);J.Z>0;J.Z--){var W=Ii(J);let H=Ii(J),D=Ii(J);W&4&&(W&3)===this.track&&(this.track===0||this.track===1)&&(W=this.C,W.C.push({time:J.Y,type:this.track,gC:H,qd:D,order:W.C.length}))}GgX(this.C,J);return J.A}return[]}reset(){this.C.clear()}};var qT2=class extends EG{constructor(J,W,H,D,Y,p,E,Q,w,k){super(J,W,H,D,Y,p,E,Q,w,k);this.type=2;this.Tl=[];this.tR=this.zl=this.j$=0;this.yY=NaN;this.XO=0;this.JX=null;this.PC=new g.KA(this.Ff,433,this);this.B&&(k.createClientVe(this.B,this,167342),this.O(this.B,"click",()=>{k.logClick(this.B)}),J=new g.e4(this.element,!0),g.n(this,J),J.subscribe("hoverstart",()=>{k.logVisibility(this.B,!0)},this));
g.en(this.element,"ytp-caption-window-rollup");g.n(this,this.PC);g.oz(this.element,"overflow","hidden")}le(){var J=this.PC;J.stop();J.zP()}Ff(){this.element.removeEventListener("transitionend",this.Ff,!1);g.mU(this.element,"ytp-rollup-mode");this.N(this.JX,!0)}NQ(){return this.D?this.tR:this.zl}tX(){return this.D?this.zl:this.tR}N(J,W){this.JX=J;if(this.Y.params.Mt){var H=0;for(let D=0;D<this.K.length&&H<J.length;D++)this.K[D]===J[H]&&H++;H>0&&H<J.length&&(J=this.K.concat(J.slice(H)));this.XO=this.tR;
this.zl=this.tR=0;super.N(J);DaW(this,W)}super.N(J)}};var C5W=class{constructor(J,W,H,D){this.J=J;this.Z=W;this.logger=H;this.Ag=D;this.Bi=[];this.C=null;this.Y=[];this.Rw=[];this.A=null;J=g.iO(this.J.j().experiments,"html5_override_micro_discontinuities_threshold_ms");this.V=J>0?J:10}unload(){this.A!=null&&(this.J.removeEventListener("sabrCaptionsDataLoaded",this.A),this.A=null);this.Bi=[];this.C=null;this.Y=[];this.J.Yk("sabrCaptionsBufferedRangesUpdated",this.Bi)}X(J){return{formatId:g.La(J.info.wl.info,this.Ag),DU:J.info.DU+(this.Ag?0:1),startTimeMs:J.info.V*
1E3,durationMs:J.info.X*1E3}}};var e0S=class extends Qj{constructor(J,W){super(W);this.A=J;this.J=W;this.logger=new g.Ne("caps");this.B=this.IB=null;this.N=new C5W(this.J,this,this.logger,this.A.Ag)}X(J,W,H){this.Y();W=J.getId();W=W!=null&&W in this.A.C?this.A.C[W]:null;W||(W=J.languageCode,W=this.A.isManifestless?MoX(this,W,"386"):MoX(this,W));W&&(this.B=J,this.IB=W,wko(this.N,H),this.J.Yk("sabrCaptionsTrackChanged",g.La(W.info,this.A.Ag)))}V(J){var W=this.A.isManifestless?ajX(this,"386"):ajX(this);for(let H of W)O8(this.C,H);
J.QE()}Y(){this.B&&(this.B=this.IB=null,this.N.unload(),this.J.Yk("sabrCaptionsTrackChanged",null))}D(){return""}};var k3W="WEBVTT".split("").map(J=>J.charCodeAt(0)),STW=class extends Zk{constructor(){super()}Y(J,W){J instanceof ArrayBuffer&&(J=g.eE(new Uint8Array(J)));
var H=[];J=J.split(Ab2);for(let P=1;P<J.length;P++){var D=J[P],Y=W;if(D!==""&&!m2p.test(D)){var p=M$.exec(D);if(p&&p.length>=4){var E=Le(p[1]),Q=Le(p[2])-E;E+=Y;var w=(p=p[3])?p.split(" "):[];p={};var k=null;var K="";var r=null,C="";for(let u of w){w=u.split(":");if(w.length!==2)continue;var e=w[1];switch(w[0]){case "line":w=e.split(",");w[0].endsWith("%")&&(k=w[0],p.i6=Number.parseInt(k,10),w.length===2&&(K=w[1].trim()));break;case "position":w=e.split(",");r=w[0];p.V7=Number.parseInt(r,10);w.length===
2&&(C=w[1].trim());break;case "align":switch(e){case "start":p.textAlign=0;break;case "middle":p.textAlign=2;break;case "end":p.textAlign=1}}}k||K||(K="end");if(!r)switch(p.textAlign){case 0:p.V7=0;break;case 1:p.V7=100;break;case 2:p.V7=50}if(p.textAlign!=null){k=0;switch(K){case "center":k+=3;break;case "end":k+=6;break;default:k+=0}switch(C){case "line-left":k+=0;break;case "center":k+=1;break;case "line-right":k+=2;break;default:switch(p.textAlign){case 0:k+=0;break;case 2:k+=1;break;case 1:k+=
2}}K=k<0||k>8?7:k;p.zm=K}D=D.substring(M$.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");C=p;p={};if(D.indexOf("<")<0&&D.indexOf("&")<0)Y=K0W(E,Q,5,C),E=new u_(E,Q,5,Y.id,D,!1,g.px(p)?void 0:p),H.push(Y),H.push(E),Y.C.push(E);else for(K=D.split(O3X),K.length===1?(D=5,C=K0W(E,Q,D,C)):(k=D=6,C=Object.assign({GJ:32},C),C=new G7(E,Q,k,"_"+s8++,C)),H.push(C),k=E,r=0;r<K.length;r++)if(w=K[r],r%2===0){e=j5(`<html>${w}</html>`);let u;e.getElementsByTagName("parsererror").length?(u=e.createElement("span"),
u.appendChild(e.createTextNode(w))):u=e.firstChild;rsw(this,k,Q-(k-E),D,C,r>0,u,p,H)}else k=Le(w)+Y}M$.lastIndex=0}}return H}},m2p=/^NOTE/,Ab2=/(?:\r\n|\r|\n){2,}/,M$=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),O3X=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var jYe=class extends g.RA{constructor(J,W){super();this.J=J;this.W=W;this.C=null;this.L9=this.J.D2();this.logger=new g.Ne("caps")}clear(){this.C&&this.C.dispose();this.C=null}reset(){this.C&&this.C.reset()}VY(){super.VY();this.clear()}};var maL={windowColor:"#080808",windowOpacity:0,textAlign:2,zm:7,V7:50,i6:100,isDefault:!0,PZ:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},AsL={windowColor:"#080808",windowOpacity:0,textAlign:0,zm:7,V7:50,i6:100,isDefault:!0,PZ:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.sC("captions",class extends g.mf{constructor(J){super(J);this.J=J;this.Tl=[];this.tR={};this.i9={};this.B=!1;this.Y="NONE";this.C=this.K=this.N=this.Er=this.Ka=null;this.bW={QE:()=>{this.QE()},
Y8:(D,Y,p,E,Q=0)=>{var w=Number(this.videoData.j().La().C.pa(g.Kjp)??0);Q>0&&w>0&&this.videoData.lengthSeconds>0&&Q/this.videoData.lengthSeconds>w?this.J.S("tts",{dropcap:Q}):this.Y8(D,Y,p,E)}};
this.Mm=this.A=null;this.W=this.J.j();this.videoData=this.J.getVideoData();this.Ff=this.J.MQ();this.Z={PZ:{}};this.D={PZ:{}};g.RF(this.videoData)?this.Y="OFFLINE":g.W_S(this.videoData,this.J)?this.Y="HLS":Z$2(this.videoData,this.J)?this.Y="SABR_LIVE":g.HtL(this.videoData,this.J)?this.Y="LIVE":this.videoData.captionTracks.length?this.Y="INNERTUBE":this.videoData.hg&&(this.Y="TTS");this.u9=this.W.controlsType==="3";this.j$=new jYe(this.J,this.W);this.b9=new g.iP(this);this.X=new g.kD({G:"div",AR:"ytp-caption-window-container",
X4:{id:"ytp-caption-window-container"}});this.zl={top:0,right:0,bottom:0,left:0,width:1,height:1};var W=null,H=g.F$("yt-html5-player-modules::subtitlesModuleData");H&&(W=new g.sl(H));this.storage=W;W=J.vC();this.kQ=!!W?.i9();this.dP=!!W?.j$();this.V=Ri(this);this.IB=elt(this);g.n(this,this.j$);this.V?this.oB=this.yY=null:(this.yY=new g.aI(this.lW,void 0,this),g.n(this,this.yY),this.oB=new g.KA(this.XO,2E3,this),g.n(this,this.oB));g.n(this,this.b9);g.uX(this.player,this.X.element,4);g.n(this,this.X);
this.V||this.b9.O(J,"resize",this.hR);W=g.vl(this.W)&&!g.D$()&&!this.J.isFullscreen();H=this.W.La().C.pa(g.GBe)&&g.p6(this.W)&&g.lL;(this.Qq=(W||H)&&!this.V&&!this.IB)&&this.b9.O(J,W?"resize":"fullscreentoggled",this.G5);this.b9.O(J,"onPlaybackAudioChange",this.hg);this.b9.O(J,g.Wd("captions"),D=>{this.onCueRangeEnter(D)});
this.b9.O(J,g.Hd("captions"),D=>{this.onCueRangeExit(D)});
dX(this,ml()||{});g.aj(this.player,"onCaptionsModuleAvailable");this.Y==="HLS"&&this.V&&(J=this.J.vC().BC(),this.dP&&this.b9.O(J.textTracks,"addtrack",this.NQ))}VY(){if(this.V||this.IB){let J=this.J.vC();J&&!J.F4()&&J.B()}else vF(this,!1);super.VY()}pN(){if(this.u9)return this.V||this.IB;if(this.Y==="HLS")return this.V;var J=this.getAudioTrack();if(toV(this)){if(!J.captionTracks.length)return!1;if(!this.C)return!0}J=e5(J,g.kB(this.W));return J==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:J==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?
cF(this):T7(this)||cF(this)?!0:PsX(this)}load(){super.load();this.K=this.getAudioTrack();if(this.C)this.A&&(this.j$.clear(),this.V?xa2(this,!0):this.player.getPresentingPlayerType()!==3&&this.C.X(this.A,"json3",this.bW),this.Y!=="HLS"&&this.V||this.IB||oi(this)||g.aj(this.player,"captionschanged",Ce(this.A)));else{if(this.Y==="OFFLINE")var J=new $22(this.player,this.videoData,this.getAudioTrack());else this.Y==="SABR_LIVE"?J=new e0S(this.videoData.C,this.player):this.Y==="HLS"?J=new hl2(this.player):
this.Y==="LIVE"?J=new L02(this.videoData.C,this.player):this.Y==="INNERTUBE"?J=new i$2(this.player,this.videoData,this.getAudioTrack()):(J=this.videoData,J=new Rl2(this.player,this.videoData.hg,this.videoData.videoId,J.captionsLanguagePreference||J.Ca.captionsLanguagePreference||g.ta(J,"yt:cc_default_lang")||J.Ca.lW,this.videoData.uD,this.videoData.eventId));this.C=J;g.n(this,this.C);this.C.V(this.bW)}}unload(){this.V&&this.A?xa2(this,!1):(this.oB&&this.oB.YR(),this.player.Zo("captions"),this.Tl=
[],this.C&&this.C.Y(),this.j$.clear(),this.N&&this.player.FB(this.N),this.hR());super.unload();this.player.fH();g.aj(this.player,"captionschanged",{})}create(){this.pN()&&this.load();var J;a:{if(this.W.L("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(J=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(let W of J)if(W.kind==="asr"&&W.languageCode==="en"){J=
!0;break a}J=!1}J&&this.J.Yk("showpromotooltip",this.X.element)}QE(){var J=e5(this.player.getAudioTrack(),g.kB(this.W));var W=J==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?W4(this,this.B):J==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&cF(this)?Jz(this):T7(this)||this.B||PsX(this)?W4(this,this.B):cF(this)?Jz(this):null;if(this.Y!=="HLS"&&this.V||this.IB){let H=this.C.C.C(!0);J=[];for(let D=0;D<H.length;D++){let Y=H[D],p=g.Ni("TRACK");p.setAttribute("kind","subtitles");p.setAttribute("label",g.TB(Y));p.setAttribute("srclang",
g.ca(Y));p.setAttribute("id",Y.toString());this.IB||p.setAttribute("src",this.C.D(Y,"vtt"));Y===W&&p.setAttribute("default","1");J.push(p)}W=this.J.vC();W.zl(J);J=W.BC();this.dP&&this.b9.O(J.textTracks,"change",this.SR)}else!this.A&&W&&pM(this,W),g.aj(this.player,"onCaptionsTrackListChanged"),g.kU(this.player,"onApiChange")}SR(){var J=this.J.vC().BC().textTracks,W=null;for(let H=0;H<J.length;H++)if(J[H].mode==="showing")a:{W=this.C.C.C(!0);for(let D=0;D<W.length;D++)if(W[D].toString()===J[H].id){W=
W[D];break a}W=null}(this.loaded?this.A:null)!==W&&pM(this,W,!0)}NQ(){this.C?.V(this.bW)}uz(){!this.A&&this.V||this.unload()}Y8(J,W,H,D){if(J){YK(this,this.A??void 0);this.C.b9()&&(this.Tl=[],this.J.Zo("captions"),gX(this.yY),this.j$.reset());a:{var Y=this.j$;D=D||0;H=$aW(Y,J,H||0);J=[];try{for(let y of H){let X=y.trackData,F=y.He,T=Y.W.L("safari_live_drm_captions_fix");if(typeof X!=="string"){H=J;var p=H.concat;if(T&&b$S(X))var E=gC2(Y,X,F);else{var Q=Y,w=W,k=X,K=F,r=D;if(!Jst(k))throw Error("Invalid binary caption track data");
Q.C||(Q.C=new gMM(r,w));E=Q.C.Y(k,K)}var C=p.call(H,E)}else{if(X.substring(0,6)==="WEBVTT")var e=J.concat(gC2(Y,X,F));else{H=J;var P=H.concat;b:{w=Y;Q=W;if(X[0]==="{")try{w.C||(w.C=new f2t(CsS(Q)));var u=w.C.Y(X,F);break b}catch(A2){g.a7(A2);u=[];break b}let Qt=j5(X);if(!Qt||!Qt.firstChild){let A2=Error("Invalid caption track data");A2.params=X;throw A2;}if(Qt.firstChild.tagName==="timedtext"){if(Number(Qt.firstChild.getAttribute("format"))===3){k=Qt;w.C||(w.C=new WuV(CsS(Q)));u=w.C.Y(k,F);break b}let A2=
Error("Unsupported subtitles format in web player (Format2)");A2.params=X;throw A2;}if(Qt.firstChild.tagName==="transcript"){let A2=Error("Unsupported subtitles format in web player (Format1)");A2.params=X;throw A2;}let ke=Error("Invalid caption track data");ke.params=X;throw ke;}e=P.call(H,u)}C=e}J=C}var h=J;break a}catch(y){g.uH(Y.logger,187101178,`Captions parsing failed: ${y.message}. `);Y.clear();h=[];break a}h=void 0}this.W.L("html5_sabr_live_support_subfragmented_captions")&&this.C instanceof
e0S&&(W=this.C.N,Y=[],h.length>0&&(Y=h.slice(W.Y.length)),W.Y=!W.C||W.C.info.hX?[]:h,h=Y);h.length>0&&(W=this.A,this.e0(W,!!W,oi(this)?"g":this.B?"m":"s"));this.player.FB(h,void 0,this.Y==="LIVE"||this.Y==="SABR_LIVE");!this.B||this.IB||oi(this)||g.EZ(this.W)||g.Dl(this.W)||g.Fc(this.W)||this.W.B==="shortspage"||this.player.isInline()||(this.oB.YR(),h=dMo({zm:0,V7:5,i6:5,Mt:2,textAlign:0,wN:0,lang:"ru"}),this.Er=[h],W=["\u0414\u043b\u044f \u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u043d\u0430\u0436\u043c\u0438\u0442\u0435 \u043d\u0430 \u0437\u043d\u0430\u0447\u043e\u043a ",
""],this.Ka||(Y=new g.WG({G:"svg",X4:{height:"100%",version:"1.1",viewBox:"0 0 36 36",width:"100%"},ZU:[{G:"path",Bg:!0,X4:{d:"m 23.94,18.78 c .03,-0.25 .05,-0.51 .05,-0.78 0,-0.27 -0.02,-0.52 -0.05,-0.78 l 1.68,-1.32 c .15,-0.12 .19,-0.33 .09,-0.51 l -1.6,-2.76 c -0.09,-0.17 -0.31,-0.24 -0.48,-0.17 l -1.99,.8 c -0.41,-0.32 -0.86,-0.58 -1.35,-0.78 l -0.30,-2.12 c -0.02,-0.19 -0.19,-0.33 -0.39,-0.33 l -3.2,0 c -0.2,0 -0.36,.14 -0.39,.33 l -0.30,2.12 c -0.48,.2 -0.93,.47 -1.35,.78 l -1.99,-0.8 c -0.18,-0.07 -0.39,0 -0.48,.17 l -1.6,2.76 c -0.10,.17 -0.05,.39 .09,.51 l 1.68,1.32 c -0.03,.25 -0.05,.52 -0.05,.78 0,.26 .02,.52 .05,.78 l -1.68,1.32 c -0.15,.12 -0.19,.33 -0.09,.51 l 1.6,2.76 c .09,.17 .31,.24 .48,.17 l 1.99,-0.8 c .41,.32 .86,.58 1.35,.78 l .30,2.12 c .02,.19 .19,.33 .39,.33 l 3.2,0 c .2,0 .36,-0.14 .39,-0.33 l .30,-2.12 c .48,-0.2 .93,-0.47 1.35,-0.78 l 1.99,.8 c .18,.07 .39,0 .48,-0.17 l 1.6,-2.76 c .09,-0.17 .05,-0.39 -0.09,-0.51 l -1.68,-1.32 0,0 z m -5.94,2.01 c -1.54,0 -2.8,-1.25 -2.8,-2.8 0,-1.54 1.25,-2.8 2.8,-2.8 1.54,0 2.8,1.25 2.8,2.8 0,1.54 -1.25,2.8 -2.8,2.8 l 0,0 z",
fill:"#fff"}}]}),g.n(this,Y),this.Ka=Y.element),Y=h.end-h.start,(C=g.TB(this.A))&&this.Er.push(new u_(h.start,Y,0,h.id,C)),this.Er.push(new u_(h.start,Y,0,h.id,W[0]),new u_(h.start,Y,0,h.id,this.Ka,!0),new u_(h.start,Y,0,h.id,W[1],!0)),this.player.FB(this.Er),g.r9(this.oB));!this.B||this.IB||oi(this)||(this.W.L("enable_player_captions_persistence_state_machine")?BF(this,!0):g.kB(this.W)?H4(this,!0):Dk(this,!0),this.K&&(this.K.V=this.A),this.player.fH());this.B=!1}}onCueRangeEnter(J){this.Tl.push(J);
gX(this.yY)}onCueRangeExit(J){g.FH(this.Tl,J);this.C instanceof L02&&this.C.IB&&this.player.dN([J]);gX(this.yY)}getCaptionWindowContainerId(){return this.X.element.id}XO(){O$p(this,this.Er);this.Er=null}lW(){if(!this.Qq||!this.V){this.yY.stop();g.E9(this.i9);this.Tl.sort(g.JU);var J=this.Tl;if(this.N){let W=g.q9(J,function(H){return this.N.indexOf(H)===-1},this);
W.length&&(J=W)}for(let W of J)W instanceof G7?NuS(this,W):ukt(this,W);for(let [W,H]of Object.entries(this.tR)){let D=W,Y=H;this.i9[D]?(Y.element.parentNode||(Y instanceof qT2||Y instanceof G3S||g.dk(this.tR,(p,E)=>{E!==D&&p.Y.params.zm===Y.Y.params.zm&&p.Y.params.V7===Y.Y.params.V7&&p.Y.params.i6===Y.Y.params.i6&&(p.dispose(),delete this.tR[E]);return E===D},this),this.X.element.appendChild(Y.element)),Y.N(this.i9[D])):(Y.dispose(),delete this.tR[D])}}}BE(){dX(this,{},!0);
g.aj(this.player,"captionssettingschanged")}z7(){var J=this.W.L("enable_player_captions_new_style_defaults")?AsL:maL,W=J.PZ;J={background:W.background,backgroundOpacity:W.backgroundOpacity,charEdgeStyle:W.charEdgeStyle,color:W.color,fontFamily:W.fontFamily,fontSizeIncrement:W.fontSizeIncrement,fontStyle:W.bold&&W.italic?3:W.bold?1:W.italic?2:0,textOpacity:W.textOpacity,windowColor:J.windowColor,windowOpacity:J.windowOpacity};W=ml()||{};W.background!=null&&(J.background=W.background);W.backgroundOverride!=
null&&(J.backgroundOverride=W.backgroundOverride);W.backgroundOpacity!=null&&(J.backgroundOpacity=W.backgroundOpacity);W.backgroundOpacityOverride!=null&&(J.backgroundOpacityOverride=W.backgroundOpacityOverride);W.charEdgeStyle!=null&&(J.charEdgeStyle=W.charEdgeStyle);W.charEdgeStyleOverride!=null&&(J.charEdgeStyleOverride=W.charEdgeStyleOverride);W.color!=null&&(J.color=W.color);W.colorOverride!=null&&(J.colorOverride=W.colorOverride);W.fontFamily!=null&&(J.fontFamily=W.fontFamily);W.fontFamilyOverride!=
null&&(J.fontFamilyOverride=W.fontFamilyOverride);W.fontSizeIncrement!=null&&(J.fontSizeIncrement=W.fontSizeIncrement);W.fontSizeIncrementOverride!=null&&(J.fontSizeIncrementOverride=W.fontSizeIncrementOverride);W.fontStyle!=null&&(J.fontStyle=W.fontStyle);W.fontStyleOverride!=null&&(J.fontStyleOverride=W.fontStyleOverride);W.textOpacity!=null&&(J.textOpacity=W.textOpacity);W.textOpacityOverride!=null&&(J.textOpacityOverride=W.textOpacityOverride);W.windowColor!=null&&(J.windowColor=W.windowColor);
W.windowColorOverride!=null&&(J.windowColorOverride=W.windowColorOverride);W.windowOpacity!=null&&(J.windowOpacity=W.windowOpacity);W.windowOpacityOverride!=null&&(J.windowOpacityOverride=W.windowOpacityOverride);return J}B8(J,W){var H={};Object.assign(H,ml());Object.assign(H,J);dX(this,H,W);g.aj(this.player,"captionssettingschanged")}hR(){!this.V&&this.loaded&&(g.Xw(this.tR,function(J,W){J.dispose();delete this.tR[W]},this),this.lW())}t_(J,W){switch(J){case "fontSize":if(isNaN(W))break;
J=g.qj(W,-2,4);this.B8({fontSizeIncrement:J});return J;case "reload":W&&!this.V&&pM(this,this.A,!0);break;case "stickyLoading":W!==void 0&&this.W.X&&(this.W.L("enable_player_captions_persistence_state_machine")?BF(this,!(!W||!W.userInitiated)):g.kB(this.W)?H4(this,!!W):Dk(this,!!W));break;case "track":return nCw(this,W);case "tracklist":return this.C?g.nZ(this.C.C.C(!(!W||!W.includeAsr)),H=>Ce(H)):[];
case "translationLanguages":return this.C?this.C.K.map(H=>Object.assign({},H)):[];
case "sampleSubtitles":this.V||W===void 0||vF(this,!!W);break;case "sampleSubtitlesCustomized":this.V||vF(this,!!W,W);break;case "recommendedTranslationLanguages":return g.Uc();case "defaultTranslationSourceTrackIndices":return this.C?this.C.zl:[]}}getOptions(){var J="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.W.X&&J.push("stickyLoading");return J}uE(){var J=this.A;if(this.J.CH("captions")){if(this.W.L("html5_modify_caption_vss_logging"))return(J=this.videoData.OT??
null)?{cc:g.ol(J)}:{};if(J){let W=J.vssId;J.translationLanguage&&W&&(W=`t${W}.${g.ca(J)}`);return{cc:W}}}return{}}Hb(J){this.isSubtitlesOn()?(this.W.L("enable_player_captions_persistence_state_machine")&&J?BF(this,!1):g.kB(this.W)?H4(this,!1):Dk(this,!1),YK(this),pM(this,null,!0)):this.H8(J)}H8(J){var W=oi(this)||!this.A?W4(this,!0):this.A;W&&this.Um(W.vssId,"m");this.isSubtitlesOn()||pM(this,W,this.W.L("enable_player_captions_persistence_state_machine")?J:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.A&&!oi(this)}hg(){var J=oi(this);cF(this,J)?pM(this,this.getAudioTrack().C,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),toV(this)&&(this.B=!1,this.A=null,this.C&&(this.C.dispose(),this.C=null)),this.pN()&&(J?pM(this,W4(this,!1),!1):this.load()))}c9(J){if(this.W.experiments.W4("web_enable_captions_set_target_container")&&J!==this.Mm){var W=this.X.element;W.parentNode&&g.iQ(W);(this.Mm=J)?(this.Mm.appendChild(W),W.style.position="absolute",W.style.bottom="0",W.style.left=
"0",W.style.width="100%",W.style.height="auto",W.style.top="auto"):(g.uX(this.player,W,4),W.style.position="absolute",W.style.bottom="auto",W.style.left="0",W.style.width="100%",W.style.height="100%",W.style.top="0");this.hR()}}FI(J){J&&(this.zl={top:J.top,right:J.right,bottom:J.bottom,left:J.left,width:1-J.left-J.right,height:1-J.top-J.bottom},this.X.element.style.top=`${this.zl.top*100}%`,this.X.element.style.left=`${this.zl.left*100}%`,this.X.element.style.width=`${this.zl.width*100}%`,this.X.element.style.height=
`${this.zl.height*100}%`,this.X.element.style.position="absolute",J=sOX(this))&&(this.X.element.style.width=`${J.width}px`,this.X.element.style.height=`${J.height}px`)}onVideoDataChange(J,W){J==="newdata"&&(this.videoData=W,this.loaded&&this.unload(),this.B=!1,this.A=null,this.C&&(this.C.dispose(),this.C=null,g.aj(this.player,"captionschanged",{})),this.pN()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}G5(){if(this.W.La().C.pa(g.GBe)){if(this.loaded&&this.unload(),this.u9=this.J.isFullscreen()||
this.W.controlsType==="3",this.V=Ri(this),this.IB=elt(this),this.V||this.IB){var J=this.J.vC();J&&!J.F4()&&J.B();this.QE()}}else(J=this.J.vC())&&!J.F4()&&J.B(),this.J.isFullscreen()?(this.V=this.u9=!0,this.loaded&&this.QE()):(this.u9=this.W.controlsType==="3",this.V=Ri(this));pM(this,this.A)}gP(){var J=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;J&&g.MO(this.player,"innertubeCommand",J)}e0(J,W,H){var D=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,Y="";J&&
(Y=J.vssId,Y=Y.replace(D,""));var p="";J&&J.getId()&&(p=J.getId()||"");J&&J.getXtags()&&(J=J.getXtags(),J=J.replace(D,""),p=p.concat(`;${J}`));this.Y==="HLS"&&(p="");this.J.e0(W?Y:"",W?p:"",H)}Um(J,W){J=(J||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");J.length>0&&this.J.Um(J,W)}});})(_yt_player);
