(function(g){var window=this;'use strict';var rNx=function(J,W){g.LQ(J,"onAutonavCoundownStarted",W)},f7x=function(J){return J.isBackground()&&J.CB()},$oZ=function(J,W){W=W.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.nextButton?.buttonRenderer;
J.qm=W?.navigationEndpoint;W=W?.trackingParams;J.playButton&&W&&J.X.setTrackingParams(J.playButton.element,W)},k0=function(J){var W=MM(J),H=Math,D=H.min;
var Y=J.B?Date.now()-J.B:0;H=D.call(H,Y,W);a2(J,Math.ceil((W-H)/1E3));W-H<=500&&J.C()?J.select(!0):J.C()&&J.S.start()},bb=function(J){var W=J.X.ma(!0,J.X.isFullscreen());
g.xb(J.container.element,"ytp-autonav-endscreen-small-mode",J.y7(W));g.xb(J.container.element,"ytp-autonav-endscreen-is-premium",!!J.suggestion&&!!J.suggestion.Ku);g.xb(J.X.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!J.X.I9());g.xb(J.X.getRootNode(),"countdown-running",J.C());g.xb(J.container.element,"ytp-player-content",J.X.I9());J.X.U("web_post_play_autonav_embiggening")||g.yC(J.overlay.element,{width:`${W.width}px`});if(J.X.U("web_post_play_autonav_embiggening")){var H=J.X.getRootNode().getBoundingClientRect();
W=Math.min(720,H.width*.5);var D=W*.5625;H=H.height-36-60;D>H&&(D=H,W=16/9*D);g.yC(J.A.ZU("ytp-autonav-endscreen-upnext-thumbnail"),{height:`${D}px`,width:`${W}px`});g.yC(J.container.element,{width:`${W}px`})}J.C()||(J.X.I9()?a2(J,Math.round(MM(J)/1E3)):a2(J),W=!!J.suggestion&&!!J.suggestion.OU,D=J.X.getVideoData(),D=D?.autonavState===1&&D?.BC&&J.X.I9()?!1:J.X.I9()||!(J.suggestion&&J.suggestion.OU),g.xb(J.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!D&&W),g.xb(J.container.element,
"ytp-autonav-endscreen-upnext-no-alternative-header",D&&!W),J.L.n9(J.X.I9()))},a2=function(J,W=-1){J=J.A.ZU("ytp-autonav-endscreen-upnext-header");
g.KR(J);if(W>=0){W=String(W);let D="\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],Y="\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".indexOf(D);if(Y>=0){var H=g.kA("\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".slice(0,Y));J.appendChild(H);H=
g.ab("span");g.m5(H,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Sj(H,W);J.appendChild(H);W=g.kA("\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".slice(Y+D.length));J.appendChild(W);return}}g.Sj(J,"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435")},MM=function(J){return J.X.isFullscreen()?(J=J.X.getVideoData()?.Fr,J===-1||J===void 0?8E3:J):J.X.pI()>=0?J.X.pI():g.K9(J.X.G().experiments,"autoplay_time")||1E4},
Kj=function(J,W){W=Sux(J,W);
var H=Math,D=H.min;var Y=(0,g.d)()-J.B;H=D.call(H,Y,W);W=W===0?1:Math.min(H/W,1);J.DU.setAttribute("stroke-dashoffset",`${-211*(W+1)}`);W>=1&&J.C()&&!J.isCasting()?J.select(!0):J.C()&&J.A.start()},Sux=function(J,W){return W?W:J.api.isFullscreen()?(J=J.api.getVideoData()?.Fr,J===-1||J===void 0?8E3:J):J.api.pI()>=0?J.api.pI():g.K9(J.api.G().experiments,"autoplay_time")||1E4},rK=function(J){return g.OD(J.player)&&J.S()&&!J.V},fj=function(J){var W=J.I9();
W!==J.J&&(J.J=W,J.player.publish("autonavvisibility"))},$0=function(J){return g.OD(J.player)&&J.S()&&!J.Z},Sc=function(J){var W=J.I9();
W!==J.Ca&&(J.Ca=W,J.player.publish("autonavvisibility"))},gyP=function(J){J=J.G();
return J.Ea&&!J.disableOrganicUi},C9x=function(J){var W=J.player.getVideoData();
if(!W||J.C===W.kQ)return!1;J.C=W.kQ;return!0},e69=function(J){J.player.lx("endscreen");
var W=J.player.getVideoData();W=new g.ha(Math.max((W.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var H=new g.ha(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});J.player.yR([W,H])};
g.Kr.prototype.pI=g.De(15,function(){return this.app.pI()});
g.D4.prototype.pI=g.De(14,function(){return this.getVideoData().aj});
g.bE.prototype.Ge=g.De(13,function(J){this.jS().Ge(J)});
g.Fg.prototype.Ge=g.De(12,function(J){this.w6!==J&&(this.w6=J,this.iV())});
var gK=class extends g.c{constructor(J){super({D:"div",W:"ytp-autonav-endscreen-countdown-overlay"});this.cancelCommand=this.qm=void 0;this.B=0;J.U("web_post_play_autonav_embiggening")&&g.jJ(this.element,"ytp-autonav-endscreen-upnext-updated");this.container=new g.c({D:"div",W:"ytp-autonav-endscreen-countdown-container"});g.q(this,this.container);this.container.pa(this.element);var W=J.G(),H=W.V;this.X=J;this.suggestion=null;this.onVideoDataChange("newdata",this.X.getVideoData());this.j(J,"videodatachange",
this.onVideoDataChange);this.A=new g.c({D:"div",W:"ytp-autonav-endscreen-upnext-container",N:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},K:[{D:"div",W:"ytp-autonav-endscreen-topbar-container",K:[{D:"div",W:"ytp-autonav-endscreen-upnext-header"},{D:"div",W:"ytp-autonav-endscreen-upnext-alternative-header",tR:"{{autoplayAlternativeHeader}}"}]},{D:"a",W:"ytp-autonav-endscreen-link-container",
N:{href:"{{url}}",target:H?W.Ca:""},K:[{D:"div",W:"ytp-autonav-endscreen-upnext-thumbnail",N:{style:"{{background}}"},K:[{D:"div",N:{"aria-label":"{{timestamp}}"},Tl:["ytp-autonav-timestamp"],tR:"{{duration}}"},{D:"div",Tl:["ytp-autonav-live-stamp"],tR:"\u0412 \u044d\u0444\u0438\u0440\u0435"},{D:"div",Tl:["ytp-autonav-upcoming-stamp"],tR:"\u0421\u043a\u043e\u0440\u043e \u0432 \u044d\u0444\u0438\u0440\u0435"}]},{D:"div",W:"ytp-autonav-endscreen-video-info",K:[{D:"div",W:"ytp-autonav-endscreen-premium-badge"},
{D:"div",W:"ytp-autonav-endscreen-upnext-title",tR:"{{title}}"},{D:"div",W:"ytp-autonav-endscreen-upnext-author",tR:"{{author}}"},{D:"div",W:"ytp-autonav-view-and-date",tR:"{{views_and_publish_time}}"},{D:"div",W:"ytp-autonav-author-and-view",tR:"{{author_and_views}}"}]}]}]});g.q(this,this.A);this.A.pa(this.container.element);H||this.j(this.A.ZU("ytp-autonav-endscreen-link-container"),"click",this.VY);this.X.createClientVe(this.container.element,this,115127);this.X.createClientVe(this.A.ZU("ytp-autonav-endscreen-link-container"),
this,115128);this.closeButton=new g.c({D:"button",W:"ytp-autonav-endscreen-upnext-header-close-button",N:{"aria-label":"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u0430\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435"}});g.q(this,this.closeButton);J.U("web_post_play_autonav_embiggening")&&(this.closeButton.listen("click",this.zl,this),this.X.createClientVe(this.closeButton.element,this,115129),this.A.ZU("ytp-autonav-endscreen-topbar-container").appendChild(this.closeButton.element));
this.overlay=new g.c({D:"div",W:"ytp-autonav-overlay"});g.q(this,this.overlay);this.overlay.pa(this.container.element);this.L=new g.c({D:"div",W:"ytp-autonav-endscreen-button-container"});g.q(this,this.L);this.L.pa(this.container.element);this.cancelButton=new g.c({D:"button",Tl:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],N:{"aria-label":"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u0430\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435"},
tR:"\u041e\u0442\u043c\u0435\u043d\u0430"});g.q(this,this.cancelButton);this.cancelButton.pa(this.L.element);this.cancelButton.listen("click",this.zl,this);this.X.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.c({D:"a",Tl:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button","ytp-autonav-endscreen-upnext-button-rounded"],N:{href:"{{url}}",role:"button","aria-label":"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 \u0432\u0438\u0434\u0435\u043e"},
tR:"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438"});g.q(this,this.playButton);this.playButton.pa(this.L.element);this.playButton.listen("click",this.VY,this);this.X.createServerVe(this.playButton.element,this.playButton,!0);(W=this.X.getVideoData())&&$oZ(this,W);this.S=new g.SJ(()=>{k0(this)},500);
g.q(this,this.S);this.Ca();this.j(J,"autonavvisibility",this.Ca)}J(J){this.suggestion!==J&&(this.suggestion=J,g.l2(this.A,J),this.playButton.updateValue("url",this.suggestion.L2()),bb(this))}C(){return this.B>0}Z(){this.C()||(this.B=Date.now(),k0(this),rNx(this.X,MM(this)),g.xb(this.X.getRootNode(),"countdown-running",this.C()))}V(){this.Y();k0(this);var J=this.A.ZU("ytp-autonav-endscreen-upnext-header");J&&g.Sj(J,"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435")}Y(){this.C()&&(this.S.stop(),
this.B=0)}select(J=!1){this.X.nextVideo(!1,J);this.Y()}VY(J){g.LC(J,this.X)&&(J.currentTarget===this.playButton.element?this.X.logClick(this.playButton.element):J.currentTarget===this.A.ZU("ytp-autonav-endscreen-link-container")&&(J=this.A.ZU("ytp-autonav-endscreen-link-container"),this.X.logVisibility(J,!0),this.X.logClick(J)),this.qm?(g.LQ(this.X,"innertubeCommand",this.qm),this.Y()):this.select())}zl(){this.X.logClick(this.cancelButton.element);g.fC(this.X,!0);this.cancelCommand&&g.LQ(this.X,"innertubeCommand",
this.cancelCommand)}onVideoDataChange(J,W){$oZ(this,W);this.cancelCommand=W.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.cancelButton?.buttonRenderer?.command}Ca(){var J=this.X.I9();this.eo!==J&&this.n9(J);bb(this);this.X.logVisibility(this.container.element,J);this.X.logVisibility(this.cancelButton.element,J);this.X.logVisibility(this.A.ZU("ytp-autonav-endscreen-link-container"),J);this.X.logVisibility(this.playButton.element,J)}y7(J){return J.width<
400||J.height<459}};var Cj=class extends g.c{constructor(J,W){super({D:"div",Tl:["html5-endscreen","ytp-player-content",W||"base-endscreen"]});this.created=!1;this.player=J}create(){this.created=!0}destroy(){this.created=!1}S(){return!1}I9(){return!1}qm(){return!1}};var ANf=class extends g.c{constructor(J){super({D:"div",Tl:["ytp-upnext","ytp-player-content"],N:{"aria-label":"{{aria_label}}"},K:[{D:"div",W:"ytp-cued-thumbnail-overlay-image",N:{style:"{{background}}"}},{D:"span",W:"ytp-upnext-top",K:[{D:"span",W:"ytp-upnext-header",tR:"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},{D:"span",W:"ytp-upnext-title",tR:"{{title}}"},{D:"span",W:"ytp-upnext-author",tR:"{{author}}"}]},{D:"a",W:"ytp-upnext-autoplay-icon",N:{role:"button",href:"{{url}}","aria-label":"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 \u0432\u0438\u0434\u0435\u043e"},
K:[{D:"svg",N:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},K:[{D:"circle",W:"ytp-svg-autoplay-circle",N:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",W:"ytp-svg-autoplay-ring",N:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",W:"ytp-svg-fill",N:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",W:"ytp-upnext-bottom",
K:[{D:"span",W:"ytp-upnext-cancel"},{D:"span",W:"ytp-upnext-paused",tR:"\u0410\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043f\u0440\u0438\u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e."}]}]});this.api=J;this.cancelButton=null;this.DU=this.ZU("ytp-svg-autoplay-ring");this.S=this.notification=this.A=this.suggestion=null;this.qm=new g.SJ(this.L,5E3,this);this.B=0;var W=this.ZU("ytp-upnext-cancel");this.cancelButton=
new g.c({D:"button",Tl:["ytp-upnext-cancel-button","ytp-button"],N:{tabindex:"0","aria-label":"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u0430\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435"},tR:"\u041e\u0442\u043c\u0435\u043d\u0430"});g.q(this,this.cancelButton);this.cancelButton.listen("click",this.zl,this);this.cancelButton.pa(W);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.q(this,this.qm);
this.api.createClientVe(this.element,this,18788);W=this.ZU("ytp-upnext-autoplay-icon");this.j(W,"click",this.VY);this.api.createClientVe(W,this,115130);this.Ca();this.j(J,"autonavvisibility",this.Ca);this.j(J,"mdxnowautoplaying",this.yY);this.j(J,"mdxautoplaycanceled",this.b9);g.xb(this.element,"ytp-upnext-mobile",this.api.G().Y)}L(){this.notification&&(this.qm.stop(),this.Mn(this.S),this.S=null,this.notification.close(),this.notification=null)}J(J){this.suggestion=J;g.l2(this,J,"hqdefault.jpg")}Ca(){this.n9(this.api.I9());
this.api.logVisibility(this.element,this.api.I9());this.api.logVisibility(this.ZU("ytp-upnext-autoplay-icon"),this.api.I9());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.I9())}RB(){window.focus();this.L()}Z(J){this.C()||(g.Ot("a11y-announce",`\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 ${this.suggestion.title}`),this.B=(0,g.d)(),this.A=new g.SJ(()=>{Kj(this,J)},25),Kj(this,J),rNx(this.api,Sux(this,J)));
g.P7(this.element,"ytp-upnext-autoplay-paused")}hide(){super.hide()}C(){return!!this.A}isCasting(){return this.api.getPresentingPlayerType()===3}V(){this.Y();this.B=(0,g.d)();Kj(this);g.jJ(this.element,"ytp-upnext-autoplay-paused")}Y(){this.C()&&(this.A.dispose(),this.A=null)}select(J=!1){if(this.api.G().U("autonav_notifications")&&J&&window.Notification&&typeof document.hasFocus==="function"){let W=Notification.permission;W==="default"?Notification.requestPermission():W!=="granted"||document.hasFocus()||
(this.L(),this.notification=new Notification("\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435",{body:this.suggestion.title,icon:this.suggestion.IU()}),this.S=this.j(this.notification,"click",this.RB),this.qm.start())}this.Y();this.api.nextVideo(!1,J)}VY(J){!g.$A(this.cancelButton.element,J.target)&&g.LC(J,this.api)&&(this.api.I9()&&this.api.logClick(this.ZU("ytp-upnext-autoplay-icon")),this.select())}zl(){this.api.I9()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.fC(this.api,
!0)}yY(J){this.isCasting();this.show();this.Z(J)}b9(){this.isCasting();this.Y();this.hide()}Yk(){this.Y();this.L();super.Yk()}};var mof=class extends Cj{constructor(J){super(J,"videowall-endscreen");this.X=J;this.stills=[];this.V=this.videoData=null;this.Z=this.J=!1;this.Ca=null;g.jJ(this.element,"modern-videowall-endscreen");this.A=new g.rC(this);g.q(this,this.A);this.L=new g.SJ(()=>{g.jJ(this.element,"ytp-show-tiles")},0);
g.q(this,this.L);this.table=new g.z6({D:"div",W:"ytp-modern-endscreen-content"});g.q(this,this.table);this.table.pa(this.element);J.getVideoData().kQ?this.C=new gK(J):this.C=new ANf(J);g.q(this,this.C);g.mL(this.player,this.C.element,4);J.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var J=this.player.getVideoData();J&&(this.videoData=J);this.Y();this.A.j(this.player,"appresize",this.Y);this.A.j(this.player,"onVideoAreaChange",this.Y);this.A.j(this.player,"videodatachange",
this.onVideoDataChange);this.A.j(this.player,"autonavchange",this.B);this.A.j(this.player,"onAutonavCancelled",this.zl);J=this.videoData.autonavState;J!==this.Ca&&this.B(J,!1);this.A.j(this.element,"transitionend",this.VY)}destroy(){this.A.A();g.jB(this.stills);this.stills=[];super.destroy();g.P7(this.element,"ytp-show-tiles");this.L.stop();this.Ca=this.videoData.autonavState}S(){return this.videoData?.BC||this.videoData.autonavState!==1}show(){var J=this.eo;super.show();g.P7(this.element,"ytp-show-tiles");
this.player.G().Y?g.CD(this.L):this.L.start();(this.Z||this.V&&this.V!==this.videoData.clientPlaybackNonce)&&g.fC(this.player,!1);rK(this)?(fj(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||f7x(this.player.JQ())&&this.player.U("web_player_pip_logging_fix")?this.C.select(!0):this.C.Z():this.videoData.autonavState===3&&this.C.V()):(g.fC(this.player,!0),fj(this));J!==this.eo&&this.player.logVisibility(this.element,!0)}hide(){var J=this.eo;super.hide();this.C.V();fj(this);
J!==this.eo&&this.player.logVisibility(this.element,!1)}VY(J){J.target===this.element&&this.Y()}Y(){var J=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.J()];if(J.length){var W=this.X.ma(!0,this.X.isFullscreen()),H=Math.floor((W.width-64+16)/(g.t3(W.width*.27,250,450)+16));W=Math.min(3,Math.floor((W.height-64)/((W.width-64-(H-1)*16)/H*.5625+70)));g.tG(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.jJ(this.element,`ytp-modern-endscreen-limit-rows-${W}`);g.xb(this.element,"ytp-modern-endscreen-single-item",H===1);g.xb(this.element,"ytp-modern-endscreen-row-0",W===0);H=this.table.element;H.ariaLive="polite";this.C.J(this.videoData.J());this.C instanceof gK&&bb(this.C);g.xb(this.element,"ytp-endscreen-takeover",rK(this));fj(this);W=0;H.ariaBusy="true";var D=J.length;for(let Y=0;Y<D;Y++){let p=Y%D,E=this.stills[Y];E||(E=new g.xjS(this.player),this.stills[Y]=E,H.appendChild(E.element));g.NUL(E,
J[p]);W++}this.stills.length=W}}onVideoDataChange(){var J=this.player.getVideoData({playerType:1});this.videoData!==J&&(J?.J()?(this.videoData=J,this.Y()):this.player.wl("missg",{vid:J?.videoId||"",cpn:J?.clientPlaybackNonce||""}))}qm(){return this.C.C()}B(J,W=!1){var H=this.videoData?.BC;if(J===1){if(!H||W)this.Z=!1,this.V=this.videoData.clientPlaybackNonce;this.C.Y();this.eo&&this.Y()}else this.Z=!0,this.eo&&rK(this)&&(J===2?this.C.Z():J===3&&this.C.V())}zl(J){if(J){for(J=0;J<this.stills.length;J++)this.X.logVisibility(this.stills[J].element,
!0);this.B(1,!0)}else this.V=null,this.Z=!1;this.Y()}I9(){return this.eo&&rK(this)}};var Ozp=class extends g.c{constructor(J){var W=J.G(),H=g.Pv||g.YB?{style:"will-change: opacity"}:void 0,D=W.V,Y=["ytp-videowall-still"];W.Y&&Y.push("ytp-videowall-show-text");super({D:"a",Tl:Y,N:{href:"{{url}}",target:D?W.Ca:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{D:"div",W:"ytp-videowall-still-image",N:{style:"{{background}}"}},{D:"span",W:"ytp-videowall-still-info",N:{"aria-hidden":"true"},K:[{D:"span",W:"ytp-videowall-still-info-bg",
K:[{D:"span",W:"ytp-videowall-still-info-content",N:H,K:[{D:"span",W:"ytp-videowall-still-info-title",tR:"{{title}}"},{D:"span",W:"ytp-videowall-still-info-author",tR:"{{author_and_views}}"},{D:"span",W:"ytp-videowall-still-info-live",tR:"\u0412 \u044d\u0444\u0438\u0440\u0435"},{D:"span",W:"ytp-videowall-still-info-duration",tR:"{{duration}}"}]}]}]},{D:"span",Tl:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],N:{"aria-hidden":"true"},K:[{D:"span",W:"ytp-videowall-still-listlabel-icon"},
"\u041f\u043b\u0435\u0439\u043b\u0438\u0441\u0442",{D:"span",W:"ytp-videowall-still-listlabel-length",K:[" (",{D:"span",tR:"{{playlist_length}}"},")"]}]},{D:"span",Tl:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],N:{"aria-hidden":"true"},K:[{D:"span",W:"ytp-videowall-still-listlabel-mix-icon"},"\u041c\u0438\u043a\u0441",{D:"span",W:"ytp-videowall-still-listlabel-length",tR:" (50+)"}]}]});this.suggestion=null;this.A=D;this.api=J;this.C=new g.rC(this);g.q(this,this.C);this.listen("click",
this.onClick);this.listen("keypress",this.onKeyPress);this.C.j(J,"videodatachange",this.onVideoDataChange);J.createServerVe(this.element,this);this.onVideoDataChange()}select(){this.api.g_(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.uq||void 0)&&this.api.logClick(this.element)}onClick(J){if(g.I_(this.api.G())&&this.api.U("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);let W=this.suggestion.L2(),
H={};g.CC(this.api,H);W=g.id(W,H);g.RF(W,this.api,J)}else g.LC(J,this.api,this.A,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(J){switch(J.keyCode){case 13:case 32:J.defaultPrevented||(this.select(),J.preventDefault())}}onVideoDataChange(){var J=this.api.getVideoData(),W=this.api.G();this.A=J.vZ?!1:W.V}};var jEZ=class extends Cj{constructor(J){super(J,"videowall-endscreen");this.X=J;this.V=0;this.stills=[];this.Z=this.videoData=null;this.L=this.Ca=!1;this.zl=null;this.Y=new g.rC(this);g.q(this,this.Y);this.B=new g.SJ(()=>{g.jJ(this.element,"ytp-show-tiles")},0);
g.q(this,this.B);var W=new g.c({D:"button",Tl:["ytp-button","ytp-endscreen-previous"],N:{"aria-label":"\u041d\u0430\u0437\u0430\u0434"},K:[g.q6()]});g.q(this,W);W.pa(this.element);W.listen("click",this.yY,this);this.table=new g.z6({D:"div",W:"ytp-endscreen-content"});g.q(this,this.table);this.table.pa(this.element);W=new g.c({D:"button",Tl:["ytp-button","ytp-endscreen-next"],N:{"aria-label":"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},K:[g.nY()]});g.q(this,W);W.pa(this.element);W.listen("click",
this.DU,this);J.getVideoData().kQ?this.C=new gK(J):this.C=new ANf(J);g.q(this,this.C);g.mL(this.player,this.C.element,4);J.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var J=this.player.getVideoData();J&&(this.videoData=J);this.A();this.Y.j(this.player,"appresize",this.A);this.Y.j(this.player,"onVideoAreaChange",this.A);this.Y.j(this.player,"videodatachange",this.onVideoDataChange);this.Y.j(this.player,"autonavchange",this.J);this.Y.j(this.player,"onAutonavCancelled",
this.VY);J=this.videoData.autonavState;J!==this.zl&&this.J(J,!1);this.Y.j(this.element,"transitionend",this.b9)}destroy(){this.Y.A();g.jB(this.stills);this.stills=[];super.destroy();g.P7(this.element,"ytp-show-tiles");this.B.stop();this.zl=this.videoData.autonavState}S(){return this.videoData?.BC||this.videoData?.autonavState!==1}show(){var J=this.eo;super.show();g.P7(this.element,"ytp-show-tiles");this.player.G().Y?g.CD(this.B):this.B.start();(this.L||this.Z&&this.Z!==this.videoData.clientPlaybackNonce)&&
g.fC(this.player,!1);$0(this)?(Sc(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||f7x(this.player.JQ())&&this.player.U("web_player_pip_logging_fix")?this.C.select(!0):this.C.Z():this.videoData.autonavState===3&&this.C.V()):(g.fC(this.player,!0),Sc(this));J!==this.eo&&this.player.logVisibility(this.element,!0)}hide(){var J=this.eo;super.hide();this.C.V();Sc(this);J!==this.eo&&this.player.logVisibility(this.element,!1)}b9(J){J.target===this.element&&this.A()}A(){var J=this.videoData?.suggestions?.length?
this.videoData?.suggestions:[this.videoData?.J()];if(J.length){g.jJ(this.element,"ytp-endscreen-paginate");var W=this.X.ma(!0,this.X.isFullscreen()),H=g.ZU(this.X);H&&(H=H.gN()?48:32,W.width-=H*2);var D=W.width/W.height,Y=96/54,p=H=2,E=Math.max(W.width/96,2),Q=Math.max(W.height/54,2),w=J.length;var Z=w*4;for(Z-=4;Z>0&&(H<E||p<Q);){var b=H/2,K=p/2,C=H<=E-2&&Z>=K*4,e=p<=Q-2&&Z>=b*4;if((b+1)/K*Y/D>D/(b/(K+1)*Y)&&e)Z-=b*4,p+=2;else if(C)Z-=K*4,H+=2;else if(e)Z-=b*4,p+=2;else break}Y=!1;Z>=12&&w*4-Z<=
6&&(p>=4||H>=4)&&(Y=!0);Z=H*96;E=p*54;D=Z/E<D?W.height/E:W.width/Z;D=Math.min(D,2);Z=Math.floor(Math.min(W.width,Z*D));E=Math.floor(Math.min(W.height,E*D));W=this.table.element;W.ariaLive="polite";g.Ws(W,Z,E);g.yC(W,{marginLeft:`${Z/-2}px`,marginTop:`${E/-2}px`});this.C.J(this.videoData.J());this.C instanceof gK&&bb(this.C);g.xb(this.element,"ytp-endscreen-takeover",$0(this));Sc(this);Z+=4;E+=4;D=0;W.ariaBusy="true";for(Q=0;Q<H;Q++)for(b=0;b<p;b++)if(C=D,e=0,Y&&Q>=H-2&&b>=p-2?e=1:b%2===0&&Q%2===0&&
(b<2&&Q<2?b===0&&Q===0&&(e=2):e=2),C=g.x4(C+this.V,w),e!==0){K=this.stills[D];K||(K=new Ozp(this.player),this.stills[D]=K,W.appendChild(K.element));var m=Math.floor(E*b/p);let u=Math.floor(Z*Q/H),n=Math.floor(E*(b+e)/p)-m-4,l=Math.floor(Z*(Q+e)/H)-u-4;g.ve(K.element,u,m);g.Ws(K.element,l,n);g.yC(K.element,"transitionDelay",(b+Q)/20+"s");g.xb(K.element,"ytp-videowall-still-mini",e===1);g.xb(K.element,"ytp-videowall-still-large",e>2);e=Math.max(l,n);g.xb(K.element,"ytp-videowall-still-round-large",
e>=256);g.xb(K.element,"ytp-videowall-still-round-medium",e>96&&e<256);g.xb(K.element,"ytp-videowall-still-round-small",e<=96);C=J[C];K.suggestion!==C&&(K.suggestion=C,e=K.api.G(),m=g.OK(K.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.l2(K,C,m),g.I_(e)&&!K.api.U("web_player_log_click_before_generating_ve_conversion_params")&&(e=C.L2(),m={},g.Fl(K.api,"addEmbedsConversionTrackingParams",[m]),e=g.id(e,m),K.updateValue("url",e)),(C=(C=C.sessionData)&&C.itct)&&K.api.setTrackingParams(K.element,
C));D++}W.ariaBusy="false";g.xb(this.element,"ytp-endscreen-paginate",D<w);for(J=this.stills.length-1;J>=D;J--)H=this.stills[J],g.fR(H.element),g.OQ(H);this.stills.length=D}}onVideoDataChange(){var J=this.player.getVideoData({playerType:1});this.videoData!==J&&(J?.J()?(this.V=0,this.videoData=J,this.A()):this.player.wl("missg",{vid:J?.videoId||"",cpn:J?.clientPlaybackNonce||""}))}DU(){this.V+=this.stills.length;this.A()}yY(){this.V-=this.stills.length;this.A()}qm(){return this.C.C()}J(J,W=!1){var H=
this.videoData?.BC;if(J===1){if(!H||W)this.L=!1,this.Z=this.videoData.clientPlaybackNonce;this.C.Y();this.eo&&this.A()}else this.L=!0,this.eo&&$0(this)&&(J===2?this.C.Z():J===3&&this.C.V())}VY(J){if(J){for(J=0;J<this.stills.length;J++)this.X.logVisibility(this.stills[J].element,!0);this.J(1,!0)}else this.Z=null,this.L=!1;this.A()}I9(){return this.eo&&$0(this)}};var Uo9=class extends g.c{constructor(J){super({D:"button",Tl:["ytp-watch-on-youtube-button","ytp-button"],tR:"{{content}}"});this.X=J;this.buttonType=this.buttonType=1;this.C();this.buttonType===2&&g.jJ(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.C);this.n9(!0)}C(){switch(this.buttonType){case 1:var J="\u041f\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u0442\u044c \u0441\u043d\u043e\u0432\u0430 \u043d\u0430 YouTube";var W=156915;
break;case 2:J="\u041f\u0440\u043e\u0434\u043e\u043b\u0436\u0438\u0442\u044c \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 \u043d\u0430 YouTube";W=156942;break;default:J="\u041f\u0440\u043e\u0434\u043e\u043b\u0436\u0438\u0442\u044c \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 \u043d\u0430 YouTube",W=156942}this.update({content:J});this.X.hasVe(this.element)&&this.X.destroyVe(this.element);this.X.createClientVe(this.element,this,W)}onClick(J){this.X.U("web_player_log_click_before_generating_ve_conversion_params")&&
this.X.logClick(this.element);g.RF(this.getVideoUrl(),this.X,J);this.X.U("web_player_log_click_before_generating_ve_conversion_params")||this.X.logClick(this.element)}getVideoUrl(){var J=!0;switch(this.buttonType){case 1:J=!0;break;case 2:J=!1}J=this.X.getVideoUrl(J,!1,!1,!0);var W=this.X.G();if(g.I_(W)){let H={};g.I_(W)&&g.Fl(this.X,"addEmbedsConversionTrackingParams",[H]);J=g.id(J,H)}return J}logVisibility(){this.X.logVisibility(this.element,this.eo&&this.AR)}show(){super.show();this.logVisibility()}hide(){super.hide();
this.logVisibility()}Da(J){super.Da(J);this.logVisibility()}};var P9F=class extends Cj{constructor(J){super(J,"watch-again-on-youtube-endscreen");this.watchButton=new Uo9(J);g.q(this,this.watchButton);this.watchButton.pa(this.element);g.UDe(J)&&(this.C=new g.rJT(J),g.q(this,this.C),this.A=new g.c({D:"div",Tl:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],N:{tabIndex:"-1"},K:[this.C]}),g.q(this,this.A),this.C.pa(this.A.element),this.A.pa(this.element));J.createClientVe(this.element,this,156914);this.hide()}hasSuggestions(){return this.C?.hasSuggestions()}show(){if(this.player.getPlayerState()!==
3){super.show();let W=this.A;if(W){var J=this.C.hasSuggestions();g.xb(this.element,"ytp-shorts-branded-ui",J);J?W.show():W.hide()}g.ZU(this.player)?.Ge(!0);this.player.logVisibility(this.element,!0);this.watchButton.Da(!0)}}hide(){super.hide();g.ZU(this.player)?.Ge(!1);this.player.logVisibility(this.element,!1);this.watchButton.Da(!1)}};g.cx("endscreen",class extends g.nr{constructor(J){super(J);this.endScreen=null;this.C=this.A=!1;this.listeners=new g.rC(this);g.q(this,this.listeners);var W=J.G();J.isEmbedsShortsMode()?this.endScreen=new P9F(J):gyP(J)?(this.A=!0,C9x(this),W.U("delhi_modern_endscreen")?this.endScreen=new mof(J):this.endScreen=new jEZ(J)):this.endScreen=new Cj(J);g.q(this,this.endScreen);g.mL(J,this.endScreen.element,4);e69(this);this.listeners.j(J,"videodatachange",this.onVideoDataChange,this);this.listeners.j(J,
g.VI("endscreen"),H=>{this.onCueRangeEnter(H)});
this.listeners.j(J,g.N0("endscreen"),H=>{this.onCueRangeExit(H)})}lB(){var J=this.player.getVideoData(),W=J.mutedAutoplay&&(J.limitedPlaybackDurationInSeconds>0||J.endSeconds>0||J.mutedAutoplayDurationMode!==2);
if(this.player.isEmbedsShortsMode()&&!W)return!0;var H=!(!J?.J()&&!J?.suggestions?.length);H=!gyP(this.player)||H;var D=J.fN,Y=this.player.P5();return(H||!!J?.BC)&&!D&&!Y&&!W}I9(){return this.endScreen.I9()}vu(){return this.I9()?this.endScreen.qm():!1}Yk(){this.player.lx("endscreen");super.Yk()}load(){{let H=this.player.getVideoData(),D=H.transitionEndpointAtEndOfStream;if(D&&D.videoId){var J=this.player.p9().Uh.get("heartbeat");var W=H.J();!W||D.videoId!==W.videoId||H.V$?(this.player.g_(D.videoId,
void 0,void 0,!0,!0,D),J&&J.vP("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),J=!0):J=!1}else J=!1}J||(super.load(),this.endScreen.show())}unload(){super.unload();this.endScreen.hide();this.endScreen.destroy()}onCueRangeEnter(J){this.lB()&&(this.endScreen.created||this.endScreen.create(),J.getId()==="load"&&this.load())}onCueRangeExit(J){J.getId()==="load"&&this.loaded&&this.unload()}onVideoDataChange(){e69(this);this.A&&C9x(this)&&
(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.endScreen=new jEZ(this.player),g.q(this,this.endScreen),g.mL(this.player,this.endScreen.element,4))}});})(_yt_player);
